### ISSUE TITLE
Only one devices appearing in Home Assistant

### ISSUE THREAD

**Issue by SylvainGa** [claudegel/sinope-130#1]
Hi, thank you very much for this integration :-)

Looks like I'm the first one to submit and issue :-)

I have 6 thermostats (five TH1123ZB and one TH1124ZB) as well as a GT130 hub. I chose the Neviweb setup because that's what HACS installed (I believe). In Home Assistant, only the Living room thermostat (the TH1124ZB) is showing, although the log shows it sees all of them. Is there something I most do have the other appears?

If I have to send the logs, is there something I must 'blank out' to anonymise it?

Thanks!

**Comment by SylvainGa** [comment]
Being a developer myself in a previous life, looking at the code, I saw what was wrong.

I replaced 
DEVICE_MODEL_FLOOR = [737]
DEVICE_MODEL_HEAT = [1124]
IMPLEMENTED_DEVICE_MODEL = DEVICE_MODEL_HEAT + DEVICE_MODEL_FLOOR

for 
DEVICE_MODEL_FLOOR = [737]
DEVICE_MODEL_HEAT3000W = [1123]
DEVICE_MODEL_HEAT4000W = [1124]
IMPLEMENTED_DEVICE_MODEL = DEVICE_MODEL_HEAT3000W + DEVICE_MODEL_HEAT4000W + DEVICE_MODEL_FLOOR

And my 1123 were discovered in HA :-)

I'll close this incident and let you decide if you want to add my modification or not.

**Comment by claudegel** [comment]
Hi Sylvain,

I'm just missing the device model # for all thermostat. I just own a
floor thermostat because all other are for the GT125. I was thinking
that model 1124 was for both 3000 and 4000W

so I've changed my code like this

DEVICE_MODEL_FLOOR = [737]
DEVICE_MODEL_HEAT = [1123, 1124]
IMPLEMENTED_DEVICE_MODEL = DEVICE_MODEL_HEAT + DEVICE_MODEL_FLOOR 

and it should do the job

Only floor thermostat need to be separated as they call for specific
data update

Try it I've updated my git

Claude Gelinas

Le Sun, 29 Dec 2019 15:58:03 -0800
SylvainGa <notifications@github.com> a écrit:

> Being a developer myself in a previous life, looking at the code, I
> saw what was wrong.
> 
> I replaced 
> DEVICE_MODEL_FLOOR = [737]
> DEVICE_MODEL_HEAT = [1124]
> IMPLEMENTED_DEVICE_MODEL = DEVICE_MODEL_HEAT + DEVICE_MODEL_FLOOR
> 
> for 
> DEVICE_MODEL_FLOOR = [737]
> DEVICE_MODEL_HEAT3000W = [1123]
> DEVICE_MODEL_HEAT4000W = [1124]
> IMPLEMENTED_DEVICE_MODEL = DEVICE_MODEL_HEAT3000W +
> DEVICE_MODEL_HEAT4000W + DEVICE_MODEL_FLOOR
> 
> And my 1123 were discovered in HA :-)
> 
> I'll close this incident and let you decide if you want to add my
> modification or not.
>

**Comment by SylvainGa** [comment]
Works, merci!

**Comment by claudegel** [comment]
Hi,

I've added also the double pole and low voltage thermostat model
number. Hoping they are correct model number :)

For the GT125 I have a component that goes via Neviweb, Sinope Neviweb,
like the one you are using, Sinope Neviweb 130. I also developed a
component that connect directly to the GT125 to manage the devices,
Sinope GT125. No need to use Neviweb.

I'm developping one component for the GT130 direct connection but I need
some update from Sinopé as the development is not finished on there
side.

Thank You

Claude Gelinas

Le Sun, 29 Dec 2019 15:58:03 -0800
SylvainGa <notifications@github.com> a écrit:

> Being a developer myself in a previous life, looking at the code, I
> saw what was wrong.
> 
> I replaced 
> DEVICE_MODEL_FLOOR = [737]
> DEVICE_MODEL_HEAT = [1124]
> IMPLEMENTED_DEVICE_MODEL = DEVICE_MODEL_HEAT + DEVICE_MODEL_FLOOR
> 
> for 
> DEVICE_MODEL_FLOOR = [737]
> DEVICE_MODEL_HEAT3000W = [1123]
> DEVICE_MODEL_HEAT4000W = [1124]
> IMPLEMENTED_DEVICE_MODEL = DEVICE_MODEL_HEAT3000W +
> DEVICE_MODEL_HEAT4000W + DEVICE_MODEL_FLOOR
> 
> And my 1123 were discovered in HA :-)
> 
> I'll close this incident and let you decide if you want to add my
> modification or not.
>
