### ISSUE TITLE
Thermostat TH1123ZB not detected in HA

### ISSUE THREAD

**Issue by AntoineLan** [claudegel/sinope-130#103]
Hello Claude,

I have installed your Naviweb130 in my HA. I see the status of the GT130 as Online and I see the status of all my water leak detectors, so I assume that the connection to Naviweb is working fine. 

However, I don't see any of my six TH1123ZB Thermostats that are connected to Naviweb.

I don't know if I'm missing something.

Thanks,

**Comment by claudegel** [comment]
Hi Antoine, if you speak french we can switch to french or keep it as is .

Did you add in configuration.yaml the debug line for neviweb130 ?

```
logger:
  default: warning
  logs:
    custom_components.neviweb130: debug
```
With this you should see in home-assistant.log the following line which include all your devices. Check for line like this:
`Received gateway data: [{'id': 130090, 'identifier': '14b457fffe7a9472-500b9140000132b7', 'name': 'chauffe eau',.....`
You should see all your thermostats. You will have also one line per device like this:
`[custom_components.neviweb130] Received signature data: {'signature': {'model': 5051, 'modelCfg': 0, 'softBuildCfg'.....`
Then for each devices the following:
`[custom_components.neviweb.climate] Updating neviweb climate Cave (0.533 sec): {'roomSetpointMin': .....`

You should find all your device under dev tools > state. thermostat are listed as climate.neviweb130_climate_name_of_your_thermostats.

If for any reason they don't show up then we will need to check in Neviweb for your thermostats to get the model number. This is found in each device tile, configuration button and info.
Check this and let me know

**Comment by claudegel** [comment]
In the signature data you should see the model number 1123 which is for the thermostat TH1123ZB. If your thermostats are new it is possible that Sinopé change the model number but you should be able to find it in the log or on Neviweb

**Comment by AntoineLan** [comment]
Merci pour votre aide.

En activant le log de neviweb130, j'ai pu voir qu'effectivement les nouveaux modèles de thermostat (je les ai reçus hier) ont un nouveau # de modèle. 
 ...
'name': 'TH1123ZB-G2', 
'family': '1123-G2', 
'signature': {'model': 300, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 8, 'middle': 0, 'major': 0}, 'hardRev': 0}, 
'location$id': 40917,
...

Donc, dans mon cas le modèle est "300". J'ai modifié le fichier climate.py et j'ai ajouté ce nouveau modèle à DEVICE_MODEL_HEAT.

DEVICE_MODEL_HEAT = [300, 1123, 1124, 7373]

Mes thermostats sont maintenant détectés dans HA.

Merci beaucoup pour votre aide.

**Comment by claudegel** [comment]
Une bonne chose. Je vais faire un release pour ajouter le support de ces nouveaux model.
Par contre si vous avez du temps je voudrais valider si Sinopé a inclu de nouvelles fonctions pour ce thermostat deuxième génération.  Quel navigateur utilisez-vous ? Firefox ? Il faudrait valider les attributs qui sont recu de Neviweb pour ajouter ce qui manque s'il y a des différences avec l'ancien model 1123

**Comment by AntoineLan** [comment]
Bonjour,

oui certainement, je peux vous aider. Quelle est la marche à suivre pour valider les attributs?

**Comment by claudegel** [comment]
Si vous etes avec Firefox, juste ouvrir Neviweb et faites F12 pour ouvrir la console de débug au bas de la page.
ensuite ouvrez un thermostat TH1123ZB-G2 et cliquez le bouton de configuration pour afficher les parametres. Dans la console il va apparaitre les parametres comme sur l'image ci-joint
![neviweb_debug](https://user-images.githubusercontent.com/4268938/197064919-717a167b-fe2b-401a-bf2f-190325f6f568.jpg)

**Comment by claudegel** [comment]
Pour Chrome c'est comme suit:

En haut à droite cliquez sur le bouton «Personalisez et contrôlez...»
puis dans le menu sélectionnez Plus d'outils et enfin dans Outils de
développement.

La page se divise en deux. A gauche Neviweb. Sélectionnez votre thermostat
A droite, sélectionnez «Réseau» puis «Tout». Vous allez voir défiler
des lignes «attribut?attributes=...» dans une colonne de gauche et en
cliquant sur l'un d'eux vous aller voir à droite quels sont les
attributs. C'est ce qu'on recherche.

![chrome1](https://user-images.githubusercontent.com/4268938/197065968-1ce44d73-1d2f-4670-a16e-74dc83a9d606.jpg)

**Comment by AntoineLan** [comment]
Voilà! 

{"roomSetpoint":20,"roomTemperatureDisplay":22,"outputPercentDisplay":0,"systemMode":"heat","errorCodeSet1":{"compensationSensor":"ok","airTopSensor":"ok","airBottomSensor":"ok","wireSensor":"ok","currentOverload":"ok","thermalOverload":"ok","lineError":"ok","inductiveMode":false,"endOfLife":false}}

**Comment by AntoineLan** [comment]
Parfois j'obtiens plus d'information.

{"roomSetpoint":20,"roomTemperatureDisplay":22,"outputPercentDisplay":0,"systemMode":"heat","errorCodeSet1":{"compensationSensor":"ok","airTopSensor":"ok","airBottomSensor":"ok","wireSensor":"ok","currentOverload":"ok","thermalOverload":"ok","lineError":"ok","inductiveMode":false,"endOfLife":false},"drStatus":{"drActive":"off","optOut":"off","setpoint":"off","powerAbsolute":"off","powerRelative":"off"},"drSetpoint":{"status":"off","value":null}}

**Comment by AntoineLan** [comment]
Parfait! Si vous avez besoin de quoi ce soit d'autres, faites-moi signe. :)

**Comment by claudegel** [comment]
Vous n'avez pas un TH1124ZB-G2 par hazzardClaude Gelinas agr.Phyto Ressources inc
-------- Message d'origine --------De : AntoineLan ***@***.***> Date : 2022-10-20  5 h 59 p.m.  (GMT-05:00) À : claudegel/sinope-130 ***@***.***> Cc : Claude Gelinas ***@***.***>, Comment ***@***.***> Objet : Re: [claudegel/sinope-130] Thermostat TH1123ZB not detected in HA (Issue #103) 
Parfait! Si vous avez besoin de quoi ce soit d'autres, faites-moi signe. :)

**Comment by AntoineLan** [comment]
Non malheureusement, j'ai seulement acheté le modèle TH1123ZB-G2.

**Comment by claudegel** [comment]
OK on va commencer avec ça. J'ai lancé un appel sur le forum
https://community.home-assistant.io/t/sinope-line-voltage-thermostats/17157
Peut-être que quelqu'un en a un

**Comment by claudegel** [comment]
Il semble manquer le parametre roomTemperature. Pour les autres TH1123ZB c'est ce parametre qui indique la température de la pièce. Pouvez-vous valider quel est le parametre qui affiche la température de la pièce
Aussi dans la console si vous ouvrez la section configuration du thermometre il va apparaitre d'autres attributs. Si vous pouviez me les envoyer ce serait bien. Merci

**Comment by claudegel** [comment]
Quand vous regardez dans home-assistant.log la ligne qui correspond à la mise a jour d'un thermostat
`[custom_components.neviweb130.climate] Updating neviweb130 climate Lavage (1.438 sec): {'roomSetpoint': 15, 'outputPercentDisplay': 0, 'roomTemperature': {'value': 22.93},....`

est-ce que vous voyez le parametre **roomTemperature** si oui est-ce que vous pouvez me copier cette ligne. Je vois que le parametre **roomTemperatureDisplay** donne la valeur arrondie de la température de la pièce alors que **roomTemperature** donne la température mesurée.

**Comment by AntoineLan** [comment]
Sur la page de Neviweb, l'attribut qui correspond à la température dans la pièce est "roomTemperatureDisplay" qui correspond à une valeur arrondie à 0.5 près. Par contre, lorsque je regarde dans le log de HA, l'attribut "roomTemperature" existe.

`Updating neviweb130 climate TH1123ZB-G2 (0.991 sec): {'roomSetpoint': 20, 'outputPercentDisplay': 40, 'roomTemperature': {'value': 20.02}, 'roomSetpointMin': 5, 'roomSetpointMax': 30, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off'}, 'drSetpoint': {'status': 'off', 'value': None}, 'loadConnected': 2599, 'lockKeypad': 'unlocked', 'backlightAdaptive': 'always', 'systemMode': 'heat'}`

Lorsque j'ouvre les configurations dans Neviweb j'obtiens:

`{"roomSetpointMin":5,"roomSetpointMax":30,"backlightAdaptive":"always","temperatureFormat":"celsius","timeFormat":"24h","lockKeypad":"unlocked","loadConnected":1219,"signature":{"model":300,"modelCfg":0,"softBuildCfg":0,"softVersion":{"minor":8,"middle":0,"major":0},"hardRev":0,"protocol":"sinopcom"},"config2ndDisplay":"exteriorTemperature"}`

De plus, j'ai remarqué deux trucs de bizarres ce matin. 

1- Lorsque je change la température à travers l'interface Dashboard de HA, le thermostat se met à jour et tout fonctionne correctement. Par contre, lorsque la commande est envoyée par la Scheduler-card, la valeur de la température désirée change dans HA, mais la requête n'est jamais transmise à Neviweb, puisque le setPoint ne change pas dans Neviweb ni dans le thermostat.

2- Il y a cette erreur dans le log:
```
2022-10-21 10:44:46.901 DEBUG (SyncWorker_3) [custom_components.neviweb130.climate] Updating neviweb130 climate TH1123ZB-G2 (0.829 sec): {'roomSetpoint': 20, 'outputPercentDisplay': 100, 'roomTemperature': {'value': 18.92}, 'roomSetpointMin': 5, 'roomSetpointMax': 30, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off'}, 'drSetpoint': {'status': 'off', 'value': None}, 'loadConnected': 2599, 'lockKeypad': 'unlocked', 'backlightAdaptive': 'always', 'systemMode': 'heat'}
2022-10-21 10:44:47.193 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.neviweb130_climate_th1123zb_g2 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/climate.py", line 906, in update
    self._code_air_sensor = device_error_code["airSensor"]
KeyError: 'airSensor'
```

**Comment by AntoineLan** [comment]
J'ai redémarré le serveur HA. Pour l'instant il n'y a plus de trace d'erreur. Je vais voir si celle-ci apparaît seulement après un certain temps.

**Comment by AntoineLan** [comment]
Bon l'erreur est revenue, j'ai décommenté la ligne 902 pour voir le contenu de `device_error_code` et j'obtiens le log suivant:

`WARNING (SyncWorker_0) [custom_components.neviweb130.climate] Updating error code: {'compensationSensor': 'ok', 'airTopSensor': 'ok', 'airBottomSensor': 'ok', 'wireSensor': 'ok', 'currentOverload': 'ok', 'thermalOverload': 'ok', 'lineError': 'ok', 'inductiveMode': False, 'endOfLife': False}`

Ça te parlera peut-être plus à toi, mais l'erreur vient du fait que l'attribut "airSensor" n'existe plus, tu l'as peut-être oublié et devrait être remplacé par "airTopSensor" et "airBottomSensor".

**Comment by claudegel** [comment]
self._code_air_sensor = device_error_code["airSensor"] cette option n'existe pas pour votre thermostat. à la place c'est ```
self._air_top = device_error_code["airTopSensor"]
self._air_bottom = device_error_code["airBottomSensor"]
```
C,est parametres vont apparaitre avec le release. Ce soir je vais mettre a jour la branche 2nd-gen qui va inclure tous les spécifications pour les G2
Je n'ai pas ajouté le modele 300 avec les autres. Ca va plus tôt être ceci
```
DEVICE_MODEL_HEAT = [1123, 1124, 7373]
DEVICE_MODEL_HEAT_G2 = [300]
```
J'ai presque fini. il me manquait juste les info pour roomTemperature qui est la valeur lue par le sensor du thermostat alors que roomTemperatureDisplay est la valeur arrondie par le thermostat pour l'affichage.

On avance

**Comment by claudegel** [comment]
Je recherche aussi le modèle pour le TH1124ZB-G2 mais au pire je ferai un autre release.

**Comment by claudegel** [comment]
le airSensor c'est pour les vieux TH1123ZB alors que c'est remplacé par airTopSensor et airBottomSensor. Ma nouvelle version va corriger cela

**Comment by AntoineLan** [comment]
Parfait, juste vous mentionner qu'après avoir changé `airSensor`, j'ai obtenu la même erreur pour l'attribut `referenceSensor`. Du même coup, j'ai aussi enlevé `loadError` puisqu'il n'apparaissait pas dans la liste de `device_error_code`.

Par contre, j'ai essayé de voir ce qui causait le déclenchement de cette partie du code et j'ai trouvé que `start - self._energy_stat_time > 1800` devenait "True". Je ne sais pas pourquoi, mais à partir de ce moment-là, je ne reçois plus d'update de mes thermostats. La seule solution est de redémarrer le serveur HA.

**Comment by claudegel** [comment]
OK j'ai corrigé ca aussi. Je vais mettre a jour ma branche ce soir pour que vous puissiez la tester. Il va y voir des changements dans climate.py et probablement dans const.py. Mais pour l'instant attendez car j'ai pas tout mi dedans

**Comment by claudegel** [comment]
J'ai mi a jour la branche 2nd-gen. Il y a des changements dans `__init__.py`, climate.py et const.py
Svp testé cela et dites moi si il y a des bug qui sortent

**Comment by Guyohms** [comment]
Je crois que les TH1123ZB-G2 n'ont pas de RSSI, car on ne voit pas la force du signal sur Neviweb et j'obtient l'erreur :


```
2022-10-23 08:34:53.236 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/climate.py", line 805, in update
self._rssi = device_data[ATTR_RSSI]
KeyError: 'rssi'
```


Sur Neviweb:
![image](https://user-images.githubusercontent.com/44414660/197392755-854fc12a-3ca2-4c96-b7ed-8597c9cb4551.png)
VS
![image](https://user-images.githubusercontent.com/44414660/197392778-40ae0e62-e968-4a8f-bfd1-929dd392d15b.png)

**Comment by Guyohms** [comment]
Je viens de tester en ajoutant : 
```
                    if not self._is_gen2:
                        self._rssi = device_data[ATTR_RSSI]
```
dans `climate.py` line 805 et ça fonctionne.

**Comment by claudegel** [comment]
J'ai plutôt ajouté
```
if ATTR_RSSI in device_data:
         self._rssi = device_data[ATTR_RSSI]
```
Comme ca si Sinopé ajoute l'attribut ca va s'activer automatiquement sans necessiter de mise a jour. Pour les attributs des thermostats G2 ca va donner rssi: None. Mais si Sinopé l'ajoute on aura la force du signal.

Si ca fonctionne bien je vais faire une nouvelle version pour que les autres en profitent.

Merci,

**Comment by claudegel** [comment]
Si vous avez d'autre problème vouz pourrez réouvrir cette issue

Merci de votre aide
