### ISSUE TITLE
TH1400ZB erreur de mise à jours

### ISSUE THREAD

**Issue by faucherc** [claudegel/sinope-130#108]
Depuis que j'ai ajouté 2 thermostat TH1400ZB à mon réseau, j'ai un erreur répétitive.  L'erreur apparait environ 30 minutes après un redémarrage de HA et par la suite, ce produit à chaque 5 minutes (mon scan_interval est à 300).

J'utilise la version 1.7.2.  J'ai décommenté la ligne 920 du fichier climate.py pour avoir le contenu de la variable device_error_code.

Voici ce que j'ai dans les logs:
2022-11-02 21:46:27.281 WARNING (SyncWorker_1) [custom_components.neviweb130.climate] Updating error code: {'compensationSensor': 'ok', 'airSensor': 'ok', 'floorSensor': 'ok', 'thermalOverload': 'ok'}
2022-11-02 21:46:27.283 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.neviweb130_climate_th1400zb fails
Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 515, in async_update_ha_state
await self.async_device_update()
File "/usr/lib/python3.10/site-packages/homeassistant/helpers/entity.py", line 710, in async_device_update
raise exc
File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/climate.py", line 929, in update
self._code_wire_sensor = device_error_code["wireSensor"]
KeyError: 'wireSensor'

**Comment by claudegel** [comment]
Bonjour,
merci de me rapporter cette erreur. Pour l'instant juste commenter les
lignes 929, 930, 931 et possiblement 939 et 940 de climate.py
Il semble que l'attribut wireSensor est absent ainsi que plusieurs autres.
demain je vais regarder comment contourner ce problème pour votre thermostat.

**Comment by faucherc** [comment]
Bonjour Claude,  Merci pour votre réponse rapide!

Après vous avoir écris, j'ai essayé une modification.  Depuis, je n'ai plus d'erreur et les states de mes thermostats semble parfait. A vous de voir si cela est suffisant et correct.
Ligne 925:        if self._is_floor and not self._is_wifi:
                            self._code_floor_sensor = device_error_code["floorSensor"]
                            self._code_gfcibase = device_error_code["gfciBase"]
                        # Debut ajout
                        elif self._is_low_voltage:
                            self._code_air_sensor = device_error_code["airSensor"]
                            self._code_floor_sensor = device_error_code["floorSensor"]
                        # Fin ajout
                        else:
                            self._code_wire_sensor = device_error_code["wireSensor"]

**Comment by claudegel** [comment]
Ok I set a new branch TH1400-support to catch error code and also to add them in attributes for your valve.
Please test. You only need to copy climate.py
https://github.com/claudegel/sinope-130/tree/TH1400-support

**Comment by faucherc** [comment]
Thank you Claude!  I just install it.  For now, it's seems good.  I will keep you in touch.

**Comment by claudegel** [comment]
Did you check if the new attributes show up in your TH1400ZB list attributes?
I'm finishing an update for the sedna valve flow sensor then I'll push a new release.

**Comment by faucherc** [comment]
Yes.  The attributes is present.

pump_protection_status: 'off'
pump_protection_duration: null
pump_protection_frequency: null
status compensation sensor: null
status thermal overload: null
status air sensor: null
status floor sensor: null
status reference sensor: null
status load sensor: null
heat_level: 0
temp_display_value: 17
second_display: default
keypad: unlocked

**Comment by claudegel** [comment]
Great they will populate after 30 minutes

**Comment by faucherc** [comment]
Yes. The new one has been populated.  But the 2 last one hasn't.  It's normal?

pump_protection_status: 'off'
pump_protection_duration: null
pump_protection_frequency: null
status compensation sensor: ok
status thermal overload: ok
status air sensor: ok
status floor sensor: ok
status reference sensor: null
status load sensor: null
heat_level: 0
temp_display_value: 17
second_display: default
keypad: unlocked

**Comment by claudegel** [comment]
status reference sensor: null
status load sensor: null
are not populated for your TH1400ZB I'll remove them for the TH1400ZB

**Comment by claudegel** [comment]
Try climate.py the two status should be gone

**Comment by faucherc** [comment]
I confirm. They are gone!

**Comment by claudegel** [comment]
OK I'll finish a little cleaning in my code and will publish a release this weekend

**Comment by faucherc** [comment]
Great! Thank you very much for your wonderfull works and support!

**Comment by claudegel** [comment]
Thank you for your help in testing the changes. I'll push a new release now
