### ISSUE TITLE
Add Support for FS4220 Flow Sensors

### ISSUE THREAD

**Issue by mtwo** [claudegel/sinope-130#109]
Hi! I'm using a Sedna WiFi water valve, which is directly connected to a FS4220 / FS4221 flow sensor and connected via Zigbee to many water sensors. This was originally configured by the Neviweb app, and I've used this repository to view and monitor these devices in Home Assistant.

Home Assistant just added water usage tracking to the energy dashboard. Would it be possible to capture water consumption information from the flow sensor attached to my Sedna valve so that it can then be displayed on the energy dashboard?

Also, thank you for developing this integration. It's really helpful and it prompted me to start using Home Assistant!

**Comment by claudegel** [comment]
Yes I think it could be easy . I'll need some data from you in order to add what we need in neviweb130. First in Neviweb do you see the flow sensor as a separate device or it is just a parameter in the sedna valve. Also do you see flow meetering in Neviweb

**Comment by mtwo** [comment]
It shows up as a parameter of the valve (along with the flow graphs), and not as a separate device:

![image](https://user-images.githubusercontent.com/1144235/199852253-9a7a32b0-0c1a-4c21-bd6d-4eb1ed927732.png)

![image](https://user-images.githubusercontent.com/1144235/199852225-7d44a1a8-3a58-4a61-8e28-b6bc5a59d6b2.png)

**Comment by claudegel** [comment]
OK it is possible to retreive the data from the graph. What browser are you using ? Firefox or Chrome. We need to open the dev tool consol from your browser. In Firefox you just hit F12 and the console will open at the bottom of the screen. Check myred mark. You need to select the consol and watch for a line GET https://neviweb.com/api...
The line we are looking for will appear when you open the graph. It should be something like this:
GEThttps://neviweb.com/api/device/69457/statistics/48hours The number 69457 in your case is the number of your sensor or your valve. See my picture. Once we know how to call the statistic we will be able to load them in HA
![neviweb_debug](https://user-images.githubusercontent.com/4268938/199856581-26a88941-a6f3-4f22-a679-8a3cfc562ef7.jpg)

**Comment by claudegel** [comment]
You should be able to get statistic for 48 hours period, 30 days period and 2 years period

**Comment by mtwo** [comment]
Trying now!

**Comment by mtwo** [comment]
Here are some details about the requests:

- https://neviweb.com/api/device/284098/energy/hourly
- https://neviweb.com/api/device/284098/energy/daily
- https://neviweb.com/api/device/284098/energy/monthly

Hourly response:
`{"device$id":284098,"unit":"milliliters","history":[{"period":0,"periodQuality":0,"counter":79451017,"counterDate":"2022-11-03T18:05:02-07:00","date":"2022-11-03T18:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79451017,"counterDate":"2022-11-03T17:05:02-07:00","date":"2022-11-03T17:00:00-07:00"},{"period":7686,"periodQuality":60,"counter":79443331,"counterDate":"2022-11-03T16:04:58-07:00","date":"2022-11-03T16:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79443331,"counterDate":"2022-11-03T15:05:04-07:00","date":"2022-11-03T15:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79443331,"counterDate":"2022-11-03T14:04:57-07:00","date":"2022-11-03T14:00:00-07:00"},{"period":0,"periodQuality":0,"counter":79574340,"counterDate":"2022-11-03T13:04:58-07:00","date":"2022-11-03T13:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79574340,"counterDate":"2022-11-03T12:04:57-07:00","date":"2022-11-03T12:00:00-07:00"},{"period":11065,"periodQuality":60,"counter":79563275,"counterDate":"2022-11-03T11:04:55-07:00","date":"2022-11-03T11:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79563275,"counterDate":"2022-11-03T10:04:59-07:00","date":"2022-11-03T10:00:00-07:00"},{"period":131697,"periodQuality":60,"counter":79431578,"counterDate":"2022-11-03T09:04:58-07:00","date":"2022-11-03T09:00:00-07:00"},{"period":97209,"periodQuality":60,"counter":79334369,"counterDate":"2022-11-03T08:04:59-07:00","date":"2022-11-03T08:00:00-07:00"},{"period":7133,"periodQuality":60,"counter":79327236,"counterDate":"2022-11-03T07:04:58-07:00","date":"2022-11-03T07:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79327236,"counterDate":"2022-11-03T06:05:01-07:00","date":"2022-11-03T06:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79327236,"counterDate":"2022-11-03T05:05:05-07:00","date":"2022-11-03T05:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79327236,"counterDate":"2022-11-03T04:04:57-07:00","date":"2022-11-03T04:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79327236,"counterDate":"2022-11-03T03:04:59-07:00","date":"2022-11-03T03:00:00-07:00"},{"period":0,"periodQuality":0,"counter":79393940,"counterDate":"2022-11-03T02:04:58-07:00","date":"2022-11-03T02:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79393940,"counterDate":"2022-11-03T01:04:53-07:00","date":"2022-11-03T01:00:00-07:00"},{"period":54047,"periodQuality":60,"counter":79339893,"counterDate":"2022-11-03T00:04:56-07:00","date":"2022-11-03T00:00:00-07:00"},{"period":76,"periodQuality":60,"counter":79339817,"counterDate":"2022-11-02T23:04:57-07:00","date":"2022-11-02T23:00:00-07:00"},{"period":12581,"periodQuality":60,"counter":79327236,"counterDate":"2022-11-02T22:04:59-07:00","date":"2022-11-02T22:00:00-07:00"},{"period":9662,"periodQuality":60,"counter":79317574,"counterDate":"2022-11-02T21:04:57-07:00","date":"2022-11-02T21:00:00-07:00"},{"period":3561,"periodQuality":60,"counter":79314013,"counterDate":"2022-11-02T20:04:55-07:00","date":"2022-11-02T20:00:00-07:00"},{"period":1827,"periodQuality":60,"counter":79312186,"counterDate":"2022-11-02T19:05:00-07:00","date":"2022-11-02T19:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79312186,"counterDate":"2022-11-02T18:04:57-07:00","date":"2022-11-02T18:00:00-07:00"},{"period":7508,"periodQuality":60,"counter":79304678,"counterDate":"2022-11-02T17:05:00-07:00","date":"2022-11-02T17:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79304678,"counterDate":"2022-11-02T16:04:55-07:00","date":"2022-11-02T16:00:00-07:00"},{"period":27,"periodQuality":60,"counter":79304651,"counterDate":"2022-11-02T15:05:01-07:00","date":"2022-11-02T15:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79304651,"counterDate":"2022-11-02T14:04:59-07:00","date":"2022-11-02T14:00:00-07:00"},{"period":7413,"periodQuality":60,"counter":79297238,"counterDate":"2022-11-02T13:04:54-07:00","date":"2022-11-02T13:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79297238,"counterDate":"2022-11-02T12:04:54-07:00","date":"2022-11-02T12:00:00-07:00"},{"period":7557,"periodQuality":60,"counter":79289681,"counterDate":"2022-11-02T11:04:54-07:00","date":"2022-11-02T11:00:00-07:00"},{"period":133,"periodQuality":60,"counter":79289548,"counterDate":"2022-11-02T10:04:54-07:00","date":"2022-11-02T10:00:00-07:00"},{"period":0,"periodQuality":60,"counter":79289548,"counterDate":"2022-11-02T09:04:58-07:00","date":"2022-11-02T09:00:00-07:00"},{"period":121061,"periodQuality":60,"counter":79168487,"counterDate":"2022-11-02T08:04:57-07:00","date":"2022-11-02T08:00:00-07:00"},{"period":0,"periodQuality":0,"counter":78965897,"counterDate":"2022-11-02T06:04:53-07:00","date":"2022-11-02T06:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78965897,"counterDate":"2022-11-02T05:05:04-07:00","date":"2022-11-02T05:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78965897,"counterDate":"2022-11-02T04:04:59-07:00","date":"2022-11-02T04:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78965897,"counterDate":"2022-11-02T03:04:56-07:00","date":"2022-11-02T03:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78965897,"counterDate":"2022-11-02T02:04:55-07:00","date":"2022-11-02T02:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78965897,"counterDate":"2022-11-02T01:04:50-07:00","date":"2022-11-02T01:00:00-07:00"},{"period":33027,"periodQuality":60,"counter":78932870,"counterDate":"2022-11-02T00:04:52-07:00","date":"2022-11-02T00:00:00-07:00"},{"period":7262,"periodQuality":60,"counter":78925608,"counterDate":"2022-11-01T23:04:54-07:00","date":"2022-11-01T23:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78925608,"counterDate":"2022-11-01T22:04:56-07:00","date":"2022-11-01T22:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78925608,"counterDate":"2022-11-01T21:04:59-07:00","date":"2022-11-01T21:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78925608,"counterDate":"2022-11-01T20:04:58-07:00","date":"2022-11-01T20:00:00-07:00"},{"period":0,"periodQuality":60,"counter":78925608,"counterDate":"2022-11-01T19:05:01-07:00","date":"2022-11-01T19:00:00-07:00"},{"period":1910,"periodQuality":60,"counter":78923698,"counterDate":"2022-11-01T18:04:59-07:00","date":"2022-11-01T18:00:00-07:00"}]}`

Daily response:
`{"device$id":284098,"unit":"milliliters","history":[{"period":308837,"periodQuality":960,"counter":79339893,"counterDate":"2022-11-03T00:04:56-07:00","date":"2022-11-03T00:00:00-07:00"},{"period":407023,"periodQuality":1440,"counter":78932870,"counterDate":"2022-11-02T00:04:52-07:00","date":"2022-11-02T00:00:00-07:00"},{"period":325127,"periodQuality":1440,"counter":78607743,"counterDate":"2022-11-01T00:04:59-07:00","date":"2022-11-01T00:00:00-07:00"},{"period":354252,"periodQuality":1440,"counter":78253491,"counterDate":"2022-10-31T00:04:55-07:00","date":"2022-10-31T00:00:00-07:00"},{"period":280193,"periodQuality":1440,"counter":77973298,"counterDate":"2022-10-30T00:05:00-07:00","date":"2022-10-30T00:00:00-07:00"},{"period":414652,"periodQuality":1440,"counter":77558646,"counterDate":"2022-10-29T00:04:56-07:00","date":"2022-10-29T00:00:00-07:00"},{"period":443634,"periodQuality":1440,"counter":77115012,"counterDate":"2022-10-28T00:05:00-07:00","date":"2022-10-28T00:00:00-07:00"},{"period":91801,"periodQuality":1440,"counter":77023211,"counterDate":"2022-10-27T00:04:58-07:00","date":"2022-10-27T00:00:00-07:00"},{"period":277052,"periodQuality":1440,"counter":76746159,"counterDate":"2022-10-26T00:04:57-07:00","date":"2022-10-26T00:00:00-07:00"},{"period":212513,"periodQuality":1440,"counter":76533646,"counterDate":"2022-10-25T00:05:00-07:00","date":"2022-10-25T00:00:00-07:00"},{"period":394463,"periodQuality":1440,"counter":76139183,"counterDate":"2022-10-24T00:04:56-07:00","date":"2022-10-24T00:00:00-07:00"},{"period":656268,"periodQuality":1440,"counter":75482915,"counterDate":"2022-10-23T00:04:54-07:00","date":"2022-10-23T00:00:00-07:00"},{"period":657714,"periodQuality":1440,"counter":74825201,"counterDate":"2022-10-22T00:05:01-07:00","date":"2022-10-22T00:00:00-07:00"},{"period":596313,"periodQuality":1440,"counter":74228888,"counterDate":"2022-10-21T00:04:55-07:00","date":"2022-10-21T00:00:00-07:00"},{"period":412972,"periodQuality":1440,"counter":73815916,"counterDate":"2022-10-20T00:04:58-07:00","date":"2022-10-20T00:00:00-07:00"},{"period":342922,"periodQuality":1440,"counter":73472994,"counterDate":"2022-10-19T00:04:53-07:00","date":"2022-10-19T00:00:00-07:00"},{"period":444295,"periodQuality":1380,"counter":73117928,"counterDate":"2022-10-18T00:04:53-07:00","date":"2022-10-18T00:00:00-07:00"},{"period":186851,"periodQuality":1440,"counter":72931077,"counterDate":"2022-10-17T00:04:56-07:00","date":"2022-10-17T00:00:00-07:00"},{"period":458111,"periodQuality":1440,"counter":72472966,"counterDate":"2022-10-16T00:05:01-07:00","date":"2022-10-16T00:00:00-07:00"},{"period":56,"periodQuality":1440,"counter":72472910,"counterDate":"2022-10-15T00:05:00-07:00","date":"2022-10-15T00:00:00-07:00"},{"period":529959,"periodQuality":1380,"counter":72012848,"counterDate":"2022-10-14T00:04:55-07:00","date":"2022-10-14T00:00:00-07:00"},{"period":460314,"periodQuality":1380,"counter":71571395,"counterDate":"2022-10-13T00:05:01-07:00","date":"2022-10-13T00:00:00-07:00"},{"period":469744,"periodQuality":1440,"counter":71101651,"counterDate":"2022-10-12T00:04:53-07:00","date":"2022-10-12T00:00:00-07:00"},{"period":464811,"periodQuality":1440,"counter":70636840,"counterDate":"2022-10-11T00:04:57-07:00","date":"2022-10-11T00:00:00-07:00"},{"period":115991,"periodQuality":1440,"counter":70520849,"counterDate":"2022-10-10T00:04:51-07:00","date":"2022-10-10T00:00:00-07:00"},{"period":81,"periodQuality":1440,"counter":70520768,"counterDate":"2022-10-09T00:04:58-07:00","date":"2022-10-09T00:00:00-07:00"},{"period":81,"periodQuality":1440,"counter":70520687,"counterDate":"2022-10-08T00:04:56-07:00","date":"2022-10-08T00:00:00-07:00"},{"period":54,"periodQuality":1440,"counter":70520633,"counterDate":"2022-10-07T00:04:55-07:00","date":"2022-10-07T00:00:00-07:00"},{"period":371894,"periodQuality":1440,"counter":70148739,"counterDate":"2022-10-06T00:04:51-07:00","date":"2022-10-06T00:00:00-07:00"},{"period":364243,"periodQuality":1440,"counter":69784496,"counterDate":"2022-10-05T00:04:52-07:00","date":"2022-10-05T00:00:00-07:00"}]}`

Monthly response:
`{"device$id":284098,"unit":"milliliters","history":[{"period":1040987,"periodQuality":3840,"counter":78607743,"counterDate":"2022-11-01T00:04:59-07:00","date":"2022-11-01T00:00:00-07:00"},{"period":10711021,"periodQuality":44460,"counter":68074709,"counterDate":"2022-10-01T00:04:49-07:00","date":"2022-10-01T00:00:00-07:00"},{"period":6940647,"periodQuality":43200,"counter":61134062,"counterDate":"2022-09-01T00:05:03-07:00","date":"2022-09-01T00:00:00-07:00"},{"period":10196493,"periodQuality":44640,"counter":50937569,"counterDate":"2022-08-01T00:05:07-07:00","date":"2022-08-01T00:00:00-07:00"},{"period":16662718,"periodQuality":44460,"counter":34857644,"counterDate":"2022-07-01T00:04:57-07:00","date":"2022-07-01T00:00:00-07:00"},{"period":17475330,"periodQuality":43080,"counter":17526994,"counterDate":"2022-06-01T00:05:11-07:00","date":"2022-06-01T00:00:00-07:00"},{"period":14043401,"periodQuality":44580,"counter":3509700,"counterDate":"2022-05-01T00:04:58-07:00","date":"2022-05-01T00:00:00-07:00"},{"period":3868482,"periodQuality":12780,"counter":0,"counterDate":"2022-04-22T00:04:50-07:00","date":"2022-04-01T00:00:00-07:00"}]}`

**Comment by claudegel** [comment]
Great with that data I'll be able to setup counter for flow meter

**Comment by claudegel** [comment]
I've created a branch TH1400-support and added the code for your flow sensor.  Please go to the branch below and copy switch.py file to your HA custom_component/neviweb130/ dir

https://github.com/claudegel/sinope-130/tree/TH1400-support/custom_components/neviweb130

you should see some data in the log or in your valve attribute.

**Comment by mtwo** [comment]
Will test this today

**Comment by mtwo** [comment]
Here's what's coming through now:

Hourly flow count
79,754.25
Daily flow count
79,482.05
Monthly flow count
78,607.74
Hourly flow
87.92
Daily flow
360.12
Monthly flow
1,432.14

I've confirmed that these values match what I see on neviweb.com!

I attempted to add these values to the energy / water usage dashboard, and it looks like they need to be in a slightly different format to be usable. I clicked a help link within Home Assistant and it (amusingly) said "Open an issue with the author of the integration and link them to https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics.".

**Comment by claudegel** [comment]
I need to find a way to differentiate the first gen and second gen valve as the first one do not have flow sensor. If you see some data in your attribute or in the log

**Comment by claudegel** [comment]
The value sent by Neviweb are in milliliters and I thing that the energy module is looking for L, gal, m³, ft³
Did you create a sensor to read the values from your valve and translate it to what energy is looking for.
```
template:
  - sensor:
      - name: "water flow"
        unit_of_measurement: "L"
        device_class: water
        state_class: total_increasing
        state: >-
          {{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") | float / 1000 }}
```
if we need to send L instead of ml, I can do the translation directly in neviweb130

**Comment by claudegel** [comment]
I've converted flow sensor values from ml to L directly in the attributes. Please check switch.py sould be better for energy module

**Comment by mtwo** [comment]
Just updated switch.py and I'll provide results in a few minutes once it has time to capture data.

Regarding the valve data, this request might help:

GET https://neviweb.com/api/device/284098/attribute?attributes=motorPosition,motorTargetPosition,temperatureAlarmStatus,batteryStatus,valveInfo,batteryVoltage,stm8Error,flowMeterMeasurementConfig,waterLeakStatus

`{"motorPosition":100,"motorTargetPosition":100,"temperatureAlarmStatus":"ok","batteryStatus":"ok","valveInfo":{"status":"opened","cause":"remote","identifier":"0000000000000002"},"batteryVoltage":5.8,"stm8Error":{"motorJam":false,"motorPosition":false,"motorLimit":false},"flowMeterMeasurementConfig":{"multiplier":9887,"offset":87372,"divisor":1},"waterLeakStatus":"ok"}`

**Comment by mtwo** [comment]
Update: using the switch.py from both of today's commits caused my water valve entity to disappear, so I reverted to yesterday's commit to restore it. Looking through the logs now.

**Comment by claudegel** [comment]
I just finished updating switch.py to add support for all valve model with flow sensor. But your previous message allow me to add some more attributes...

**Comment by mtwo** [comment]
Hmm, after reverting to yesterday evening's commits, the entity for the valve re-appears but the flow values aren't populating. I'm going to let this sit for ~10 minutes to see if these values get populated.

**Comment by claudegel** [comment]
I've added all missing attributes. If your flow data don't appear look in your log. It is possible that I've made a mistake in the conversion from ml to L.
Pick the last switch.py so we speek with the same code

**Comment by mtwo** [comment]
The older release populated the values after a few minutes, testing the latest release again now

**Comment by mtwo** [comment]
Darn, it failed again, here are the logs:

`2022-11-04 20:53:29.349 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform neviweb130
File "/config/custom_components/neviweb130/switch.py", line 761, in extra_state_attributes
File "/config/custom_components/neviweb130/switch.py", line 369, in ml_to_L
2022-11-04 20:53:29.392 ERROR (MainThread) [homeassistant.components.switch] Error while setting up neviweb130 platform for switch
File "/config/custom_components/neviweb130/switch.py", line 761, in extra_state_attributes
File "/config/custom_components/neviweb130/switch.py", line 369, in ml_to_L`

I'm attempting to debug now.

**Comment by mtwo** [comment]
No luck debugging it. Are the logs that I provided sufficient, or is there more that I can provide?

**Comment by mtwo** [comment]
After reverting to yesterday's release I also tested the configuration for the "water flow" sensor to populate water usage on the energy dashboard. I believe that the sensor configuration is correctly formatted, however I noticed the flow meter attribute values from the Neviweb integration take about 10 minutes to populate after rebooting Home Assistant. This causes the templated sensor to error out during startup:

`2022-11-04 22:59:41.343 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") | float / 1000 }}")
ValueError: Template error: float got invalid input 'None' when rendering template '{{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") | float / 1000 }}' but no default was specified
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'None' when rendering template '{{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") | float / 1000 }}' but no default was specified
2022-11-04 22:59:41.356 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'None' when rendering template '{{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") | float / 1000 }}' but no default was specified') while processing template 'Template("{{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") | float / 1000 }}")' for attribute '_attr_native_value' in entity 'sensor.arbutus_water_flow'`

**Comment by claudegel** [comment]
Ok I just fix it. Please remove  | float / 1000  in your sensor because when starting HA the value for flow sensor are None and it will cause an error. Anyway now the value will be reported as None before the first call to Neviweb and after to values converted to liters

**Comment by mtwo** [comment]
Updated switch.py to your latest version and removed « | float / 1000 » from the sensor. Testing now.

**Comment by mtwo** [comment]
Thanks! The attribute values are working once again, and I noticed that they're now in cubic meters. Thanks for adding this!

The statistic that makes these values available to the new energy dashboard still isn't working however. It's not generating any errors in the logs, but it's not generating any values either.

![image](https://user-images.githubusercontent.com/1144235/200138024-447cadb9-7e14-412a-95bb-96464ecd3900.png)

**Comment by claudegel** [comment]
I think you should point energy to your sensor, not the valve.
Also if Neviweb is sending flow meter values in milliliters than the vales / 1000 should be in liters not cubic meters

**Comment by claudegel** [comment]
What are the values reported by your sensor.arbutus_water_flow. Should be in liters

**Comment by mtwo** [comment]
Neviweb.com reports my flows as:
Past hour: 54.63L
Yesterday: 425.9L
November: 2037.11L

Here are the attribute values:

Valve status
opened
Temperature alert
ok
Battery level
87
Battery voltage
5.8
Battery status
ok
Valve closure source
—
Battery alert
true
Motor target position
100
Water leak status
—
Valve cause
remote
Valve info ID
0000000000000002
Alert motor jam
false
Alert motor position
false
Alert motor limit
false
Flow meter multiplier
9,887
Flow meter offset
87,372
Flow meter divisor
1
Hourly flow count
80.3
Daily flow count
79.91
Monthly flow count
78.61
Hourly flow
0.05
Daily flow
0.44
Monthly flow
1.94
ID
284,098
Sku
VA4220WF

**Comment by claudegel** [comment]
Ha I miss that. In switch.py the value are already divided by 1000 and I did another division so now the value are in square meeter
I'll remove the second division. We don't need it and we will have the value in litters. Test switch.py I will update the new version without the /1000. Sorry

**Comment by mtwo** [comment]
No need to apologize, thank you for putting so much effort into this!

**Comment by mtwo** [comment]
I'm curious, is there a reason why the flow attributes take about ~20 minutes to appear after restarting Home Assistant? Are they being queried less frequently and only being updated when the Neviweb APIs offer new data?

**Comment by claudegel** [comment]
I've set that delay because if you start everything after restarting HA, then if you have a lot of devices on the GT130 it will overload Neviweb and Sinopé don't like this. Also as the data is updated once per hour it is not critical.
I'll check if I can start polling flow data let say 5 minutes after restart then poll every 30 minutes after. It should be better.

**Comment by mtwo** [comment]
That would be perfect!

**Comment by mtwo** [comment]
Also FYI, you will likely want to keep the measurements in cubic meters: https://community.home-assistant.io/t/wth-do-we-have-energy-dashboard-and-no-water-dashboard/467168/45

**Comment by claudegel** [comment]
So I should keep the second division  by 1000 ?

**Comment by claudegel** [comment]
Ok I've reverted to keep the second /1000 to have "m³"
I also change data polling start to 5 minutes. As you already have a scan_interval: 360, that will give data polling to start at the next polling after HA restart.
I think you should change your sensor setup to:
```
template:
  - sensor:
      - name: "Arbutus Water Flow"
        unit_of_measurement: "m³"
        device_class: water
        state_class: total_increasing
        state: >-
          {{ state_attr("switch.neviweb130_water_valve","hourly_flow_count") }}
```

**Comment by mtwo** [comment]
Yep! One question, should the template sensor be referencing the hourly_flow_count attribute, or hourly_flow? I'd assumed that it would be hourly_flow

**Comment by mtwo** [comment]
Confirmed that this is working in the energy monitor by referencing hourly_flow! Thank you so much, this is fantastic! I only started using Home Assistant a few months ago, and contributions like this are what make the community excellent!

One question: I think that the way this works is that the hourly_flow attribute is presenting the hourly consumption each hour, which is then copied into the templated sensor. This works as long as Home Assistant and Neviweb can communicate at least once an hour, which they usually can. Given that Neviweb captures the hourly history for 48 hours, it might be more robust to expose this history so that Home Assistant can backfill its data if there's an interruption?

Anyways, just a thought. I don't think that backfilling the history is critical, and the same limitation would exist with a dedicated flow meter connected directly to Home Assistant.

**Comment by claudegel** [comment]
Great if you use the hourly_flow attribute I think that you need to set state_class: total instead of total_increasing
When we poll the data we get 24 hours but I need to check how the energy module store and retreive its data. Don't know if it is possible to backfill the data but normally HA must stay ON all the time.
We poll the data every 30 minutes and Neviweb publish new data once per hour so if we miss one we will catch with the next poll I think. If you use hourly_flow_count you won't loos anything because the count keep growing. If you use hourly_flow you can loose some data if HA stop for any reason.

So if it is ok now I'll prepare a new release tomorrow. Many people will be happy to get flow monitor

**Comment by mtwo** [comment]
Thanks!
