### ISSUE TITLE
Cette entité n'est plus fournie par l'intégration neviweb130

### ISSUE THREAD

**Issue by JordanM1738** [claudegel/sinope-130#114]
Bonjour,
J'ai une valve d'eau VA4200WZ quand je force l'utilisation de la version 1.7.2 ou avant elle fonctionne parfaitement.
Lorsque je met à jour Sinope Neviweb130 depuis HACS vers une version >1.7.2 elle ne fonctionne plus.
Elle est bien présente dans Neviweb mais dans Home assistant j'ai le message suivant:

Cette entité n'est plus fournie par l'intégration neviweb130. Si l'entité n'est plus utilisée, supprimez-la depuis les paramètres.

<img width="581" alt="Capture d’écran, le 2022-11-17 à 18 56 27" src="https://user-images.githubusercontent.com/85708647/202587068-2053128d-5c8d-4c26-9e07-47e0ab15f96b.png">

**Comment by claudegel** [comment]
Bonjour, merci de rapporter ce problème. Premièrement pouvez-vous valider le numéro de model de votre valve.
Dans Neviweb en regardant dans la configuration de la valve dans la section info ou bien dans les log de HA la ligne contenant
[custom_components.neviweb130] Received gateway data: 
Votre valve devrait s'y retrouver avec le numéro de model

**Comment by JordanM1738** [comment]
Je ne trouve pas les logs de HA  mais dans neviweb j'ai les infos suivates:

- model 3150
- version logiciel 1.1.0
- version matériel 1

**Comment by claudegel** [comment]
Les log des HA sont dans config/homeassistant.log Pour avoir des log sur neviweb130 il faut ajouter dans configuration.yaml
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
Vous avez le bon numéro de model il faut donc chercher autre chose. en commençant par les log

**Comment by claudegel** [comment]
Les log sont au même endroit où vous avez édité le fichier configuration.yaml pour y mettre les parametres de neviweb130

**Comment by JordanM1738** [comment]
Dans les logs j'ai trouvé ceci
`2022-11-17 20:52:10.339 DEBUG (SyncWorker_4) [custom_components.neviweb130.switch] Updating neviweb130 switch Sedna (0.49 sec): {'motorPosition': 100, 'motorTargetPosition': 100, 'temperatureAlarmStatus': 'ok', 'batteryVoltage': 5.6, 'batteryStatus': 'ok', 'valveClosureSource': {'source': 'user'}, 'stm8Error': {'motorJam': False}, 'alertLowBatt': False}
2022-11-17 20:52:10.485 ERROR (MainThread) [homeassistant.components.switch] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
await task
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/switch.py", line 592, in update
self._stm8Error_motorLimit = device_data[ATTR_STM8_ERROR]["motorLimit"]
KeyError: 'motorLimit'`

**Comment by claudegel** [comment]
Ok je vais faire une patch. un instant...
C'est bien les log de la version 1.7.7 ?

**Comment by JordanM1738** [comment]
Oui je suis bien en 1.7.7

**Comment by claudegel** [comment]
ok allez sur la branch wifi
https://github.com/claudegel/sinope-130/tree/wifi
et télécharger le fichier switch.py pour remplacer celui que vous avez dans config/custom_components/neviweb130.
redémarrer HA

**Comment by JordanM1738** [comment]
Ca fonctionne bien, la valve est de retour fonctionnelle dans HA.
Merci beaucoup !
