### ISSUE TITLE
HA unable to update value

### ISSUE THREAD

**Issue by OptimAdam** [claudegel/sinope-130#118]
Hi,

I noticed a while back HA dashboard is not reflexing the correct values of my thermosets. I can control them from HA but they are just not updating. My switch is also working when I turn it on and off, so I know HA is polling Neviweb. I looked in the logs and see the following error.

`2022-12-08 11:36:58.334 DEBUG (SyncWorker_3) [custom_components.neviweb130.climate] Updating neviweb130 climate TH1500ZB (1.943 sec): {'roomSetpoint': 19, 'outputPercentDisplay': 0, 'roomTemperature': {'value': 19.07}, 'roomSetpointMin': 12, 'roomSetpointMax': 22.5, 'roomTemperatureDisplay': 19, 'timeFormat': '12h', 'temperatureFormat': 'celsius', 'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off'}, 'drSetpoint': {'status': 'off', 'value': None}, 'loadConnected': 332, 'lockKeypad': 'unlocked', 'backlightAdaptive': 'always', 'systemMode': 'heat', 'config2ndDisplay': 'setpoint', 'rssi': -28}

2022-12-08 11:36:59.887 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.neviweb130_climate_th1500zb_5 fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
raise exc
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/climate.py", line 1014, in update
self._code_wire_sensor = device_error_code["wireSensor"]
KeyError: 'wireSensor'`

Anyone any ideas?

**Comment by claudegel** [comment]
Hi, it's simple, as I don't have a TH1500ZB I was not able to fine tune my neviweb130 for this one. But if you can assist it is very simple to correct this.
The error you got is just because neviweb130 sent a request for the wireSensor attribute and it is not supported by your thermostat. So if you can help me I'll make a new branch to make the corrections.
What browser are you using and are you familiar with the dev consol. If you are using firefox just hit F12 when your in neviweb.com and it will open the dev consol. In that you will see all the attributes requested by neviweb from the Sinopé server.
This way it is possible to see all the specific requested attributes for your TH1500ZB.

**Comment by claudegel** [comment]
I've created a new branch https://github.com/claudegel/sinope-130/tree/TH1500ZB
I just uncomment the line 1002 in climate.py to get in the log what is sent by Neviweb for the device_sensor_error attributes.
You can download the file climate.py or open yours in neviweb130 and remove the # in front of the line 1002.
Then restart HA and watch your log for line containing Updating error code:....
send me that line

**Comment by OptimAdam** [comment]
> I've created a new branch https://github.com/claudegel/sinope-130/tree/TH1500ZB I just uncomment the line 1002 in climate.py to get in the log what is sent by Neviweb for the device_sensor_error attributes. You can download the file climate.py or open yours in neviweb130 and remove the # in front of the line 1002. Then restart HA and watch your log for line containing Updating error code:.... send me that line

I have two different Thermostats, here is error log for both.

**TH1123ZB-G2**
`2022-12-09 14:51:43.403 WARNING (SyncWorker_2) [custom_components.neviweb130.climate] Updating error code: {'compensationSensor': 'ok', 'airTopSensor': 'ok', 'airBottomSensor': 'ok', 'wireSensor': 'ok', 'currentOverload': 'ok', 'thermalOverload': 'ok', 'lineError': 'ok', 'inductiveMode': False, 'endOfLife': False}`

**TH1500ZB**
`2022-12-09 14:51:46.884 WARNING (SyncWorker_1) [custom_components.neviweb130.climate] Updating error code: {'compensationSensor': 'ok', 'airSensor': 'ok', 'floorSensor': 'ok', 'thermalOverload': 'ok', 'base': 'ok'}`


Interesting I see this for the plug too but no update error
2022-12-09 14:51:31.873 DEBUG (SyncWorker_7) [custom_components.neviweb130.switch] Updating neviweb130 switch SP2610ZB (0.824 sec): {'onOff': 'off', 'wattageInstant': 1.9}
2022-12-09 14:51:32.227 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.neviweb130_switch_sp2610zb fails

**Comment by claudegel** [comment]
Thanks for the data. I've updated file climate.py in branch TH1500ZB
Please upload climate.py and replace the one you have in  custom_components/neviweb130
Then restart HA to test
Your G2 is updating well ? it is just the TH1500ZB that is not updating ?

**Comment by OptimAdam** [comment]
They are both updating correctly now.
