### ISSUE TITLE
Unit of measurement HA 2023.1

### ISSUE THREAD

**Issue by simtreti** [claudegel/sinope-130#137]
Bonjour Claude,

Depuis la version 2023.1 de HA les cards de thermostat affiche le unit of measurement avec le HVAC Action mais pour les modèles RF et WF le unit of measurement n'est pas le meme. Pour les RF c'est °C et pour les WF Celcius. Est-ce qu'il y aurait moyen d'afficher également °C pour les WF. Voir photo 

De plus le Preset Home s'affiche egalement pour les Thermostat WF est-ce qu'on pourrait seulement afficher le preset quand il est away et ne rien affiché quand il est home ?

<img width="365" alt="image" src="https://user-images.githubusercontent.com/79706737/214187191-cc999842-9e4a-4e19-928a-b205ef0d7e83.png">

Merci

**Comment by claudegel** [comment]
Merci de me pointer ce problème. J'ai le même avec mes zigbee. Je vais regarder ce qui cloche. Probablement que je dois déclarer le unit of measurement en quelques part.

![celcius](https://user-images.githubusercontent.com/4268938/214195942-3342f58b-9cd0-4fac-9fcb-fdb76c1731eb.jpg)

**Comment by claudegel** [comment]
Salut, j'ai trouvé. On recoit l'unité de mesure de neviweb. Soit celcius ou fahrenheit.
Je vais faire une patch pour les convertir en oC et oF
Donne moi quelques minutes et je vais produire une nouvelle branche pour tester avec tes wifi de ton coté et mes zigbee

**Comment by simtreti** [comment]
Super, pas de probleme je vais tester quand ce sera prêt !

**Comment by claudegel** [comment]
Bon ca fonctionne. J'ai créé une branche
https://github.com/claudegel/sinope-130/tree/temp-celsius/custom_components/neviweb130
copis seulement le fichier climate.py et redémarre HA

**Comment by simtreti** [comment]
Ouep Ca fonctionne ! Merci :)

**Comment by simtreti** [comment]
Pour le preset Home est-ce qu'il ya moyen de faire quelque chose également ?

**Comment by claudegel** [comment]
Comme quoi, quel est le problème

**Comment by simtreti** [comment]
En réalité ce n'est pas un problème, c'est plus un comportement différent des modèles RF. Les RF quand il sont en mode normal on ne voit pas le preset mode tandis que les WF on voit le Preset Home. Les RF affiche seulement le preset quand ils sont away. Je me demandais si ca serais possible d'avoir le meme comportement avec les WF.

**Comment by claudegel** [comment]
Ha c'est que les wifi ont trois preset mode, away, home et none
les autres ont juste away et none
```
PRESET_WIFI_MODES = [
    PRESET_AWAY,
    PRESET_HOME,
    PRESET_NONE,
]

PRESET_MODES = [
    PRESET_AWAY,
    PRESET_NONE,
]
```

**Comment by claudegel** [comment]
as-tu un screen shot pour que je vois. Je n'ai pas de wifi

**Comment by simtreti** [comment]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/79706737/214206008-39408ac4-ae03-42c9-811b-bc41e8ff127a.png">
 Celui ci !

**Comment by claudegel** [comment]
Si tu le met a preset none est-ce que ça affiche quelque chose

**Comment by simtreti** [comment]
Je suis incapable de mettre le preset a none il le prend pas

**Comment by claudegel** [comment]
Moi je vois que je suis incapable de le mettre a away. Bon tu es bon pour trouver les bug.
Je vais faire une release pour le temp celsius et ensuite regarder ce qui cloche pour le preset

**Comment by simtreti** [comment]
De mon coté le preset Away fonctionne par contre. mais voici ce que ca donne dans le log quand j'essaie de le mettre a none. 
2023-01-23 22:27:51.945 DEBUG (SyncWorker_13) [custom_components.neviweb130] Data = {'setpointMode': 'auto'}
2023-01-23 22:27:51.945 DEBUG (SyncWorker_13) [custom_components.neviweb130] Request response = 200
2023-01-23 22:27:51.945 DEBUG (SyncWorker_13) [custom_components.neviweb130] Json Data received= {'setpointMode': 'auto'}
2023-01-23 22:27:51.945 DEBUG (SyncWorker_13) [custom_components.neviweb130] Content = b'{"setpointMode":"auto"}'
2023-01-23 22:27:51.945 DEBUG (SyncWorker_13) [custom_components.neviweb130] Text = {"setpointMode":"auto"}
2023-01-23 22:27:51.946 DEBUG (SyncWorker_7) [custom_components.neviweb130.climate] Updated attributes for neviweb130 climate Garde Robe: ['roomSetpoint', 'outputPercentDisplay', 'roomTemperature', 'roomSetpointMin', 'roomSetpointMax', 'roomTemperatureDisplay', 'timeFormat', 'temperatureFormat', 'drStatus', 'drSetpoint', 'loadConnected', 'loadWattOutput1', 'loadWatt', 'wifiRssi', 'keyboardLock', 'config2ndDisplay', 'setpointMode', 'occupancyMode', 'backlightAutoDim', 'earlyStartCfg', 'roomSetpointAway', 'config2ndDisplay', 'rssi']
2023-01-23 22:27:53.241 DEBUG (SyncWorker_7) [custom_components.neviweb130.climate] Updating neviweb130 climate Garde Robe (1.294 sec): {'roomSetpoint': 18, 'outputPercentDisplay': {'percent': 0, 'sourceType': 'heating'}, 'roomTemperature': {'value': 21.24, 'error': None}, 'roomSetpointMin': 5, 'roomSetpointMax': 30, 'roomTemperatureDisplay': {'value': 21.5, 'status': 'on'}, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off'}, 'drSetpoint': {'status': 'off', 'value': None}, 'loadWattOutput1': 2021, 'loadWatt': 2021, 'wifiRssi': -52, 'keyboardLock': 'unlock', 'config2ndDisplay': 'setpoint', 'setpointMode': 'auto', 'occupancyMode': 'home', 'backlightAutoDim': 'alwaysOn', 'earlyStartCfg': 'off', 'roomSetpointAway': 18}

**Comment by simtreti** [comment]
Les ZB je crois qu'ils n'ont pas de preset mode comparé au WF.

**Comment by claudegel** [comment]
Les ZB dans neviweb c'est comme les RF. Mais avec ton log je vois que au lieu de mettre  à None je le met à auto.
en plus je pense que ce devrait être le occupancyMode qui va à none alors que je met le setpointMode à auto
Donc je devrais avoir dans les log  Data = {'occupancyMode': 'None'}
Je vais fouiller ça un peu et corriger. Mai s pour ce soir je vais juste faire le release du temp format

**Comment by simtreti** [comment]
No stress je m'en vais au dodo également ;)

**Comment by claudegel** [comment]
Il faut aussi que je fasse un release pour les RF car pour eux j'affiche seulement oC et si quelqu'un veut oF ca marchera pas.
Donc deux releases.

**Comment by claudegel** [comment]
J'ai fais les deux releases et effacé les branches pour le oC.
Je vais regarder pour faire le ménage dans les preset et ouvrir une branche pour ça.
Quand j'ai quelques chose a tester je vais t'aviser.
Merci pour ton aide.

**Comment by claudegel** [comment]
Oublis pas de remettre ton setpointMode à manuel au cas ou

**Comment by simtreti** [comment]
Pas de probleme cela me fait plaisir de contribuer à votre excellente integration !

**Comment by claudegel** [comment]
Bonjour,
est-ce possible de valider certains point dans Neviweb. sais-tu comment utiliser la console de débogage dans un navigateur. Il me faudrait l'attribut passer a Neviweb quand on change le preset de None à away et de away à home.
Pour accéder à la console de débug ouvrir neviweb.com dans le naigateur et peser sur F12. Selon le navigateur la console apparait soit à droite de la page (chrome) ou dans le bas (firefox).
Ensuite tu ouvre ton thermostat wifi et change le mode preset. Dans la console tu devrais voir passer quelques chose comme
POST https://neviweb.com/api/location/16515/mode avec la commande
mode: away ou mode:home
Je veux savoir si c'est la même commande pour les wifi

**Comment by simtreti** [comment]
Voici les 2 seuls option soit home ou away sur l'attribut occupancyMode. je suis incapable de mettre none

<img width="420" alt="image" src="https://user-images.githubusercontent.com/79706737/214459979-0190e55b-8516-4eb5-82fe-d85248e2fb72.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/79706737/214460032-d94e07dd-710e-4f49-90d9-658127aec459.png">

**Comment by claudegel** [comment]
C'est bon merci.
C'est drole car le mode home est maintenant présent dans Neviweb pour les zigbee.
Je vais faire le ménage dans les preset

**Comment by claudegel** [comment]
Pour changer le away c'est directement dans la configuration du thermostat ou bien tu changes le home/away au haut de la page d'accueil dans Neviweb ?

**Comment by simtreti** [comment]
Je le fait au niveau de la page d'accueil.  Il est impossible de mettre seulement un thermostat en mode absent dans neviweb sans passer par ton integration dans ha

**Comment by claudegel** [comment]
Ok c'est comme moi pour les zigbee sauf que je ne vois pas de occupancyMode dans les parametre du thermostat quand je regarde la console.
Donc je vais corriger le occupancyMode pour les wifi en premier

**Comment by claudegel** [comment]
J'ai modifié` __init__.py` et climate.py dans cette branche:
https://github.com/claudegel/sinope-130/tree/leak-detector/custom_components/neviweb130
si tu peux tester les modes off/auto/manual et home/away pour tes wifi
dit-moi si c'est beau. Pour les zigbee il faut encore que je travail le home/away parce qu'ils ont pas de occupancyMode comme les wifi.
Il me reste a intégrer les leak sensor WL4210 et si tout est beau je vais publier

**Comment by simtreti** [comment]
Tout fonctionne parfaitement sauf 2 choses banale, quand je change la consigne en etant en mode auto le thermostat devient en mode autobypass et l'icone du thermostat dans HA devient bleu comme si le chauffage etait idle.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/79706737/214986543-617abfe3-b4e2-4ced-b634-f9b0e1269ff2.png">

L'autre chose c'est plus un caprice de ma part haha, mais est-ce qu'il serait possible de ne pas afficher le preset dans l'entity card quand on est en preset home  et seulement l'afficher quand on devient en preset away ? Comme le font les thermostat RF dans HA

**Comment by claudegel** [comment]
Si tu change la consigne manuellement quand tu est en mode auto c'est Neviweb qui te transfert en mode autoBypass. Tu as bypassé le mode auto. Ca revient en auto lors du prochain changement de setpoint dans ton mode auto sur Neviweb.
Pour cacher le preset home je vais regarder ça.
Pour l'icone ca relève de HA. mais tu peux changer l'icone avec customize-ui

As-tu testé le away/home ?

**Comment by simtreti** [comment]
Oui j'ai testé le mode home et away et ca fonctionne comme ca devrait !

Merci à toi pour tous ces ajustements !

**Comment by claudegel** [comment]
Pour le mode home dans le RF il y a pas de preset home. seulement none, away, eco et bypass
Par défaut quand c'est none, HA met rien dans la carte du thermostat. peut-être qu'on pourrait chnanger la ligne 1267 de climate.py pour remplacer par
return PRESET_HOME
remplacé par
return PRESET_NONE
tu peux essayer de ton coté car je n'ai pas de wifi

**Comment by simtreti** [comment]
Je confirme que la modification sur la ligne 1267 fonctionne ! Vraiment super !

<img width="402" alt="image" src="https://user-images.githubusercontent.com/79706737/214997840-e822ec92-bd23-4901-946f-10c8dbf808f6.png">

**Comment by claudegel** [comment]
je pense qu'on va le faire comme ca. Quand on est à la maison on sait que c'est preset-home. pas besoin de l'afficher :)
Bon il me reste juste a trouver comment on peut passer tout neviweb en home ou away à ârtir de HA et ca va etre complet

**Comment by claudegel** [comment]
J'ai publié une nouvelle version

**Comment by simtreti** [comment]
Super Merci encore pour les modifications !

Le 8 févr. 2023 à 21:10, Claude Gelinas ***@***.***> a écrit :



J'ai publié une nouvelle version
