### ISSUE TITLE
Extra number at end of line breaks interpretation.

### ISSUE THREAD

**Issue by jurw2201** [claudegel/sinope-130#153]
https://github.com/claudegel/sinope-130/blob/9b30a3b901ce2d64d62f09ee3cd3ceeb5b523b3b/custom_components/neviweb130/climate.py#L1085

**Comment by jurw2201** [comment]
Using VS Code, or any file editor, we're able to remove that '2' and restart HA to fix any issues.

**Comment by claudegel** [comment]
Sorry I was away yesterday. I'll make a release to fix that

**Comment by claudegel** [comment]
Thanks for reporting this. I've released v2.2.2 to fix
