### ISSUE TITLE
Calypso

### ISSUE THREAD

**Issue by gvhomeassistant** [claudegel/sinope-130#160]
Bonjour,
L'intégration fonctionnait parfaitement, jusqu'à hier, après un redémarrage de HAss, Mes thermostats + mon Heavy duty switch sont fonctionnels, mais j'ai perdu les 2 Calypso ... qui apparaissent comme indisponible

**Comment by claudegel** [comment]
Bonjour, le mien est toujours disponible mais les log donnent une erreur 
File "/config/custom_components/neviweb130/switch.py", line 939, in update
    self._temp_status = device_data[ATTR_ERROR_CODE_SET1]["temperature"]
KeyError: 'temperature'
C,est comme si l'attribut temperature est disparue. Il y a eu des mise a jour de neviweb dernièrement. Je vais valider si l'attribut a été remplacé par autre chose.

As-tu ce genre de message dans tes log? s'il y a d'autre KeyError: 'xxx' ça m'aiderait. En attendant je vais regarder pour désactiver cette ligne pour que tu retrouve tes calypso

**Comment by gvhomeassistant** [comment]
Peux tu me dire a quel endroit regarder dans le log ? je vais le faire immédiatement

**Comment by claudegel** [comment]
Recherche les lignes suivantes: 
[custom_components.neviweb130.switch] Updating neviweb130 switch Calypso chauffe eau
neviweb130 switch Calypso chauffe eau c'est le nom de mon Calypso
pour toi remplace avec le nom de tes calypso
Ca semble etre le nom temperature qui a été remplacé par temperatureSensor

**Comment by claudegel** [comment]
Ah je vois que neviweb a ajouté plein de paramètres pour le calypso. je vais créer une nouvelle branche et faire les corrections.

**Comment by gvhomeassistant** [comment]
Je ne vois que 
023-05-18 17:51:58.908 WARNING (SyncWorker_15) [custom_components.neviweb130.switch] Unknown error for neviweb130 switch MC3100ZB: {'error': {'code': 'DVCUNVLB', 'data': {'identifier': '588e81fffe95e008-588e81fffebe8e83'}}}... Report to maintainer.
2023-05-18 17:56:02.420 WARNING (MainThread) [homeassistant.components.unifi] Lost connection to UniFi Network
2023-05-18 17:56:58.941 WARNING (SyncWorker_7) [custom_components.neviweb130.switch] Unknown error for neviweb130 switch MC3100ZB: {'error': {'code': 'DVCUNVLB', 'data': {'identifier': '588e81fffe95e008-588e81fffebe8e83'}}}... Report to maintainer.
2023-05-18 18:00:00.303 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.neviweb130_switch_chauffe_eau_maison or it is/they are currently not available
2023-05-18 18:01:58.943 WARNING (SyncWorker_16) [custom_components.neviweb130.switch] Unknown error for neviweb130 switch MC3100ZB: {'error': {'code': 'DVCUNVLB', 'data': {'identifier': '588e81fffe95e008-588e81fffebe8e83'}}}... Report to maintainer.
2023-05-18 18:06:58.959 WARNING (SyncWorker_8) [custom_components.neviweb130.switch] Unknown error for neviweb130 switch MC3100ZB: {'error': {'code': 'DVCUNVLB', 'data': {'identifier': '588e81fffe95e008-588e81fffebe8e83'}}}... Report to maintainer.
Mais ca semble etre un de mes devices qui est pas branché, je ne vois rien d'autre
Par contre, les 2 Calypso apparaissent comme "indisponible" dans les périph
L'entrée que tu cherches devrait être fréquente ? 
J'ai pas mal de produits sinopé connectés

**Comment by gvhomeassistant** [comment]
Ha ok, donc ca explique la situation ... j'aimerai vraiment discuter un peu avec toi pour savoir si il est possible de modifier facilement les températures (ou au moins le mode 45 degrés) sur les sinopé ... je joue un peu avec ca dans mes scripts pour la gestion des pointes ! 
Merci pour ton aide !

**Comment by claudegel** [comment]
L'erreur DVCUNVLB survient quand Neviweb fait une mise a jour et bloc temporairement l'accès aux appareils ou si ton appareil est pas branchée.
L'entré [custom_components.neviweb130.switch] Updating neviweb130 switch Calypso chauffe eau 
apparait à chaque mise a jour et tu as  une ligne pour chaque appareil.
Dans ton configuration.yaml as-tu ceci:
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
Si tu as pas cela tu vas manquer ces lignes et avoir juste les warning. ca rempli les logs mais c'est pratique pour débugger les appareils.

**Comment by gvhomeassistant** [comment]
Je vais regarde ca, ca t'arrange que je le fasse la ? ou alors tu as mis le doigt sur le bobo ?

**Comment by claudegel** [comment]
Je vois qu'il y a plein de chose qui ont changés alors je vais plonger et sortir une nouvelle version. En attendant je vais créer une branche corriger l'erreur du calypso.

Pour toi tu peux changer switch.py, ligne 939
remplace 
self._temp_status = device_data[ATTR_ERROR_CODE_SET1]["temperature"]
par
self._temp_status = device_data[ATTR_ERROR_CODE_SET1]["temperatureSensor"]
redémarre HA et dis-moi si ca fonctionne

**Comment by claudegel** [comment]
C'est toujours bon d'avoir un deuxième regard parce que j'ai pas tous les appareils. ca peut aller en fin de semaine si ca t'arrange. En attendant fait la correction dans switch.py et ça devrait corriger ton bug

**Comment by claudegel** [comment]
J'ai crééla branche
https://github.com/claudegel/sinope-130/tree/attribute-patch/custom_components/neviweb130
J'y ai mi la correction pour switch.py

**Comment by gvhomeassistant** [comment]
tu es plus rapide que moi, je viens de corriger et ca redémarre

**Comment by gvhomeassistant** [comment]
Je te confirme que avec le changement a la main, les 2 Calypso sont repartis

**Comment by claudegel** [comment]
Je vais ajouter les nouveaux attributs. je me disais justement que c'est la période creuse de Sinopé. Pas de pointe alors ils vont faire plein d'amélioration. je vais donc réviser tous les attributs des appareils zigbee et si tu as des appareils wifi ça m'aiderait

**Comment by claudegel** [comment]
Est-ce que to MC3100 est raccordé à ton système d'allarme ? moi je l'ai fais mais il a fallu que je change de fournisseur car l'ancien ne voulais pas

**Comment by gvhomeassistant** [comment]
malheureusement, j'ai juste les Zigbee, j'ai beaucoup de thermostats, 1 petit switch , 1 heavy duty sur ma pompe a chaleur, et 2 calypso

Non mon MC3100 est dans un carton juste pour m'amuser :) mon alarme est une Vista20p et je cherche toujours comment la connecter avec un ESP32 

Es tu sur Discord ? je pourrai définitivement t'aider si tu le veux

**Comment by claudegel** [comment]
Non je suis pas discord. J'ai un compte mais j'y vais pas souvent

**Comment by gvhomeassistant** [comment]
Je ne sais pas comment je pourrais te passer mes coordonnées :D 
Mais je suis dispo pour te donner un coup de main et / ou te donner accès a mon instance et mes devices si tu le veux

**Comment by claudegel** [comment]
OK je vais commencer par corriger/ajouter les nouveaux attributs et si besoin je te contacte en fin de semaine.

**Comment by gvhomeassistant** [comment]
Excellent, merci encore pour l'excellent addon et aussi pour le support ! 
Une fois que ca sera fixé, je te reviendrais avec mes questions :D

**Comment by claudegel** [comment]
Ok merci pour avoir soumit le bug

**Comment by claudegel** [comment]
J'ai fais un nouveau release pour tous les nouveaux attributs ajoutés par Neviweb pour les switch et thermostats.

**Comment by gvhomeassistant** [comment]
Je viens de l'installer, je vais faire quelques tests ! 
Est il possible d'afficher la puissance instantanée consommée dans le Bouton ON/OFF quand un appareil est actif ?

**Comment by claudegel** [comment]
L'information sur la puissance instantanée pour le calypso est dans l'attribut "Wattage_instant"
Pour l'afficher il faut créer un template sensor comme ceci et l'ajouter dans une carte lovelace.
```
- template:
  - sensor:
    - name: "watt_chauffe_eau"
      unit_of_measurement: 'W'
      device_class: power
      state_class: measurement
      unique_id: sensor.watt_chauffe_eau
      state: "{{ state_attr('switch.neviweb130_switch_calypso_chauffe_eau_2', 'Wattage_instant') }}"
```
ca va créer un sensor.watt_chauffe_eau qui aura la valeur de la puissance
