### ISSUE TITLE
SP2600ZB déconnecter cause des messages d'erreurs

### ISSUE THREAD

**Issue by AlexandreFoley** [claudegel/sinope-130#165]
J'ai une switch intélligente qui n'est pas utiliser depuis noel dernier. 
Une erreur inconnue s'est produit 1010 fois depuis le 14 juillet, possiblement suite a une mise à jour:
` Unknown error for neviweb130 switch SP2600ZB: {'error': {'code': 'DVCUNVLB', 'data': {'identifier': '588e81fffe95da05-000d6f0015662026'}}}...(SKU: SP2600ZB) Report to maintainer. `

**Comment by claudegel** [comment]
Je suis malheureusement absent. De retour samedi prochain je vais regarder.A premiere vue, DVCUNVLB signifit que Neviweb ne reussit pas a communiquer avec votre appareil. Avez-vous validé si dans Neviweb cet appareil est disponible. Il faut peut-etre simpllement le réappareiller avec Neviweb. Dans mon readme.md il y a une procedure pour reinitialiser votre SP2600ZB.Claude Gelinas agr.Phyto Ressources inc
-------- Message d'origine --------De : Alexandre Foley ***@***.***> Date : 2023-07-18  9 h 28 p.m.  (GMT-05:00) À : claudegel/sinope-130 ***@***.***> Cc : Subscribed ***@***.***> Objet : [claudegel/sinope-130] SP2600ZB déconnecter cause des erreurs (Issue #165) 
J'ai une switch intélligente qui n'est pas utiliser depuis noel dernier.
Une erreur inconnue s'est produit 1010 fois depuis le 14 juillet, possiblement suite a une mise à jour:
Unknown error for neviweb130 switch SP2600ZB: {'error': {'code': 'DVCUNVLB', 'data': {'identifier': '588e81fffe95da05-000d6f0015662026'}}}...(SKU: SP2600ZB) Report to maintainer.

**Comment by AlexandreFoley** [comment]
L'appareil est déconnecté et ça va resté comme ça jusqu'à ce que j'en ai besoin de nouveau.
Idéalement, un appareil absent ne cause pas d'erreur inconnue.
Il n'y a vraiment aucun problème en ce qui me concerne. Simplement que le message me demandais de rapporter le problème, alors voila c'est fait =p.

**Comment by claudegel** [comment]
Lorsque vous déconnectez un appareil sans l'enlever de Neviweb, HA ne le sait pas et il continue à tenter de le mettre à jour selon la fréquence déterminée par le paramètre scan_interval. D'où le nombre élevé de message DVCUNVLB qui est retourné par Neviweb à chaque tentative de mise a jour de l'appareil. Je vais donc modifier neviweb130 pour désactiver l'appareil qui n'est plus relié à Neviweb. De cette facon les messages cesseront car HA ne tentera plus de mettre a jour cet appareil.
Report to maintainer, m'a permit de trouver ce message d'erreur et de cette façon je vais pouvoir le gérer correctement.
Svp ne pas enlever votre appareil de neviweb et pour arrêter les message d'erreur simplement désactiver la ligne suivante dans switch.py
ligne 1150
`_LOGGER.warning("Unknown error for %s: %s...(SKU: %s) Report to maintainer.", self._name, device_data, self._sku)`
devient:
`#            _LOGGER.warning("Unknown error for %s: %s...(SKU: %s) Report to maintainer.", self._name, device_data, self._sku)`
simplement mettre un # au début de la ligne et redémarre HA.
je vais créer une nouvelle branche avec le correctif et vous aviser lorsque ce sera pret a tester

Merci de votre aide.

**Comment by claudegel** [comment]
J'ai créer une branche error-handlling:
https://github.com/claudegel/sinope-130/tree/error-handling/custom_components/neviweb130
Neviweb130 va pouvoir détecter l'erreur DVCUNVLB et stopper les requêtes vers Neviweb pour cet appareil. Si l'appareil est rebranché j'ai ajouter le service neviweb130.set_activation pour réactiver les requêtes vers Neviweb quand l'appareil est rebranché.
Si vous avez le temps de tester il ne dervait plus y avoir de message DVCUNVLB. Il faut télécharger tous les fichiers du répertoire ci-dessus et les mettre a la place des vôtre dans config/custom_components/neviweb130
Merci pour votre aide.

**Comment by claudegel** [comment]
Je vais publier une nouvelle version. De mon coté tout semble fonctionner.
merci d'avoir signalé ce problème

**Comment by AlexandreFoley** [comment]
Merci pour tout. Je teste cela dès que je suis de retour à la maison.

--

Alexandre Foley

De : Claude Gelinas ***@***.***>
Date : mardi, 25 juillet 2023 à 21:29
À : claudegel/sinope-130 ***@***.***>
Cc : Alexandre Prémont-Foley ***@***.***>, Author ***@***.***>
Objet : Re: [claudegel/sinope-130] SP2600ZB déconnecter cause des messages d'erreurs (Issue #165)

Je vais publier une nouvelle version. De mon coté tout semble fonctionner.
merci d'avoir signalé ce problème
