### ISSUE TITLE
Current temperature not updating

### ISSUE THREAD

**Issue by DanielRegert** [claudegel/sinope-130#168]
Hi, 

I have two TH1123WF and everything was working well until I updated HASS core / OS to their latest version (2023.8.0). What's happening now is that the current temperature is only read once after I restart the system after that, the temperature is no longer updated (until I restart the system again). 
This might be an issue with this plugin, but I'm not sure where to start debugging this issue. Could you give me some points on how to dig a bit deeper and see if I can find out what's happening?

Thanks

**Comment by claudegel** [comment]
When neviweb130 catch error code DVCUNVLB for one device, this indicate that the device is not connected to Neviweb. To avoid lot of error message in your log the device is deactivated and data polling is stopped. At each restart, neviweb130 will try once to poll the disconnected device. If it is back, the device will be reactivated.
You can also reactivate the device with service.neviweb130_set_activation if you don't want to restart HA.

**Comment by claudegel** [comment]
Let me know if it happen again. Maybe there is something specific with wifi device on Neviweb. We can dig a little to try to find out.
Thank's
