### ISSUE TITLE
Appareils hors-ligne n'apparaissent pas indisponible dans HA

### ISSUE THREAD

**Issue by antoineDion** [claudegel/sinope-130#170]
Lorsque les thermostats TH1310WF ne sont pas alimentés, ils apparaissent hors-ligne dans l'application NeviWeb mais pas dans homeassistant. Dans homeassistant ces toujours les dernières valeurs lue qui sont affichés.

**Comment by claudegel** [comment]
Ceci est le même bug que #169. je constate que lorsqu'un appareil wifi est déconnecté de Neviweb il y a énormément de message d'erreur qui emplissent les log. Pour le moment lorsque je détecte qu'un appareil wifi est déconnecté de Neviweb je stop les requêtes vers Neviweb pour cet appareil pour éviter de remplir les log.
A chaque redémarrage de HA je revérifie l'état de l'appareil sur Neviweb et si tout est OK je redémarre les requêtes, sinon il n'y a pas de requête. J'ai ajouté un service.neviweb130.set_activation pour réactiver ou stopper les requêtes sans redémarrer HA.
le problème des appareils wifi qui se débranchent de Neviweb vient habituellement des routers. Certain modèles comme le Bell hub 3000 n'acceptent que 15 appareils wifi en même temps. Les routers Asus sont connus pour le même problème. Dans ce dernier cas changer le parametre DTIM à 1 règle le problème.
je cherche un manière de débrancher les appareils wifi de HA quand je détecte que ceux-ci ne sont plus connectés à Neviweb. de cette facon l'utilisateur pourra détecter le problème plus repidement et reconnecter l'appareil en cause.

**Comment by michaeldufour** [comment]
Allo Claude 
J'ai également un problème avec un thermostat ou Neviweb130 semble arrêter les requêtes
J'essais de redémarrer les requêtes avec ce script mais toujours en arrêt:

service: neviweb130.set_activation
data:
  entity_id: climate.neviweb130_climate_th1123wf_solarium
  active: true

Aucun erreur dans les log.

Est-ce qu'il y a quelque chose qui n'est pas correct?

Merci

**Comment by claudegel** [comment]
Votre thermostat est un wifi alors votre réseau wifi est saturé. Votre router ne supporte pas suffisamment de connection simultanée. Il faut ajouter  une passerelle wifi qui va permettre d'ajouter plus de connection wifi simultanée. De cette façon le thermostat restera connecté en permanence.
Vous devez avoir cet erreur dans vos logs: DVCUNVLB
Votre appareil wifi se débranche de Neviweb et n'est plus disponible pour HA. Dans ce cas je désactive le thermostat pour vous aviser qu'il y a un probleme avec cet appareil.

**Comment by claudegel** [comment]
Que dit Nevuweb pour cet appareil ?

Au oire edites le fichier climate.py dans custom_component/neviweb130 et recherche la ligne 1087
self._activ = False
change pour 
# self._activ = False
Ca va arrêter de désactiver ton thermostat mais il faudra trouver pourquoi il se déconnecte de Neviweb

**Comment by michaeldufour** [comment]
Bonjour dans Neviweb  il est actif.
La ligne 1087 était déjà à false
Je me suis fait un automation pour voir quand je suis plus en mesure de rejoindre l'adresse IP du thermostat, je vais voir si je perd physiquement le thermostat.

Merci Claude

**Comment by claudegel** [comment]
Quand l'erreur DVCUNVLB est détectée dans la réponse de Neviweb le self._active devient false et le polling de l'appareil arrête
en mettant un `#` devant la ligne ca maintient le polling actif, self._activ = True, même si Neviweb envoit le code DVCUNVLB.

**Comment by michaeldufour** [comment]
Ah en effet j'avais pas vu le # désolé merci de votre aide.
