### ISSUE TITLE
Thermostat Sinipe TH-1400ZB retourne une valeur de consommation négative

### ISSUE THREAD

**Issue by SN0WTR00PER** [claudegel/sinope-130#180]
Bonjour M. Gélinas,

J'ai un thermostat TH-1123ZB-G2 qui m'a retourné une valeur d'énergie consommé négative de 1800.2 kwh dans Home Assistant lorsque je l'ai réalimenté.

À titre informatif, ce thermostat a été débranché tout l'été pour fin de rénovation d'une salle de lavage.

Lorsque j'ai réalimenté le chauffage, 2h après, mon tableau de bord "Énergie" représentait une consommation négative de -1800khw pout ce thermostat.  Le thermostat n'a  même pas chauffé.  Il était en mode idle.

J'ai essayé de corriger les statistiques via l'outil de développement->Satistiques->Ajuster la somme.  La valeur de consommation négative n'y apparait pas.

J'ai déconnecté le thermostat du système "Home assistant" et j'ai effectuer une restauration de sauvegarde complète de la journée précédente.  2h après, la même chose recommence.  Valeur négative de 1800.2.  Est-ce qu'il y a une valeur résiduelle dans la mémoire du thermostat qui conserve cette mauvaise valeur?

Enfin bref, J'ai refais une restauration de sauvegarde afin d'effacer ce report de 1800.2kwh.

J'ai ré-additionner à nouveau le thermostat au système.  2h après, encore la même valeur reportée dans le tableau de bord "Énergie".

J'ai tenté d'en faire "RESET" ou "CLR" du thermostat en suivant la procédure sur le site de Sinopé... hélas, je ne suis pas sur si cela a fonctionnée.  Lire ci-dessous ce que ma tentative de reset a donnée.

J'ai appuyé sur le bouton TEMP+ jusqu'à ce que le menu s'affiche.
J'ai appuyé sur les deux boutons TEMP+ et TEMP- jusqu'à ce que l'affichage indique RST.  Cela ne   J'imagine que cela veud rire "RESET".
Et ensuite, le thermostat a redémarrer seul.  Je n'ai pas eu besoin de sélectionner l'option "CLR".  Le thermostat ne me permet pas de le faire.

Une idée du problème?  Comment éditer la base de donnée SQL?

Merci à l'avance pour votre aide!
![2023-10-25 20_14_31-Clipboard](https://github.com/claudegel/sinope-130/assets/18689208/3f908b40-e86c-4cc3-924b-04234d9921df)

Stéphane Néron

**Comment by claudegel** [comment]
Bonjour, j'ai jamais vu cela. Pour faire un reset c'est supposé d'être comme ceci. Il faut peser plusieurs fois sur les deux boutons pour arriver à l'option CLR

    Raise the temperature until the display change.
    Push the two button until CLR appear on the screen.
    Push once the upper button to get YES on the display.
    Push both button simutanously and release immediately. DONE should appear on the screen.
    The thermostat will restart with factory setup.
Le thermostat conserve le total et je pense qu'il y a un moyen de le remettre a zéro mais il faudrait que je fouille  un peu. Est-ce que votre thermostat est avec neviweb130 ou avec zha?

Pour éditer la base de données ça prend un éditeur pour cette base de donnée qui est en sqlite
[Home Assistant Community Add-on: SQLite Web](https://community.home-assistant.io/t/home-assistant-community-add-on-sqlite-web/68912)

**Comment by claudegel** [comment]
C'est le fun des faciles de même. Avez-vous pu faire un CLR du thermostat ?

**Comment by SN0WTR00PER** [comment]
> C'est le fun des faciles de même. Avez-vous pu faire un CLR du thermostat ?

Oui j'ai pu faire un reset du thermostat.  À propos, la procédure de reset des thermostats de 2e génération n'est pas la me^me que celle des 1ere.  Rendu dans le menu, il faut tenir les deux boutons (UP DOWN) et attendre que le thermostat affiche "RST" et il va redémarrer de lui même à neuf.

Oui, c'est toujours plus agréable d'avoir le moyen d'utiliser home assistant pour régler la problématique avec un outils interne plutôt qu'essayer de jouer dans la base de donnée, chose que je n'ai jamais faite.  Et j'ai peur de "foutre" le bordel :)

**Comment by claudegel** [comment]
OK merci je vais l'ajouter dans mon readme.md
