### ISSUE TITLE
Sinope neviweb130 update - Impossible d'installer la version 2.4.1 

### ISSUE THREAD

**Issue by d3xt3r67** [claudegel/sinope-130#181]
Bonjour, 

Lorsque je tente d'installer la mise à jour 2.4.1 j'ai toujours le message d'erreur suivant: 
![image](https://github.com/claudegel/sinope-130/assets/15317580/ca992cf4-7c59-46da-bb82-c948b7195c75)
![image](https://github.com/claudegel/sinope-130/assets/15317580/49e41b0b-f468-44ea-b648-a4d6893dc5b0)

**Comment by claudegel** [comment]
Bonjour, merci de me rapporter ce bug. la dernière version est 2.4.1 mais il semble y avoir un bug dans les versions sur github.
je vais verifier et au pire faire une nouvelle version. Je vous avise quand j'ai trouvé

**Comment by claudegel** [comment]
Je pense que le bug vient de hacs. De mon coté sur HA ma dernière version sur hacs est 2.4.0 alors que sur mon git c'est 2.4.1

**Comment by d3xt3r67** [comment]
> Je pense que le bug vient de hacs. De mon coté sur HA ma dernière version sur hacs est 2.4.0 alors que sur mon git c'est 2.4.1

J'ai redémarré mon HA juste pour voir. La notification de mise à jour à disparue et la seule version disponible semble la 2.4.0
![image](https://github.com/claudegel/sinope-130/assets/15317580/ede61de7-1224-41b7-a883-91ac3a36f2d5)

**Comment by claudegel** [comment]
la version 2.4.1 est pour les DM2550ZB G2. En fin de semaine je vais probablement faire une nouvelle mise a jour pour les valves et alors ca va créer la version 2.4.2. En attendant je vais vérifier avec HACS pour voir si il n'ignore pas la version active qui est 2.4.1 ou si ca vient de changement dans git hub

**Comment by claudegel** [comment]
la version 2.4.1 est maintenant disponble. Il y avait un bug avec git hub
