### ISSUE TITLE
Problème avec TH1400ZB

### ISSUE THREAD

**Issue by jefmartel** [claudegel/sinope-130#182]
2023-10-29 22:33:31.042 DEBUG (SyncWorker_1) [custom_components.neviweb130.climate] Updating neviweb130 climate Neviweb Custom Name Thermostat (0.567 sec): {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '287681fffe615b6e-500b9140000269fc'}}}
2023-10-29 22:33:31.043 WARNING (SyncWorker_1) [custom_components.neviweb130.climate] Device attribute not supported for neviweb130 climate Neviweb Custom Name Thermostat: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '287681fffe615b6e-500b9140000269fc'}}}...(SKU: TH1400ZB)

**Comment by claudegel** [comment]
It's ok for firefox. To open the dev console just hit F12 when you are in Neviweb. The console will appear at the bottom.
Then select «Console» in the top horizontal menu. Bellow you will see many lines starting with GET https... Each line is what you receive from Neviweb when you click on something above in the Neviweb window. So select your TH1400ZB and open the configuration, all options. You will see new lines in the console. click on the small triangle on the left of each line to see the content and select «Reponse» to see the parameter with there value. On the left there is also a «Requête» button to see what is sent to Neviweb when you change a value. See the picture below.
![firefox console](https://github.com/claudegel/sinope-130/assets/4268938/9c12bca2-e27e-4969-a3e2-7825e1868d40)

**Comment by claudegel** [comment]
This way we will be able to see all parameters for your TH1400ZB

**Comment by claudegel** [comment]
I see that your parameter options display in Neviweb is different then what I have. There is a question mark on the left side of each options. In mime there is nothing. Do you have a different Neviweb app
![2c8979e367286b086f2f8d990d0629e6ea634a44](https://github.com/claudegel/sinope-130/assets/4268938/9fd5ffbc-d901-4a03-a65d-4e74dd2e97a8)

**Comment by claudegel** [comment]
![parameter display](https://github.com/claudegel/sinope-130/assets/4268938/e9dd89fb-ce72-43c1-99ab-43e700f36780)

**Comment by jefmartel** [comment]
I just enabled the infotip in the settings.

Here are the info

roomSetpoint	5
roomTemperature	
outputPercentDisplay	0
systemMode	"off"
roomSetpointMin	5
roomSetpointMax	36
backlightAdaptive	"always"
temperatureFormat	"celsius"
timeFormat	"24h"
airFloorMode	"airByFloor"
floorSensorType	"10k"
signature	Object { model: 7372, modelCfg: 0, softBuildCfg: 0, … }
cycleLengthOutput2	Object { status: "off", value: null }
cycleLength	900
systemMode	"off"
rssi	-47
floorLimitHigh	Object { status: "off", value: null }
floorLimitLow	Object { status: "off", value: null }
floorMaxAirTemperature	Object { status: "off", value: null }
pumpProtectStatus	"off"
pumpProtectPeriod	
pumpProtectDuration

**Comment by claudegel** [comment]
Thank's you are missing config2ndDisplay for outside temperature, lockKeypad to lock the keypad on thermostat and drStatus drSetpoint those two are activated when you add your thermostat to ÉcoSinopé. Does your thermostat is registered to ÉcoSinopé ?
What do you have in advance option ?

**Comment by jefmartel** [comment]
Looks like you are right here. They were all registered but I added the 1st floor much later so it wasn't registered with EcoSinope. I just did the registration and it could take up to 24h to see the change. I'll let you know how it goes tomorrow. Thanks for you help Claude.

**Comment by claudegel** [comment]
I'l let you know when I have a test branch ready to test all those attributes

**Comment by claudegel** [comment]
Quel est la version du firmware dans option pour le thermostat. Sinopé me dit que ça devrait etre 0.1.6

**Comment by jefmartel** [comment]
Modele 7372
Firmware 0.0.7
Version matérielle 0

**Comment by gobol007** [comment]
Same problem here with TH1124ZB... But the TH1124ZB-G2 work great...

Info to my TH1124ZB                   Info to my TH1124ZB-G2
Model : 1124                                Model : 300
Firmware : 0.6.4                            Firmware : 0.1.1
Material : 3                                   Material: 0

![image](https://github.com/claudegel/sinope-130/assets/8069819/0134524a-8dc9-4d01-8dfa-3d9310f25fb2)


State of TH1124ZB (In dev Tools of HA)
--------------------------
hvac_modes:
  - 'off'
  - heat
min_temp: 0
max_temp: 0
preset_modes:
  - away
  - none
current_temperature: null
temperature: null
hvac_action: idle
preset_mode: none
wattage: 0
status compensation sensor: null
status wire sensor: null
status current sensor: null
status thermal sensor: null
status end of life sensor: null
cycle_length: 0
status air sensor: null
status reference sensor: null
status load sensor: null
heat_level: 0
temp_display_value: null
second_display: null
keypad: null
backlight: null
time_format: 24h
temperature_format: °C
setpoint_max: 0
setpoint_min: 0
eco_status: 'off'
eco_optOut: 'off'
eco_setpoint: 'off'
eco_power_relative: 'off'
eco_power_absolute: 'off'
eco_setpoint_status: 'off'
eco_setpoint_value: null
hourly_kwh_count: 0
daily_kwh_count: 0.009
monthly_kwh_count: null
hourly_kwh: 0.009
daily_kwh: 0
monthly_kwh: null
rssi: null
sku: TH1124ZB
Activation: true
model: 1124
id: 449689
unit_of_measurement: °F
device_class: temperature
friendly_name: neviweb130 climate Salon
supported_features: 17

**Comment by claudegel** [comment]
what problem exactly.

**Comment by gobol007** [comment]
J'ai 9 X **TH1124ZB-G2** qui fonctionne très bien.

J'ai 1 X **TH1124ZB** qui n'Affiche aucune info sur la carte dans Home Assistant, par contre je peut le contrôler avec Node Red...
Le modèle qui ne fonctionne pas :
TH1124ZB
Model : 1124 
Firmware : 0.6.4 
Material : 3

Les valeur que retourne l'intégration qui me semble causer le problème : 
min_temp: 0
max_temp: 0
current_temperature: null
temperature: null

J'aurais peut-être dû ouvrir un autre issue... désoler...

**Comment by claudegel** [comment]
Pouvez-vous installer du debug dans HA ? 
mettez dans configuration.yaml 
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
ensuite redémarrer HA et recherchez dans home-assistant.log  les lignes suivantes:
[custom_components.neviweb130.climate] Updating neviweb130 climate nom de votre thermostat...
[custom_components.neviweb130.climate] Updated attributes for neviweb130...

Il semble que la mise a jour du thermostat ne se fait pas, possiblement parce qu'il y a un attribut qui ne fonctionne pas. Neviweb retourne alors l'erreur {'error': {'code': 'DVCATTRNSPTD',  et ne retourne pas les valeurs pour les etats dans HA.
Je dois installer deux nouveau TH1124ZB demain. Je vais voir qu'elle est le numéro de firmware et si il y  a une erreur.

**Comment by gobol007** [comment]
Cette erreur provient d'une intégration personnalisée

Logger: custom_components.neviweb130.climate
Source: custom_components/neviweb130/climate.py:1092
Integration: Sinope Neviweb130 (documentation)
First occurred: 21:31:49 (1 occurrences)
Last logged: 21:31:49

Device attribute not supported for neviweb130 climate Salon: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '287681fffe6648f1-500b91400002cc82'}}}...(SKU: TH1124ZB)

**Comment by claudegel** [comment]
DVCATTRNSPTD ça veut dire qu'on demande une valeur pour un attribut qui n'est pas supporté par ce thermostat. Ce qui est étrange c'est que ce sont des attributs comme keyboardlock et outside temperature qui ont toujours été supportés. Je prépare une branche spéciale pour trouver ce qui n'est pas supporté mais je soupsonne les attribut roomTemperatureDisplay, config2ndDisplay et lockKeypad. je vais les retirer de la requete envoyé à Neviweb et si ce sont les coupable les états devraient se repeupler et l'erreur DVCATTRNSPTD va disparaitre

**Comment by claudegel** [comment]
J'ai un TH1123ZB d'installé et il fait la même requête que le TH1124ZB et il n'y a pas d'erreur... a suivre demain

**Comment by gobol007** [comment]
Ce matin j'ai toujours la même erreur dans les logs mais la carte de Home Assistant affiche maintenant l'info du thermostat et je peut le contrôler dans Home assistant... Biz... Je vais continuer à valider les logs voir...

Maintenant il affiche la Version Firmware : 0.6.8 (Sinopé à mit à jour cette nuit ?!)

![image](https://github.com/claudegel/sinope-130/assets/8069819/c9e0917a-7fc5-459c-b403-d9dcf874b65a)
: 

Logger: custom_components.neviweb130.climate
Source: custom_components/neviweb130/climate.py:1092
Integration: Sinope Neviweb130 ([documentation](https://github.com/claudegel/sinope-130))
First occurred: 31 octobre 2023 à 21:31:49 (68 occurrences)
Last logged: 04:08:17

Device attribute not supported for neviweb130 climate Salon: {'error': {'code': 'DVCATTRNSPTD', 'data': {'identifier': '287681fffe6648f1-500b91400002cc82'}}}...(SKU: TH1124ZB) #

**Comment by jefmartel** [comment]
TH1400ZV updaté ce matin. Les options de 2e affichage sont présente dans Neviweb. Firmware à la version 0.1.6. Les consigne de température fonctionne mais, je ne vois pas la température intérieure dans HomeAssistant

**Comment by claudegel** [comment]
Bonjour, désolé du retard mais ce matin mon power supply de mon firewall a sauté.. plus rien. 
Je suis de nouveau en ligne avec encore quelques bug a ajuster
C'est certain que si le firmware ne suporte pas certains attribut  alors ca va causer une erreur de type DVCATTRNSPTD
Sinopé fait pas mal de mise a jour en préparation des pointes hivernales et pour le projet pilote de Hydro
@gobol007  peux-tu redémarrer HA pour voir si ca va aussi corriger le problème.
@jefmartel peux-tu m'envoyer la ligne de log  [custom_components.neviweb130.climate] Updating neviweb130 climate ...
je voudrais valider les valeurs retournées par Neviweb

**Comment by gobol007** [comment]
Après redémarrage, les erreurs ne semble plus là... tout semble être beau... YES ! (redémarrer depuis 18h ce soir)
La mise à jour de 0.6.4 à 0.6.8 à dû faire un changement tu crois ?

Et désoler pour ton power supply :)

**Comment by claudegel** [comment]
Dans neviweb dans certain fichier de controle il y a des listes d'attribut avec des référence aux numéro de firmware. Ca veux dire que certain attributs ne sont accessibles que quand l'appareil est updater à un certain numéro de firmware. En mettant a jour ça a débloqué les attributs qui n'étaient pas accessibles.
je vais proposer à Sinopé d'ajouter un bouton dans neviweb pour vérifier les mise a jour disponibles pour cheque appareils et si il y en a une de la faire immédiatement. Présentement Sinopé fait les mises a jour selon le développement des firmwares. Si ton appareil n'est pas connecté lors de la mise a jour ca peu prendre des jours avant que tu soit mis a jour.
Donc si tout est beau on peu fermer cet issue ? Je vais fouiller un peu plus pour voir si on peut mettre la main sur une liste des plus récents firmware des appareils.

**Comment by gobol007** [comment]
Pour ma part, oui on peut fermer l'issue, mais je suis pas le "premier" demandeur de l'issue ([jefmartel](https://github.com/jefmartel)). J'avais acheté ce thermostat en juin, juillet et je l'ai installé seulement lundi :)... ça explique probablement ma première version de firmware ! Ça serait super d'avoir le bouton de mise à jour ! Un gros merci pour ta rapidité !!

**Comment by jefmartel** [comment]
J'avais écris Sinopé pour savoir quand les mises à jour se sont et on m'a répondu que c'était une fois par jour la vérification. Selon mon expérience, c'est pas à chaque jour mais ça finit par se faire.
On peut fermer le ticket. Merci à Claude à qui j'aimerais bien envoyer une bière!

**Comment by claudegel** [comment]
Merci pour avoir rapporté ce problème. Ca va aider les autres .
Est-ce possible d'avoir la ligne de log **[custom_components.neviweb130.climate] Updating neviweb130 climate...**
pour votre thermostat TH1400ZB et TH1124ZB. Je veux valider les valeurs que Neviweb retourne lors de la mise a jour du thermostat. Déjà je vois qu'il y a de nouveaux attributs pour les thermostats G2 que je suis a installer en remplacement de mes vieux miwi. Ca m'aiderais dans le développement de HA
Merci

**Comment by claudegel** [comment]
Si vous avez d'autres thermostats, même des wifi, même chose. Ca va me permettre de développer. je manque de système chauffage pour tester tous les modèles de thermostats Sinopé. :)

**Comment by jefmartel** [comment]
2023-11-01 20:37:32.919 DEBUG (SyncWorker_2) [custom_components.neviweb130.climate] Updating neviweb130 climate Sinope 1er etage (2.208 sec): {'roomSetpoint': 5, 'outputPercentDisplay': 0, 'roomTemperature': {'value': 21.98}, 'roomSetpointMin': 5, 'roomSetpointMax': 36, 'roomTemperatureDisplay': 22, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off'}, 'drSetpoint': {'status': 'off', 'value': None}, 'lockKeypad': 'unlocked', 'backlightAdaptive': 'always', 'systemMode': 'heat', 'cycleLength': 900, 'pumpProtectDuration': {'status': 'on', 'value': 60}, 'pumpProtectPeriod': {'status': 'on', 'value': 1}, 'floorMaxAirTemperature': {'status': 'off', 'value': None}, 'airFloorMode': 'airByFloor', 'floorSensorType': '10k', 'floorLimitHigh': {'status': 'off', 'value': None}, 'floorLimitLow': {'status': 'off', 'value': None}, 'cycleLengthOutput2': {'status': 'off', 'value': None}, 'config2ndDisplay': 'default', 'rssi': -39}

**Comment by claudegel** [comment]
je ferme cet issue. vous pouvez toujours la réouvrir si besoin
Merci de votre aide pour corriger le problème

**Comment by claudegel** [comment]
@jefmartel et @gobol007 est-ce possible de me dire quel sont les valeurs possibles pour les attributs pumpProtectDuration et pumpProtectPeriod dans la configuration de votre TH1400ZB dans Neviweb
Merci,

**Comment by jefmartel** [comment]
> @jefmartel et @gobol007 est-ce possible de me dire quel sont les valeurs possibles pour les attributs pumpProtectDuration et pumpProtectPeriod dans la configuration de votre TH1400ZB dans Neviweb Merci,

pumpProtectPeriod	
status	"on"
value	1
pumpProtectDuration	
status	"on"
value	60

pumpProtectPeriod	
status	"off"
value	null
pumpProtectDuration	
status	"off"
value	null

**Comment by gobol007** [comment]
> @jefmartel et @gobol007 est-ce possible de me dire quel sont les valeurs possibles pour les attributs pumpProtectDuration et pumpProtectPeriod dans la configuration de votre TH1400ZB dans Neviweb Merci,

Pour ma part mes TH1124ZB-G2 et TH1124ZB n'ont pas ces attributs là... et j'ai pas de TH1400ZB :)

**Comment by claudegel** [comment]
Est-ce qu'il y a plusieurs valeurs possible pour pumpProtectDuration et pumpProtectPeriod

**Comment by jefmartel** [comment]
> Est-ce qu'il y a plusieurs valeurs possible pour pumpProtectDuration et pumpProtectPeriod

Quand je mets la protection de la pompe, ça change la valeur pour 60. 
Pour la période, je ne vois pas cette option a changer

**Comment by claudegel** [comment]
Ok merci
