### ISSUE TITLE
The temperatureFormat in service set_temperature_format expects "celcius" instead of "celsius"

### ISSUE THREAD

**Issue by visto9259** [claudegel/sinope-130#188]
The `temperatureFormat` argument in service `set_temperature_format`checks for `celcius` instead of `celsius`.

Then it sends `celcius` to the device which does not work.  

The bug is here in `climate.py`:

`SET_TEMPERATURE_FORMAT_SCHEMA = vol.Schema(
    {
        vol.Required(ATTR_ENTITY_ID): cv.entity_id,
        vol.Required(ATTR_TEMP): vol.In(["celcius", "fahrenheit"]),
    }
)`

This is a small fix. Let me fork and do a PR to fix it.

**Comment by claudegel** [comment]
Nice catch. We need to change climate.py. No need for a PR I'll fix it now

**Comment by claudegel** [comment]
I've created a new branch typo to fix this. I'll do a release this week

**Comment by claudegel** [comment]
I've push the release 2.4.6. Thanks for reporting this.
