### ISSUE TITLE
PyNeviwebError is not defined

### ISSUE THREAD

**Issue by visto9259** [claudegel/sinope-130#192]
In `__init__.py` at line 315, there is a call to `PyNeviwebError`.

This should be a call to `PyNeviweb130Error`.  I guess this must be a test case that never occured in the past.

Pylint picked that one up in my VS Code dev install.

**Comment by claudegel** [comment]
Hi thank you for reporting this. It was only for those who have two GT130 in Neviweb so not too frequent
It will appear in 2.4.8
