### ISSUE TITLE
Unable to restart after changing configuration.yaml

### ISSUE THREAD

**Issue by CoOlSlY007** [claudegel/sinope-130#197]
In /root/config/custom_components/neviweb130 I have all the files. I then copy-paste in configuration.yaml the following exactly (the ' are there, other then password is not password) and when I try to reboot, I have this question:
1) Shoud I have ' before and ' after the password and username. This is the error message:

# Example configuration.yaml entry
neviweb130:
  username: 'password'
  password: 'password'
  network: 'Économie'
  scan_interval: 360

** Failed to restart Home Assistant

The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: 'utf-8' codec can't decode byte 0xc9 in position 384: invalid continuation byte.

Here's my full configuration.yaml also with username and password replaced by password... Maybe it's the french name that cause my issue... I will try...

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
neviweb130:
  username: 'password'
  password: 'password'
  network: 'Économe'
  scan_interval: 360

**Comment by CoOlSlY007** [comment]
For others, that was it...

**Comment by claudegel** [comment]
Just remove the accent on Économe -> Econome

**Comment by claudegel** [comment]
let me know if this work as I'm gonna update the readme.md

**Comment by CoOlSlY007** [comment]
It works with just removing the "É" so that was indeed the problem... I searched a lot (well, about two hours) before writing I was out of solutions... It's now "Maison" but yes, just mention that it doesn't support accentued characters. Bon module Claude.

**Comment by claudegel** [comment]
I've added a note for accented character in the readme.md
Can you tel me if you remove the accent in configuration.yaml but leave it in neviweb, does it work ?

**Comment by CoOlSlY007** [comment]
I tried two things for helping you out on this: 
- Removing the "É" from the configuration.yaml but leaving it in Neviweb app made the module not working
- I also tried, just completely removing the line with the Network in the module and it worked by taking the first that the module founds
