### ISSUE TITLE
Difficulté à installer Neviweb sur Home Assistant

### ISSUE THREAD

**Issue by MonsieurDomo** [claudegel/sinope-130#206]
Bonjour Claude

Je suis un nouvel utilisateur de Home Assistant depuis les fêtes. J'ai réussi à installer beaucoup d'équipements et tout fonctionne bien sauf Neviweb. Je n'arrive pas malgré toutes les explications dans Home Assistant Neviweb130 Custom Components. 

Neviweb fonctionne super bien. J'ai un Home Assistant Green. J'ai la clef Zigbee Skyconnect. Elle est installée dans mes appareils. J'ai installé l'intégration à partir de HACS.  Je ne connaissais pas la façon d'écrire sur la configuration yaml et j'ai installé le module complémentaire File Editor. 

Je suis rendu à écrire la configuration yaml 
neviweb130:
  username: '«your Neviweb username»'
  password: '«your Neviweb password»'
  network: '«your gt130 location name in Neviweb»' (gt130 emplacement dans Neviweb)
  network2: '«your second location name in Neviweb»' (2e emplacement)
  scan_interval: 360
  homekit_mode: False
  stat_interval: 1800

Mes questions: network vous dites l'adresse en haut de la première page Neviweb. Est-ce que c'est l'adresse web qui ressemble à ceci? neviweb.com/locations/-----/dashboard

Merci à l'avance!
Je vous ai payé deux cafés pour votre service!! ;)

**Comment by MonsieurDomo** [comment]
Autre question? Est-ce que vous donneriez un cours privé pour moi, je vous payerais pour une heure ou deux. Je suis de St-Antoine-sur-Richelieu, pas très loin de Varennes. Je me rendrais soit chez-vous ou dans un Tim Horton à Varennes.

**Comment by claudegel** [comment]
Bonjour, c'est pas bien compliqué il faut juste respecter le formattage yaml
```
neviweb130:
  username: !secret climate_username
  password: !secret climate_password
  network: !secret climate_gateway130
  scan_interval: 360
  stat_interval: 600
```
Network c'est le nom de votre emplacement dans Neviweb au haut de la page d'accueil après s'être connecté.
![console](https://github.com/claudegel/sinope-130/assets/4268938/7f793794-6366-4ebb-8d32-2493c10bbf2b)
Dans la configuration je remplace les trois premiers parametres par !secret climate_username etc et je place ces trois paramètres dans le fichier secrets.yaml comme ceci:
```
climate_username: 'moi@ici.com'
climate_password: 'qwerty'
climate_gateway130: 'emplacement'
```
Il faut garder les apostrophes 'xxx'

**Comment by MonsieurDomo** [comment]
Ok merci c'est fait, je viens de comprendre mon erreur. Pas évident à comprendre comment se passe cette programmation yaml. Je n'arrive pas à assimiler vos explications car je n'ai jamais travailler avec le yaml et je ne connais pas assez le File Editor.

Là j'essaie de comprendre comment afficher les thermostats mais je vais m'organiser, ça fait juste trois semaines que j'essaie de les faire apparaitre sur mon Dashboard. Je vais essayer de trouver des explications comment fonctionne le yaml sur Youtube.  Merci et je trouve que vous travaillez fort dans vos recherches dans community.home-assistant.io/t/sinope-line-voltage-thermostats.

**Comment by MonsieurDomo** [comment]
J'ai trouvé, merci encore!

**Comment by claudegel** [comment]
Pour ajouter les thermostats vous les trouverez dans outils de développement / états.
Dans neviweb130, ils portent le nom «climate.neviweb130_climate_nom_de_votre_thermostat_dans_neviweb»
Pour les ajouter au dashboard, aperçu, vous avez trois petits points à la verticale dans le coin supérieure droit. Sélectionnez modifier le tableau de bord. puis ajoutez une carte de thermostat. 
Si vous avez d'autres questions ne vous gênez pas.

**Comment by MonsieurDomo** [comment]
Oui merci j'avais réussi. Je croyais qu'il fallait une programmation yaml pour ajouter les thermostats, c'était beaucoup plus simple que je le croyais.

**Comment by claudegel** [comment]
Pour la suite pour vos automation vous pouvez regarder le composant Scheduler component qui s'install via HACS.
Ca rend les automation super facile à configurer.
je vais fermer cet issue mais vous pouvez toujours la réouvrir si vous avez d'autres questions.
