### ISSUE TITLE
New option for backlightAdaptive attribute

### ISSUE THREAD

**Issue by visto9259** [claudegel/sinope-130#207]
Neviweb has a 3rd option for the backlightAdaptive attribute called "bedroom".

As a minimum, it is available for TH1123ZB-G2/TH1124ZB-G2 devices as this is what I have.  Their firmware version is 0.1.3

From Neviweb:

![image](https://github.com/claudegel/sinope-130/assets/7890483/a111baf3-1c83-46d7-8f0d-c3ddbd59d9d2)

The payload for the request to set the mode to bedroom:

![image](https://github.com/claudegel/sinope-130/assets/7890483/9d62ba02-ca30-468d-8987-3be562b3af7a)

The _neviweb130.set_backlight_ service needs to include this 3rd option.

**Comment by visto9259** [comment]
Additional info from Sinopé on this option:
![image](https://github.com/claudegel/sinope-130/assets/7890483/e932d91b-55d8-41b8-8d6b-045fd37a2eae)

**Comment by claudegel** [comment]
la troisième option du lock keypad était déjà présente pour les gradateur et interrupteurs. je vais l'ajouter pour les thermostats et les switch. Pour le backlight ça fonctionne les G2 et les wifi mais pas pour les zigbee 1er génération ni les thermostats de plancher.
Je vais tester et faire le ménage en fin de semaine. Merci de m'avoir rapporter ces nouveaux attribut.

**Comment by claudegel** [comment]
J'ai tout ajouté dans la version 2.6.0 en pre-release avec des correction dans la version 2.6.1
