### ISSUE TITLE
Sinope Sedna 5 water valve kit

### ISSUE THREAD

**Issue by mattpepin** [claudegel/sinope-130#208]
Hi,
Your extension seems to be what I need. Before buying this kit:

https://www.sinopetech.com/en/product/sedna-smart-water-damage-protection-kit-2nd-gen-wi-fi/

Can you confirm that the extension works using this Wifi valve and that I don't need anything else (another device) to make it work? I'm not sure if I need a Zigbee gateway (the GT130 mentioned many times for other devices).

Thanks :)

**Comment by claudegel** [comment]
Hi, if your valve is a wifi valve you don't need to buy a GT130. The valve use the wifi to connect to Neviweb and act as a zigbee gateway for the water Leak sensor.
Neviweb130 will detect it when connected to Neviweb and you'll be able to control it.
As I'm launching a new neviweb130 version this weekend I'm looking for wifi owner to test that part of the code as I don't have any wifi device at the moment. But it should work without problem.

**Comment by mattpepin** [comment]
Thanks! I will buy it, and gladly test the code!
