### ISSUE TITLE
Received gateway data: {'error': {'code': 'VALINVLD',

### ISSUE THREAD

**Issue by mtrudel-e3k** [claudegel/sinope-130#21]
Hi Claude
I am trying to test your integration in HA.
I fail to set it up properly.
I get error 
DEBUG (SyncWorker_1) [custom_components.neviweb130] Received gateway data: {'error': {'code': 'VALINVLD', 'data': {'value': None, 'name': 'location$id'}}}
2020-12-29 16:04:34 ERROR (MainThread) [homeassistant.setup] Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/__init__.py", line 41, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
  File "/config/custom_components/neviweb130/__init__.py", line 64, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network)
  File "/config/custom_components/neviweb130/__init__.py", line 100, in __init__
    self.__get_gateway_data()
  File "/config/custom_components/neviweb130/__init__.py", line 175, in __get_gateway_data
    data = self.get_device_attributes(device["id"], [ATTR_SIGNATURE])
TypeError: string indices must be integers

I set this config
neviweb130:
  username: 'xxxxx'
  password: 'xxxx'
  network: ''
  scan_interval: 360

For network I dont know what to put. In french, I did not find the term "Reseau" anywere in Neviweb.
I have a GT130 name that is GT130 too.
My "Location/Emplacement" name is Zigbee
But nothing that says "network/réseau"

it did connect to Neviweb correctly.
2020-12-29 15:43:57 DEBUG (SyncWorker_1) [custom_components.neviweb130] Login response: {'user': {'id': xxxxx, 'role': 'owner', 'email': 'xxxxxxxxxxxxx', 'locale': 'fr', 'format': {'time': '24', 'temperature': 'c'}, 'initialized': 1}, 'account': {'id': xxxxx, 'interface': 'neviweb', 'type': 'free'}, 'iat': 9999999999999999999999, 'session': '79c4223423453daa407d9e36a8fddfsfsdfs33dcb7739bb8618', 'refreshToken': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'}
2020-12-29 15:43:57 DEBUG (SyncWorker_1) [custom_components.neviweb130] Successfully logged in

OK
I figured it out ... though I thought it was the first thing I tried ... seems not.

"Network" in the configuration is called "Location or Emplacement" in Neviweb. Not "Network"
I put the Location name "Maison" in the "Network"  in the configuration file and now it detected all my devices.

Claude maybe you can add a more descriptive message if the "Network" is wrong.
See the "Received gateway data: " message above.
Contrary to what the documentation says, leaving Network to '' in the configuration did not work in my situation. Look at the log above to see what Neviweb returned

**Comment by mtrudel-e3k** [comment]
Issue with TH1500ZB. Neviweb reports the Family to be 737-DP and not 1500.

So as a temporary patch I deactivated the IF in climate.py that checks implemented devices.
With this IF disabled, the TH1500ZB shows in HA.
I tried to add the 737-DP this way DEVICE_MODEL_HEAT = [1123, 1124, 1500, '737-DP'] but it had no effect.

Here is my temporary code.
`async def async_setup_platform(hass, config, async_add_entities, discovery_info=None):
    """Set up the neviweb130 thermostats."""
    data = hass.data[DOMAIN]

    devices = []
    for device_info in data.neviweb130_client.gateway_data:
       # if "signature" in device_info and \
       #     "model" in device_info["signature"] and \
       #     device_info["signature"]["model"] in IMPLEMENTED_DEVICE_MODEL:
            device_name = "{} {}".format(DEFAULT_NAME, device_info["name"])
            devices.append(Neviweb130Thermostat(data, device_info, device_name))

    async_add_entities(devices, True)

Being totally new to HA, I have no clue how to properly fix this.
Adding your integration was my VERY first step after installing HA.

`

**Comment by claudegel** [comment]
Ok first you were missing the network parameter. It's the name you have set in Neviweb for your GT130 zigbee devices.It's the Location name (Emplacement). I'll add more info in debug message for this. So in your HA config you will have:
```
neviweb130:
  username: !secret climate_username
  password: !secret climate_password
  network: !secret climate_gateway130 <---- you can remove completely this line if you have only one location in Neviweb
  scan_interval: 360
```
The !secret climate_username etc is for more security. those parameter are placed in the file secrets.yaml in config dir.
```
climate_username: 'me@my.place'
climate_password: '12345'
climate_gateway130: 'Location'
```
In configuration.yaml add this at the end
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
Then restart HA.
You will find all debug in file home-assistant.log

For your devices it is not the family I need but the model. I see in your log those model number
`Received signature data: {'signature': {'model': 1123,`
1123 is for TH1123ZB
2600 is for SP2600ZB
5051is for WL4200ZB
2121 is for SW2500ZB
2131 is for DM2500ZB
130 is for your GT130
2506 is for RM3250ZB
7373  <----- should be the TH1500ZB ?

so in climate.py just replace 1500 by 7373 and it should work

**Comment by claudegel** [comment]
Next step will be to sniff some information when you connect to Neviweb to check all parameter exchanged between you browser and Neviweb for your TH 1500ZB. If needed I'll add more code in my neviweb130 to take care of every parameter

**Comment by mtrudel-e3k** [comment]
Hi Claude
I added 7373 to the climate.py file and reactivated the IF. It works fine now. the TH1500ZB is properly detected by the IF
I also made the following change.
I did not like the fact that each device name was prefixed with "neviweb130 devicetype" so I added some constants to let users decide of the prefixes.

const.py
# Added by Marc Trudel and used in each .py file
# replaced hard coded DEFAULT_NAME in each .py file
# this change let the user decide of the prefix automatically added to each devices name.
# You may leave each prefix empty if desired.
ATTR_DEVICE_NAME_PREFIX_CLIMATE = "Thermostat"
ATTR_DEVICE_NAME_PREFIX_LIGHT = "Light"
ATTR_DEVICE_NAME_PREFIX_DIMMER = "Dimmer"
ATTR_DEVICE_NAME_PREFIX_SENSOR = "Sensor"
ATTR_DEVICE_NAME_PREFIX_SWITCH = "Switch"

climate.py
from .const import (DOMAIN, ATTR_SETPOINT_MODE, ATTR_ROOM_SETPOINT,
    ATTR_OUTPUT_PERCENT_DISPLAY, ATTR_ROOM_TEMPERATURE, ATTR_ROOM_SETPOINT_MIN,
    ATTR_ROOM_SETPOINT_MAX, ATTR_WATTAGE, ATTR_GFCI_STATUS, ATTR_FLOOR_MODE, MODE_AUTO, MODE_AUTO_BYPASS, 
    MODE_MANUAL, MODE_OFF, MODE_AWAY, ATTR_FLOOR_AUX, ATTR_FLOOR_OUTPUT2, ATTR_KEYPAD, ATTR_WIFI_FLOOR_OUTPUT1,
    ATTR_WIFI_WATTAGE, ATTR_WIFI, ATTR_WIFI_DISPLAY2, ATTR_WIFI_KEYPAD
	
	**,ATTR_DEVICE_NAME_PREFIX_CLIMATE	# 2020-12-30 MT**
	)

_LOGGER = logging.getLogger(__name__)

SUPPORT_FLAGS = (SUPPORT_TARGET_TEMPERATURE | SUPPORT_PRESET_MODE)

DEFAULT_NAME = **ATTR_DEVICE_NAME_PREFIX_CLIMATE	#"neviweb130 climate"** 

I did the same for each .py file.
for light.py I did...
added to .const
	ATTR_DEVICE_NAME_PREFIX_LIGHT,ATTR_DEVICE_NAME_PREFIX_DIMMER	# 2020-12-30 MT

            device_name = '{} {} {}'.format(
				'', # 2020-12-30 MT DEFAULT_NAME, 
				
				# 2020-12-30 MT Below, replaced literal with const ATTR_DEVICE_NAME_PREFIX_xxxxx
                ATTR_DEVICE_NAME_PREFIX_DIMMER if device_info["signature"]["model"] in DEVICE_MODEL_DIMMER 
                else 
				ATTR_DEVICE_NAME_PREFIX_LIGHT, device_info["name"])

You may implement these changes in your code they way you want.
You may drop my comments and make these changes yours.

**Comment by claudegel** [comment]
Hi Marc. I'll check your idea of personalized prefix name this weekend. It sound good but I need to check that if we change the prefix it could affect device list in HA. For those people who have many devices already in HA it could be complicated to go over all there automation to make the name change. So we should keep the default prefix but add the possibility to change it if we want. Having the users dig in the code to change the prefix is not the preferred way. But I thing we can have some optional parameters in configuration.yaml to overwrite the default prefix name.
The devices name is use in background by HA and you still have the possibility to change the devices name in the front end by changing the friendly name of each devices.
I'm happy that the TH1500ZB work. If you could, can you check with your browser when you're logged in Neviweb. Open the browser debug console and send me the parameter list that is sent by the browser to Neviweb when you are in the configuration of your TH1500ZB device. It will give me all the parameters that I need to manage in neviweb130 to fully support  that thermostat.
If you are using Firefox then, once in Neviweb, just hit «Ctrl Maj K» to open the console at the bottom of the screen. you will see all the trafic exchanged to and from Neviweb. Each line is a request that you can open tosee the parameter s sent to Neviweb and the answer received from Neviweb. This way I'll be able to fine tune neviweb130 for your TH1500ZB

**Comment by claudegel** [comment]
I've done a new release with TH1500ZB support included

**Comment by mtrudel-e3k** [comment]
Hi Claude
I use Chrome and am not used to debug mode.
Here is the info I could retrieve

Does it help ?

Request URL: https://neviweb.com/api/device/134752/attribute?attributes=roomTemperature,outputPercentDisplay,roomSetpoint
Request Method: GET
Status Code: 200
Remote Address: xxx.xxx.xxx.xxx:xxx
Referrer Policy: strict-origin-when-cross-origin
content-encoding: gzip
content-type: application/json
date: Sun, 03 Jan 2021 22:03:33 GMT
server: nginx/1.16.1
session-id: 7ea7abc28a15c4ce280a5eab032c3c67af8f0dd6f020a245
strict-transport-security: max-age=31536000; includeSubDomains
:authority: neviweb.com
:method: GET
:path: /api/device/134752/attribute?attributes=roomTemperature,outputPercentDisplay,roomSetpoint
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: e





Marc Trudel, B.Sc.A.  •  Associé
514 316.6650, poste 210 •  e3k.co<http://blapriseae3k.co/>

**Comment by claudegel** [comment]
Hi  Marc,The line I need is attributes....You have the three basic one, roomtemperature, roomsetpoint and outputpercentdisplayTo get the other one, go into your device and open the configuration, the gear button.You will get more attributes.This is what I needClaudeClaude Gelinas agr.Phyto Ressources inc
-------- Message d'origine --------De : mtrudel-e3k <notifications@github.com> Date : 21-01-03  5 h 14 p.m.  (GMT-05:00) À : claudegel/sinope-130 <sinope-130@noreply.github.com> Cc : Claude Gelinas <claude@phyto.qc.ca>, State change <state_change@noreply.github.com> Objet : Re: [claudegel/sinope-130] Received gateway data: {'error': {'code': 'VALINVLD', (#21) 

Hi Claude



I use Chrome and am not used to debug mode.



Here is the info I could retrieve







Does it help ?







Request URL: https://neviweb.com/api/device/134752/attribute?attributes=roomTemperature,outputPercentDisplay,roomSetpoint



Request Method: GET



Status Code: 200



Remote Address: xxx.xxx.xxx.xxx:xxx



Referrer Policy: strict-origin-when-cross-origin



content-encoding: gzip



content-type: application/json



date: Sun, 03 Jan 2021 22:03:33 GMT



server: nginx/1.16.1



session-id: 7ea7abc28a15c4ce280a5eab032c3c67af8f0dd6f020a245



strict-transport-security: max-age=31536000; includeSubDomains



:authority: neviweb.com



:method: GET



:path: /api/device/134752/attribute?attributes=roomTemperature,outputPercentDisplay,roomSetpoint



:scheme: https



accept: application/json, text/plain, */*



accept-encoding: gzip, deflate, br



accept-language: e























Marc Trudel, B.Sc.A.  •  Associé



514 316.6650, poste 210 •  e3k.co<http://blapriseae3k.co/>
