### ISSUE TITLE
This entity is no longer being provided by the neviweb130 integration. If the entity is no longer in use, delete it in settings.

### ISSUE THREAD

**Issue by CoOlSlY007** [claudegel/sinope-130#220]
I have this since about a week. I updated HACS, updated HA. No clue where to start from, I don't see anything anywhere that can help me out finding where's the source of the problem.

**Comment by claudegel** [comment]
I presume it is a valve that is missing. It is because now the valve are now supported as a new valve entity. before it was supported as a switch.
Make sure you update neviweb130 via HACS and have HA version 2024.1 or newer.
Then look in dev tools / states and search for entity valve.neviweb130_valve_name of your valve
before your valve was in switch.neviweb130_switch_name of your valve.

**Comment by CoOlSlY007** [comment]
Salut Claude,

Those are wifi regular Sinope thermostat. I just have this error message. Where would I be able to find the log to check the details of the problem?

**Comment by claudegel** [comment]
Add this in configuration.yaml and restart HA. You will have more verbose log
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```

**Comment by claudegel** [comment]
After check in your log for lines containing 
[custom_components.neviweb130] Received gateway data:...
Then you should have this line, one for each device
[custom_components.neviweb130] Received signature data:....
Then one line of this for each climate device
[custom_components.neviweb130.climate] Setting up neviweb130 climate name of your thermostat
Then for each thermostat this line which get all thermostats attribute
[custom_components.neviweb130.climate] Updating neviweb130 climate name of your thermostat

**Comment by CoOlSlY007** [comment]
Claude ... For an experienced guy in IT, I made a rookie mistake... I changed the password about a month ago, when I opened configuration.yaml, first thing I checked was the password and saw it was not matching :|

**Comment by CoOlSlY007** [comment]
Claude ... For an experienced guy in IT, I made a rookie mistake... I changed the password about a month ago, when I opened configuration.yaml, first thing I checked was the password and saw it was not matching :|

**Comment by claudegel** [comment]
Can you send me the log line for your thermostat as they are wifi and I need to check if all attributes are correctly added to HA
Please send me the line containing:
`[custom_components.neviweb130.climate] Updating neviweb130 climate name of your thermostat`
For each thermostatmodel you have
Thank you

**Comment by CoOlSlY007** [comment]
As I said, the password was the problem, everything is back to normal :)

**Comment by claudegel** [comment]
I know that the issue is cleared but if possible, I would appreciate to receive the lines from your log about each or your wifi devices. The lines I'M looking for contain that text:
`[custom_components.neviweb130.climate] Updating neviweb130 climate «name of your thermostat»....`
Those lines show all the attributes and sub-attributes received from Neviweb for each of your devices. This can help me to make sure I didn't miss something as I don't have wifi devices to test.

**Comment by sicarriere** [comment]
@claudegel 

Here mine [Model 1510 - TH1123WF]:

`2024-02-13 12:11:41.092 DEBUG (SyncWorker_23) [custom_components.neviweb130.climate] Updating neviweb130 climate Salon (1.21 sec): {'drStatus': {'drActive': 'off', 'optOut': 'off', 'setpoint': 'off', 'powerAbsolute': 'off', 'powerRelative': 'off', 'onOff': 'off'}, 'outputPercentDisplay': {'percent': 100, 'sourceType': 'heating'}, 'roomSetpoint': 21, 'roomTemperatureDisplay': {'status': 'on', 'value': 21}, 'temperatureFormat': 'celsius', 'setpointMode': 'manual', 'drSetpoint': {'status': 'off', 'value': None}, 'roomSetpointMax': 30, 'roomSetpointMin': 5, 'roomTemperature': {'error': None, 'value': 21.04}, 'timeFormat': '24h', 'cycleLength': 15, 'loadWattOutput1': 1869, 'loadWatt': 1869, 'wifiRssi': -46, 'keyboardLock': 'unlock', 'config2ndDisplay': 'default', 'occupancyMode': 'none', 'backlightAutoDim': 'alwaysOn', 'earlyStartCfg': 'off', 'roomSetpointAway': 15}
`

**Comment by claudegel** [comment]
Thnak you I got few more attributes to add for that thermostat. I'll create a new branch for you to test if everything is OK. I'll let you know when it is ready to test

**Comment by CoOlSlY007** [comment]
Claude do you still want mine I am out of the country until Thursday but can also make you a cut and paste of my logs if you need them

**Comment by sicarriere** [comment]
climate.py updated, no error so far.

**Comment by claudegel** [comment]
I just need to check if this can affect TH1500WF thermostat as they share the same code. But I think it will be ok
If you have a TH1500WF it could be good for me to get the update data

**Comment by claudegel** [comment]
It's ok I'make a release this weekend. Thank you
