### ISSUE TITLE
Tout mes entity de thermostat sont devenue indisponible

### ISSUE THREAD

**Issue by gobol007** [claudegel/sinope-130#221]
suite à la mise à jour 2.6.2 à 2.6.4... plus aucune de mes entité de thermostat était disponible...j'ai dû retourné à la version 2.6.1 pour que le tout refonctionne....

**Comment by claudegel** [comment]
Quel thermostat vous avez

**Comment by claudegel** [comment]
Y-a-t'il des erreurs dans vos log de HA

**Comment by gobol007** [comment]
oui, mais j'ai pas fait de printscreen... et j'ai retourné en 2.6.1, donc j'ai perdu les logs (du moins je ne les vois plus) mais de mémoire ça disait que le plugin neviweb130 était incapable de trouver les fichier de configuration et du coup le plugin ne pouvait pas redémarrer... j'ai essayer la version 2.6.2, 2.6.3, 2.6.4, avec le même résultat

**Comment by claudegel** [comment]
Comment vous faites les mises a jour ? via HACS

**Comment by claudegel** [comment]
si vous pouvez réinstaller 2.6.4 ou la dernière 2.6.5 après le démarrage de HA vous pouvez renommer le fichier log et réinstaller la version 2.6.1. Ainsi vous ne perdrez pas les log

**Comment by gobol007** [comment]
Oui je fait les mise à jour via HACS... je vais essayer de réinstaller la 2.6.5... Je vous donne le résultat

**Comment by gobol007** [comment]
Bon mise à jour 2.6.4 (j'ai pas vu la 2.6.5)
Avec la version 2.6.1  --------------------
![V2 6 1_2](https://github.com/claudegel/sinope-130/assets/8069819/878caff8-58b7-4932-84ea-a368f21c6b1c)

Avec la version 2.6.4 ---------------------
![V2 6 1_3](https://github.com/claudegel/sinope-130/assets/8069819/9b7650c2-b690-4261-8aaa-8dba0bb1ba32)
![V2 6 4_2](https://github.com/claudegel/sinope-130/assets/8069819/8402d29a-28ee-44c9-8caa-30831a773ae8)
![V2 6 4_3](https://github.com/claudegel/sinope-130/assets/8069819/63e8477d-ec98-4bb7-8485-97202d92320c)
![V2 6 4_4](https://github.com/claudegel/sinope-130/assets/8069819/a1acca47-4092-42cc-a384-1499d2fa80cb)


Donc voilà... espérons que ça te dise quelque chose... :)

**Comment by sicarriere** [comment]
@gobol007 Quelle version de HA as-tu? Car l'attribut "TURN_ON" et "TURN_OFF" de la plateforme "Climate" a été introduit dans HA 2024.2, donc si tu es à 2024.1.x et moins, alors, tu auras l'erreur. Mets à jour ton HA, et ça devrait être OK.

**Comment by gobol007** [comment]
Effectivement j'ai la version 2024.1.6.... je met à jour et je te reviens

**Comment by gobol007** [comment]
Effectivement avec la version de HA à 2024.2.1...et la version 2.6.5  tout est revenu à la normal

MERCI !!

**Comment by claudegel** [comment]
Bonne chose. Faudrait que je trouve comment valider la version de HA minimum avant de faire une mise a jour de neviweb130 pour envoyer une notification en cas d'incompatibilite.
