### ISSUE TITLE
DM2500ZB does not turn off.

### ISSUE THREAD

**Issue by egoleos** [claudegel/sinope-130#224]
I notice strange behavior. I can turn on DM2500ZB and adjust the brightness, but it doesn't respond to the turn-off command. What's odd is that after issuing the turn-off command on the neviweb.com page, it shows that the device is off, but in reality, the lights are still on.

**Comment by claudegel** [comment]
I've tested on neviweb.com. If I turn_on light from neviweb the light turn on. If I turn_off the light it effectively turn off and both action are updated in HA.
If I turn_on the light in HA the light turn on and in Neviweb also the light is on.
If I turn_off the light in HA. HA say it is off, Neviweb say it is off. but the light is still on.
Is it the same for you

**Comment by claudegel** [comment]
Ok found it. Look like Neviweb change something in the way it handle dimmer. We just need to send onOff: "off" to turn off the dimmer.Before we need to send both onOff and intensity.
I'll make a patch and let you know when it is ready to test

**Comment by claudegel** [comment]
You can test by downloading file light.py from
https://github.com/claudegel/sinope-130/tree/Bug-fix/custom_components/neviweb130
Please if you have also SW2500 test on them also. On my side it work for DM2500 and DM2550.

**Comment by egoleos** [comment]
Thank you for the lightning-fast fix of the issue; everything works correctly on my DM2500ZB now.
