### ISSUE TITLE
Setting up Energy Card

### ISSUE THREAD

**Issue by bsauve** [claudegel/sinope-130#228]
Bonjour,
je n'arrive pas à figurer la bonne façon de configurer les paramètres de la Card pour le suivie de l'énergie consommé par heure, jour, mois.

Tu suggères les deux templates suivant:
template:
  - sensor:
      - name: "Basement energy usage"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: >-
          {{ state_attr("climate.neviweb130_th1124zb_basement","hourly_kwh_count") }}
or:

template:
  - sensor:
      - name: "Basement energy usage"
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total
        state: >-
          {{ state_attr("climate.neviweb130_th1124zb_basement","hourly_kwh") }}

Mais quand on créer la Card,  qu'est-ce qu'il faut choisir entre Mean, Min, Max, Sum, State, Change ? 
J'ai l'impression des les paramètres son différent en fonction du template utilisé.
Dans aucun cas je n'arrive à avoir les mêmes chiffres que Neviweb.

Merci

**Comment by claudegel** [comment]
Quel card tu utilises

**Comment by bsauve** [comment]
J'ai pris la carte par défaut qui s'appelle Statistic Graph.
Voici l'image
![statGraphCard](https://github.com/claudegel/sinope-130/assets/87160404/c7ee6604-9a2d-489e-a0a4-1228a2e99d7d)

**Comment by bsauve** [comment]
Information supplémentaire, j'ai fait la configuration de l'onglet Energy de HA en haut à gauche.
Je configure un device avec le template "..._count" et les chiffres match exactement ceux de Neviweb130 sauf qu'ils sont décalé de 2h, Le chiffre de Neviweb130 de 16h match celui de HA de 18h. Mais mon Neviweb130 et HA sont dans la même time zone, i.e. GMT -5.

**Comment by claudegel** [comment]
J'ai testé la carte statistique graph card et ça semble etre des moyennes et non les directement valeurs recues de Neviweb.
Pour ce qui est des délais entre neviweb et HA, neviweb130 va chercher les data toutes les 30 minutes pour éviter qu'il y ait trop  de polling sur Neviweb. les valeurs qu'on récupère sont mis a jour par Neviweb au heures. Donc c'est possible qu'il y ait un décallage.

**Comment by bsauve** [comment]
ok merci.
