### ISSUE TITLE
Indication de chauffage erroné - TH1124ZB

### ISSUE THREAD

**Issue by gobol007** [claudegel/sinope-130#237]
Petit problème... mon thermostat indique qu'il chauffe constamment... mes 9 autres thermsotat TH1124ZB-G2 marche super bien... mon seul TH1124ZB indique qu'il chauffe constamment même si c'est pas vrai..... physiquement il ne chauffe pas. Même l'application Neviweb indique qu'il chauffe ? Problème avec une mise à jour Sinopé pour ce modèle ? J'ai fermer le courant pour le "reset"... rien n'y fait!. Il répond super bien à toute les commandes pourtant...

[image](https://github.com/claudegel/sinope-130/assets/8069819/ecd0e521-75c7-4f40-ac9d-2f8b0274206f)

**Comment by claudegel** [comment]
Si la même erreur se produit dans HA et dans Neviweb alors c'est un problème de thermostat.
Quel est la version du FW dans Neviweb. Il est possible qu'ils ont fait une mise a jour FW et qu'il y a un bug ou bien ils ont changé le nom d'un attribut.
Pour faire le reset il faut procéder ainsi:

Thermostats:

    Raise the temperature until the display change.
    Push the two button until CLR appear on the screen.
    Push once the upper button to get YES on the display.
    Push both button simutanously and release immediately. DONE should appear on the screen.
    The thermostat will restart with factory setup

**Comment by gobol007** [comment]
![25487](https://github.com/claudegel/sinope-130/assets/8069819/ced6150c-8cb2-4f7d-b0a8-a78ce23d6f7a)

**Comment by claudegel** [comment]
As-tu fais un reset comme decrit ci-haut ?

**Comment by gobol007** [comment]
non je fait ça aussitôt que j'Arrive à la maison :)... là il semble indiquer correctement... il semble très lent pour se rendre compte qu'il ne chauffe plus... quand le chauffe part il indique aussitôt qu'il chauffe... c'Est quand qu'il arrête qu'il prend un certain temps à indiquer qu'il ne chauffe plus

**Comment by claudegel** [comment]
Si je comprends bien, l'affiche sur le thermostat indique qu'il chauffe m[eme si il ne chauffe pas. M[eme chose sur Neviweb ou ca indique que le thermostat chauffe. Donc m[eme chose sur HA qui recoit l'info de neviweb.

C'est bien ca ?

**Comment by gobol007** [comment]
Exactement.... Et non pas encore reset... malheureusement ça va allez a
demain...mais tu décris bien le bug...

Le dim. 7 avr. 2024, 19 h 56, Claude Gelinas ***@***.***> a
écrit :

**Comment by gobol007** [comment]
Allo... bon après plusieurs jours de test... le problème semble résorbé... j'ai pas fait de reset.... je comprend pas trop, mais bon vous pouvez fermer le ticket :) Anyway je ne crois pas que le problème vienne de votre intégration :)

**Comment by claudegel** [comment]
Ok, si ça revient ou si vous trouvez d'autres informations vous pourrez toujours réouvrir le ticket.
