### ISSUE TITLE
Deprecated Warining: neviweb130 implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity

### ISSUE THREAD

**Issue by horspiste** [claudegel/sinope-130#238]
I am getting this warning on Home Assistant, 2024.4.1, the deprecated feature will stop woking in version 2024.10.0

neviweb130::Neviweb130FloorThermostat implements the `is_aux_heat` property or uses the auxiliary heater methods in a subclass of ClimateEntity which is deprecated and will be unsupported from Home Assistant 2024.10. Please report it to the author of the 'neviweb130' custom integration

**Comment by claudegel** [comment]
Yes HA has flag is_aux_heat, turn_aux_heat_on and turn_aux_heat_off property and method to be removed from the climate entity. I'm working on an update to switch aux heat to emergency heat function. This should come this week, ready to be tested by volunteer.

**Comment by horspiste** [comment]
I can test that it doesn't give the warning anymore but my sinope thermostats don't have aux hear/emergency heat features.

**Comment by claudegel** [comment]
You get that deprecated warning because the neviweb130 app have those attribute and methods. Low voltage and floor thermostats have aux heat option. regular thermostats don<t have aux heat

**Comment by claudegel** [comment]
I've created a branch that fix the is_aux_heat warning. You can test by downloading the files here:
https://github.com/claudegel/sinope-130/tree/aux_heat_fix/custom_components/neviweb130

**Comment by horspiste** [comment]
I tried to install it via HACS but it doesn't show, even if I enable "show
beta versions".

**Comment by claudegel** [comment]
I'm gonna put it in a beta version tonight

**Comment by claudegel** [comment]
Ok I've set a beta version v2.7.3. You should be able to install via hacs

**Comment by horspiste** [comment]
I've installed 2.7.3 via HACS and so far all seems ok. No warning in log
and my Sinope devices show properly in the dashboard.

Thank you!

Sylvain

**Comment by claudegel** [comment]
Ok thank you. Let me know if you find a bug
