### ISSUE TITLE
Unable to add RM3500WF

### ISSUE THREAD

**Issue by ldupont226** [claudegel/sinope-130#242]
Bonjour Claude, je doit commencer par te remecier pour l'excellent travail que tu fais,
Je viens d'acheter un RM3500WF et il ne s'ajoute pas à Home Assistant. J'ai 9 thermostats qui se sont très bien ajoutés mais pas ce module. Je remarque  dans le code du fichier switch.py, il indique mode : 2150 et le model de mon unité est 2152 je ne sais pas si c'est la raison. je ne connait rien à Pyton. 
J'ai redémarré Home assistant à plusieur reprise, j'ai essayé la version 2.7.2 et 2.7.4. j'ai tenté de remplacer et changer le model 2150 par 2152 dans le fichier switch.py, sans succès  
![RM3500WF](https://github.com/claudegel/sinope-130/assets/33640780/37e31b1b-a8ee-4d09-b619-62a4fe785302)

**Comment by claudegel** [comment]
Effectivement c'est la raison. Ce produit est nouveau et Il fallait que quelqu'un l'achète pour me le dire le numéro de model
Donc il faut remplacer la ligne 224 de switch.py parle bon numero de model, 2152
`IMPLEMENTED_WIFI_WATER_HEATER_LOAD_MODEL = [2152]`
Sinon j'ai créer une branche avec la correction:
https://github.com/claudegel/sinope-130/tree/wifi-calypso/custom_components/neviweb130
Simplement copier le fichier switch.py et remplacer celui qui se trouve dans config/custom_components/neviweb130 puis redémarrer HA

**Comment by ldupont226** [comment]
Merci Claude pour ta réponse aussi rapide,
J'ai remplacer le nouveau fichier et il n'apparait pas dans mes entités en filtrant sur sinope,
Y a t'il un autre endroit ou je dois regarder ?
merci et bonne nuit

**Comment by ldupont226** [comment]
Je ne sais pas s'il y a un lien mais j'ai trouvé ceci dans les logs:

Enregistreur: homeassistant.components.switch
Source: helpers/entity_platform.py:707
intégration: Commutateur (documentation, problèmes)
S'est produit pour la première fois: 19 avril 2024 à 23:43:21 (1 occurrences)
Dernier enregistrement: 19 avril 2024 à 23:43:21

neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 707, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1270, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/switch.py", line 1303, in update
    self._drstatus_optout_reason = device_data[ATTR_DRSTATUS]["optOutReason"]
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'optOutReason'

**Comment by claudegel** [comment]
Ok j'ai enlevé la ligne 1303 pour optOutReason. Ca va passer. Simplement copier switch.py de la branche wifi-calypso
SVP publis la ligne de log contrnant ceci:
[custom_components.neviweb130.switch] Updating neviweb130 switch nom de ton RM3500WF.....
Ca va me donner la liste des attributs recu de Neviweb pour ton Calypso pour me permettre de faire les ajustement.

**Comment by ldupont226** [comment]
Avec le nouveau fichier, mon unité est apparu.
Je ne vois pas de log dans systeme/journaux contenant custum_component.neviewweb......., ou dois-je regarder
mais je recuillis les info suivante dans Etats:
onOff: on
Wattage: 
value: 3867

Wattage_instant: 
value: 808

Water_leak_status: ok
Water_leak_disconect_status: ok
Water_leak_closure_config: enabled
Water_temperature: 56.64
Cold_load_pickup_status: inactive
Cold_load_remaining_time: null
Cold_load_temperature: 100
Tank_size: 60 gal
Temperature_status: null
Stm_Mcu: null
Thermal_overload: null
Current_overload: null
j2Connector: null
j3Connector: null
Line_error: null
eco_status: off
eco_optOut: off
eco_onoff: off
eco_optout_reason: off
Water_temp_min: 45
Water_time_on: 30
Water_temp_time: 120
Away_action: 
action: none
actionPayload: none

Mode: manual
Leg_status: 
temperature: ok
consumption: ok
consumptionOverTime: ok

Rssi: -40
sku: RM3500WF
device_model: 2152
device_model_cfg: 0
firmware: 1.0.0
Activation: true
device_type: power
id: 532671
device_class: switch
icon: mdi:switch
friendly_name: neviweb130 switch Chauffe Eau

**Comment by claudegel** [comment]
Il faut mettre ceci dans configuration.yaml puis redémarrer HA
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
les info vont apparaitres dans le fichier home-assistant.log

**Comment by ldupont226** [comment]
Je t'ai transmis à ton courriel , je n'aime pas publier tout les Mac address

**Comment by claudegel** [comment]
Ok reçu, je regarde ça aujourd'hui
Merci,

**Comment by claudegel** [comment]
Voila j'ai terminé la mise a jour pour le RM3500WF
simplement remplacer le fichier switch.py et tester

Merci,

**Comment by ldupont226** [comment]
mise à jour du fichier fait en tirant du répertoire /sinope-130/tree/wifi-calypso/custom_components/neviweb130
démarrage sans probleme 
Est ce normal qu'il n'y ait pas de  hourly_kwh_count, daily_kwh_count, monthly_kwh_count...?
 

onOff: on
Wattage: 3867
Wattage_instant: 0
Water_leak_status: ok
Water_leak_disconect_status: ok
Water_leak_closure_config: enabled
Water_temperature: 56.3
Cold_load_pickup_status: inactive
Cold_load_remaining_time: null
Cold_load_temperature: 100
Tank_size: 60 gal
Temperature_status: null
Stm_Mcu: null
Thermal_overload: null
Current_overload: null
j2Connector: null
j3Connector: null
Line_error: null
eco_status: off
eco_optOut: off
eco_onoff: off
eco_setpoint: off
eco_power_absolute: off
eco_power_relative: off
Water_temp_min: 45
Water_time_on: 30
Water_temp_time: 120
Away_action: none
Away_action_payload: none
Mode: manual
Leg_status_temperature: ok
Leg_status_consumption: ok
leg_status_consumption_over_time: ok
Rssi: -42
sku: RM3500WF
device_model: 2152
device_model_cfg: 0
firmware: 1.0.0
Activation: true
device_type: power
id: 532671
device_class: switch
icon: mdi:switch
friendly_name: neviweb130 switch Chauffe Eau

**Comment by claudegel** [comment]
Non faut juste L'ajouter. prochaine étape
je suppose que ce doit être la même chose que pour le Calypso zigbee.
Je vais regarder ça

**Comment by ldupont226** [comment]
Merci Claude,
Avec le correction que tu as faitpour le moment ça fonctionne beaucoup mieux que hier,
j'apprécis le travail très rapide que tu as fait.
Fais moi signe, si tu veux que je teste quand tu ajouteras les attributs.

merci

**Comment by claudegel** [comment]
Voila je les ai ajouté... à tester switch.py

**Comment by ldupont226** [comment]
Pour le moment ils sont intégré mais à null, probablement mis à jour au prochain cycle.
je te fait signe quand j'ai des chiffres

hourly_kwh_count: null
daily_kwh_count: null
monthly_kwh_count: null
hourly_kwh: null
daily_kwh: null
monthly_kwh: null

**Comment by ldupont226** [comment]
WOW good, une vraie machine
merci beaucoup
pour les mois je croix que c'est normal, je l'ai depuis èà peine 2 jours

hourly_kwh_count: 22.811
daily_kwh_count: 14.235
monthly_kwh_count: null
hourly_kwh: 0.039
daily_kwh: 8.615
monthly_kwh: null

**Comment by claudegel** [comment]
Oui ca va s'ajouter à la fin du mois.
Si tout est beau je vais publier un nouveau release demain.
merci pour votre aide.

**Comment by ldupont226** [comment]
Ça m'a fait plaisir et je suis très content.
encore merci
au plaisir.

**Comment by claudegel** [comment]
Laissez-moi savoir s'il y a autre chose.
merci pour votre aide
