### ISSUE TITLE
1 device Sinope ZB sur neviweb130 et 1 device Sinope ZB sur un autre controleur

### ISSUE THREAD

**Issue by bsauve** [claudegel/sinope-130#246]
Bonjour Claude,
j'utilise depuis un an neviweb130 avec des thermostats WiFi et des thermostats Zigbee connecté à la passerelle GT130.
Je viens d'installer un controleur Zigbee (ZigStar UZG) pour connecter un device Zigbee, jusqu'ici tout va bien.
Puis j'ai connecté une prise de coutant Sinopé à ce nouveau controleur Zigbee. Ça fonctionne.
Mais les autres devices Sinopé qui étaient connecté à la passerelle GT130 ne sont plsu visible dans HA.

Tu expliques ce qui suit dans ta page d'info mais je ne suis pas certain de comprendre. 
You need to install only one of them but both can be used at the same time on HA. Zigbee devices managed directly via Conbe II must be removed from Neviweb as they cannot be on two networks at the same time.

Ok, un device ne peut pas être sur deux controleur mais est-ce qu'on peut connecter un device Sinopé ZB au GT130 et un autre device Sinopé ZB à un autre controleur ?

Merci
Benoit

**Comment by bsauve** [comment]
Bonjour Claude,
j'ai enlevé le device Sinope ZB du controleur en pensant que mes device Sinope ZB reviendrait disponible dans HA mais ils ne reviennent pas, même après un restart de HA.

Comment doit-on faire pour retrouver les device Sinope ZB dans Neviweb130 ?

Merci
Benot

**Comment by claudegel** [comment]
Un même appareil zigbee  ne peut être connecté au GT130 et à une autre passerelle en même temps. Si vos autres appareils du GT130 ne sont plus visibles dans HA validez qu'ils sont toujours connectés à Neviweb.
Ensuite il faut vérifier les log da HA pour voir s'il n'y a pas un problème. Dans configuration.yaml assurez-vous d'avoir ceci pour activer les log correctement:
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
On se reparle ce soir. je suis sur la route.

**Comment by bsauve** [comment]
Merci Claude, voici le log qui je pense qui cause l'erreur, je ne sais ce qui a pu changer.
J'ai d'abord déconnecter la prise de Neviweb avant de la connecter sur le Zigbee controlleur.
C'est à ce moment que j'ai perdu le contact entre les autres device ZB et Neviweb130. Il sont toujour connecter à Sinope Neviweb.

Je ne sais pas comment debugger ce problème.

Mrci
Benoit


Logger: homeassistant.setup
Source: setup.py:404 
First occurred: 9:55:51 AM (1 occurrences) 
Last logged: 9:55:51 AM

Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 404, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 135, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 168, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network, network2)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 199, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb130/__init__.py", line 278, in __get_network
    elif (network["name"] == self._network_name2.capitalize()) or (network["name"] == self._network_name2[0].lower()+self._network_name2[1:]):
                                                                                      ~~~~~~~~~~~~~~~~~~~^^^
IndexError: string index out of range

**Comment by claudegel** [comment]
Les messages d'erreur au début des logs pour le unique_id ne sont pas important. je vais faire une mise a jour qui va corriger cela. si tu as changé quelques chose pour corriger ceci alors ca change le unique_id de tes appareils et ceux-ci n'existent plus. par contre dans ce cas de nouveau appareils ont été créé. Il ont le même nom mais suivit de _2.
Si c'est le cas tu vas les trouver dans outils de développement, états
Par exemple climate.neviweb130_climate_cave va devenir climate.neviweb130_climate_cave_2
Si c'est le bug alors efface climate.neviweb130_climate_cave et renomme climate.neviweb130_climate_cave_2 -> climate.neviweb130_climate_cave et tout va redevenir comme avant

**Comment by claudegel** [comment]
Pour l'erreur 
```
self._temp_status = device_data[ATTR_ERROR_CODE_SET1]["temperature"]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'temperature'
```
J'ai créé une branche qui corrige le bug. Sinopé a fait un changement concernant le parametre ATTR_ERROR_CODE_SET1
remplace ton code par celui de la branche:
https://github.com/claudegel/sinope-130/tree/error-code-fix/custom_components/neviweb130

**Comment by bsauve** [comment]
Je ne crois pas que ce soit le problème, j'ai 4 device sur 8 qui n'aparaissent plus. Je rgarde dans Develipment Tool -> States et ils ne sont pas là.

J'ai tenté d'en enlever un de Neviweb et de le remettre mais ça n'aide pas.

Je ne sais pas quoi faire.

Merci de ton support.
Benoit

**Comment by bsauve** [comment]
Donc ceci
self._temp_status = device_data[ATTR_ERROR_CODE_SET1]["temperature"]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'temperature'

peut expliquer pourqoui je ne vois plus 4 devices.

Je ne suis pas certain de quoi faire quand tu dis de remplacer mon code par celui de la branche ...
Peux-tu me guider un pleu plus ?

Merci
Benoit

**Comment by claudegel** [comment]
Oui absolument ça bloque la première update de l'appareil et alors elle n'est pas installée dans HA.
Prend ma branche error-code-fix
ca va tout replacer. En attendant que je fasse le nouveau release d'ici la fin de semaine

**Comment by claudegel** [comment]
Tu va sur la branche https://github.com/claudegel/sinope-130/tree/error-code-fix/custom_components/neviweb130
tu prends les fichier climate.py, light.py, switch.py, sensor.py et valve.py et tu remplaces ceux que tu as dans ton HA.
Puis tu redémarres HA

**Comment by bsauve** [comment]
Wow, ça semble fonctionner maintenant. J'ai passé tellement d'heures à chercher quoi faire. Merci.

Il reste des messages comme ça dans le log:

2024-06-05 23:00:35.872 ERROR (MainThread) [homeassistant.helpers.entity_registry] 'switch' from integration neviweb130 has a non string unique_id '352654', please report it to the author of the 'neviweb130' custom integration

Est-ce que je dois changer un nom quelque part ?

Merci encore.
Ben

**Comment by claudegel** [comment]
Parfait. Pour les erreurs de unique_id c'est juste un warning et on a jusqu'en 2025 pour corriger. Je travail dessus. Faut que je puisse changer les valeurs de unique_id dans le fichier .storage/core_entity_registry. Les unique_id de neviweb sont numérique et HA veut du alphanumérique. Faut que je remplace 352654 par "352654" et ensuite je fais un petit changement des neviweb130 pour transformer les unique_id de Neviweb en alphanumérique. je veux pas que les usagers soient obligés de faire les changements à la mitaine car ça risque de buster neviweb130.

**Comment by claudegel** [comment]
Je ferme cette issue. Le développement pour corriger le bug ATTR_ERROR_CODE_SET1 est dans l'issue # 247
J'ai fini de modifier le code et je vais publier une nouvelle version ce soir
