### ISSUE TITLE
New HA Core Vr 2024.6.4

### ISSUE THREAD

**Issue by PapaZodi** [claudegel/sinope-130#251]
I've been a long use of Neviweb, I'm trying to integrate it too HA.  Yes, I am new to HA, I did have Hubitat before but had limitations.

I'm assuming these two error logs are related.  From the HACS neviweb130 page, I followed the instructions, regarding the gateway info...  What if I don't have more than one network for Neviweb, do I leave the Network2 blank?

Or would these be related to do the current version of HA Core vr 2024.6.4, I've just installed vr 2.7.8 of sinpe-130

neviweb130:
  username: (confidential)
  password: (confidential)
  network: (confidential)
  network2:
  scan_interval: 540
  homekit_mode: False
  stat_interval: 1800

**Here is my first Error Log**

`Logger: homeassistant.setup
Source: setup.py:269
First occurred: 9:20:56 PM (2 occurrences)
Last logged: 9:20:58 PM

Setup failed for 'description': Integration not found.
Setup failed for custom integration 'neviweb130': Invalid config.`

**Here is my second Error Log**

`Logger: homeassistant.config
Source: config.py:1327
First occurred: 9:20:58 PM (1 occurrences)
Last logged: 9:20:58 PM

Invalid config for 'neviweb130' at configuration.yaml, line 17: string value is None for dictionary value 'neviweb130->network2', got None, please check the docs at https://github.com/claudegel/sinope-130`

Most information has outdated info, which most are using earlier versions of HA.  From what I've read from the HA site is the Config/Secreats.yaml, is fairely recent.

Can you assist?

**Comment by claudegel** [comment]
If you have only one network in Neviweb just remove the line about network2
```
neviweb130:
  username: !secret climate_username
  password: !secret climate_password
  network: !secret climate_gateway130
  scan_interval: 360
  stat_interval: 600
```
The secrets is there since long time it protect your sensitive data in configuration.yaml
```
climate_username: 'me@ha.com'
climate_password: '123456'
climate_gateway: 'my_home'
```
Put what you have for those three values.

**Comment by PapaZodi** [comment]
Thank you! so much, (merci beaucoup!), I've done only one adjustment, I added the '130' to the secrets.yaml, line 3.

I still have a lot to learn about yaml & Github.  I've only used the Excel VBA coding for work, which is similar, but not the same.

Now I got these in my error message, see below; 
```python
Logger: homeassistant.setup
Source: setup.py:402
First occurred: 11:18:47 AM (1 occurrences)
Last logged: 11:18:47 AM

Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 135, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 168, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network, network2)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 199, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb130/__init__.py", line 244, in __get_network
    raw_res = requests.get(LOCATIONS_URL + self._account, headers=self._headers,
                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
``` 

_Which seems logical, the first 2 error lines should be fixed once my thermostat names are identified, in the _init_ file, then remove the mention of Network2 from this _init_ file to sync my HA configuration file and to remove the Network2 from _init__
is this correct?



Is there an easy line of code in yaml, to disregard the “Network2”?

**Comment by claudegel** [comment]
If you have only one location (network) in Neviweb just omit the line about network2 in configuration.yaml

**Comment by claudegel** [comment]
Did you succeed ?

**Comment by PapaZodi** [comment]
Thank you for asking, but not yet, I haven't taken the time to try to fix error messages, mentioned above.  I'm taking a look at this evening, I've notice, did we have the same details in the Troubleshooting section has last week, or is this new?

I have 12 sinope thermostats with 1 gateway 130.  Looking over my climate.py, I don't see it being picked up by HA.  

1 - TH1300ZB - around line 1731
3 - TH1134ZB-HC - around line 2917
8 - TH1124ZB-G2 - around line 1573

I can see where you are picking up _some_ of this info for this section, but I'm a bit lost also, where you got some of these other details.  

![TH1300ZB](https://github.com/claudegel/sinope-130/assets/173308201/10ed9528-cb14-412e-baac-c8e6f9b3e958)

`[custom_components.neviweb130] Received gateway data: [{'id': 100225, 'identifier': '500b91400001f750', 'name': 'Chargeur auto', 'family': '2506',...
[custom_components.neviweb130] Received signature data: {'signature': {'model': 2506, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 9, 'middle': 2, 'major': 1}, 'hardRev': 2, 'protocol': 'sinopcom'}}`

Once, I have these lines where (which folder) would I add them too?

Your assistance is much appreciated

**Comment by claudegel** [comment]
What devices do you have exactly. Only thermostats or also load controller. You don't have to play with the code except maybe for the TH1134ZB-HC because I don't have this one but it is supported in the component. Maybe we will have to do few little adjustment.
Once you succeed to logging Neviweb you get this in your home-assistant.log file:
[custom_components.neviweb130] Login response: ...
[custom_components.neviweb130] Successfully logged in to: xxxxx
[custom_components.neviweb130] Number of networks found on Neviweb: 1
[custom_components.neviweb130] networks: [{'id': xxxxxx....
[custom_components.neviweb130] Selecting  «your network name» network ...

[custom_components.neviweb130] Received gateway data: [{'id': xxxx, ...  (this line contain all your devices)

Then you will see one line for each device with the model number
[custom_components.neviweb130] Received signature data: {'signature': {'model': 737,  (Which is your TH1300ZB)

After all signature lines you will start to see devices setup:
[custom_components.neviweb130.climate] Setting up neviweb130 climate «your thermostat»...
[custom_components.neviweb130.switch] Setting up neviweb130 switch Chargeur auto...

And finally the update lines:
[custom_components.neviweb130.climate] Updating neviweb130 climate «your thermostat»...
[custom_components.neviweb130.switch] Updating neviweb130 switch chargeur auto....

To get better logging add this to your configuration.yaml file and restart HA
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```
If you see all this your devices can be seen in developer tools / states
look for line containing climate.neviweb130_climate_«thermostats_name»
and switch.neviweb130_switch_chargeur_auto

**Comment by claudegel** [comment]
At the beginning of file climate.py you have all thermostat model number.
ex. 737 for TH1300ZB, 1134 for TH1134ZB-HC, 300 for TH1124ZB-G2
in the file switch.py you have the model number for your load controller
2506 for RM3250ZB

**Comment by claudegel** [comment]
I have TH1123ZB-G2, TH1124ZB-G2, TH1300ZB and they are all picked up by neviweb130. For the TH1134ZB-HC if it is not picked up it is just because the model number is wrong. We will fix that after other thermostats are working.

**Comment by PapaZodi** [comment]
I'm still fairly new to HA should I do the updates when available?  Core 2024.7.0 is now available.

I did add your code and did a restart, here are my log details
Logger: homeassistant.setup
Source: setup.py:402
First occurred: 6:52:15 PM (1 occurrences)
Last logged: 6:52:15 PM

Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 402, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 135, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 168, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network, network2)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 199, in __init__
    self.__get_network()
  File "/config/custom_components/neviweb130/__init__.py", line 244, in __get_network
    raw_res = requests.get(LOCATIONS_URL + self._account, headers=self._headers,
                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by PapaZodi** [comment]
wait a min my password in HA needs to be updated

**Comment by PapaZodi** [comment]
Success for connecting to neviweb to HA

**Comment by PapaZodi** [comment]
I'm now only missing those TH1134ZB-HC
![image](https://github.com/claudegel/sinope-130/assets/173308201/e5b67caf-65dc-42c3-8550-f848f7cfef0f)

**Comment by PapaZodi** [comment]
Is this the info you needed for the TH1134ZB-HC
![image](https://github.com/claudegel/sinope-130/assets/173308201/67731214-7405-4f65-b60b-f90caea91251)

**Comment by claudegel** [comment]
It is always a good idea to do all updates about HA or any custom_component.
yes this is what I need, the model number 1512
Just change line # 307 from:
DEVICE_MODEL_HC = [1134]
to
DEVICE_MODEL_HC = [1512]

and your thermostat will be available. Then we will need to validate if we receive all the attributes for that thermostat from Neviweb

**Comment by claudegel** [comment]
Do you also have HP6000ZB-xx inter connect for heat pump ?

**Comment by PapaZodi** [comment]
Sorry, at the moment I only have the thermostat.

I did do the updates, updated from 
DEVICE_MODEL_HC = [1134]
to
DEVICE_MODEL_HC = [1512]

did a restart, but they are not showing up in my entity list
![image](https://github.com/claudegel/sinope-130/assets/173308201/66008a21-ac97-47d9-b781-cd2403f60dc4)

Is there something else I can try?

**Comment by claudegel** [comment]
Ok look in your home-assistant.log there is a line
[custom_components.neviweb130.climate] Setting up neviweb130 climate «name of your TH1134ZB-HC»
if it is there then your device is detected
after there will be a line like this
[custom_components.neviweb130.climate] Updating neviweb130 climate «name of your TH1134ZB-HC» with a list of parameters. It is possible that one parameter is missing or wrong. In that case you should have many lines of error with many  ^^^^^^^^^^^^^^^^^
This will give us the problem

**Comment by claudegel** [comment]
You should see in log also 
[custom_components.neviweb130] Received signature data: {'signature': {'model': 1512...

**Comment by PapaZodi** [comment]
I'm trying to check the logs.

Could it be, that when I did HA update/restart, I can't seem to lookup info before that period of time the window just keep turning.

Would there be another way to find out?

![image](https://github.com/claudegel/sinope-130/assets/173308201/1ae4e2cb-765b-42a7-9356-27f8417cc2a7)

**Comment by claudegel** [comment]
When you restart HA the log file is restarted to zero and HA start to write in it the new log as it boot et update the devices. The best way is to open de file home-assistant.log located in the config directory where the configuration.yaml is located.

**Comment by PapaZodi** [comment]
I was able to locate these lines, but they are still not showing up in my entities
```
2024-07-04 17:30:28.361 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1134ZB-HC: {'id': 539696, 'identifier': '287681fffe55267d-f082c0fffe56cb06', 'name': 'TH1134ZB-HC', 'family': '1512', 'signature': {'model': 1512, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 2, 'major': 0}, 'hardRev': 3, 'protocol': 'sinopcom'}, 'location$id': 103101, 'parentDevice$id': 538878, 'group$id': 267031, 'orderIdx': 0, 'sku': 'TH1134ZB-HC', 'vendor': 'Sinopé', 'url_en': 'https://www.sinopetech.com/en/interlocking-solution/', 'url_fr': 'https://www.sinopetech.com/fr/interlocking-solution/', 'hcDevice': None}
2024-07-04 17:30:28.361 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1134ZB-HC: {'id': 540118, 'identifier': '287681fffe55267d-e0798dfffe625177', 'name': 'TH1134ZB-HC', 'family': '1512', 'signature': {'model': 1512, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 2, 'major': 0}, 'hardRev': 3, 'protocol': 'sinopcom'}, 'location$id': 103101, 'parentDevice$id': 538878, 'group$id': 267340, 'orderIdx': 0, 'sku': 'TH1134ZB-HC', 'vendor': 'Sinopé', 'url_en': 'https://www.sinopetech.com/en/interlocking-solution/', 'url_fr': 'https://www.sinopetech.com/fr/interlocking-solution/', 'hcDevice': None}
2024-07-04 17:30:28.361 DEBUG (MainThread) [custom_components.neviweb130.climate] Setting up neviweb130 climate TH1134ZB-HC: {'id': 549957, 'identifier': '287681fffe55267d-943469fffeb73a8a', 'name': 'TH1134ZB-HC', 'family': '1512', 'signature': {'model': 1512, 'modelCfg': 0, 'softBuildCfg': 0, 'softVersion': {'minor': 2, 'middle': 2, 'major': 0}, 'hardRev': 3, 'protocol': 'sinopcom'}, 'location$id': 103101, 'parentDevice$id': 538878, 'group$id': 267961, 'orderIdx': 0, 'sku': 'TH1134ZB-HC', 'vendor': 'Sinopé', 'url_en': 'https://www.sinopetech.com/en/interlocking-solution/', 'url_fr': 'https://www.sinopetech.com/fr/interlocking-solution/', 'hcDevice': None}
```

**Comment by claudegel** [comment]
OK fine you have three TH1134ZB_HC
They are initialized properly
Now we need to check if they are updated.
chack for line [custom_components.neviweb130.climate] Updating neviweb130 climate TH1134ZB-HC
It will probably give many line with error
Check for something like this:
[homeassistant.helpers.entity] Update for climate.neviweb130_climate_TH1134ZB-HC fails 
Then there is many error line and the last one say something like unknown attribute...
Send me those lines

**Comment by claudegel** [comment]
In climate.py comment line #3028 by adding at the beginning of the line a #
#                    self._heat_level = device_data[ATTR_OUTPUT_PERCENT_DISPLAY]

**Comment by PapaZodi** [comment]
Here are those error lines you were looking for, all 3 sections are the same

`2024-07-06 19:51:46.749 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1298, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/climate.py", line 3010, in update
    device_data[ATTR_ROOM_TEMPERATURE]["value"] != None else self._cur_temp_before
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'roomTemperature'`

I've added the # simbole at the beginning of row 3028 in climate.py, save changes did a reboot, I'm pretty sure this is the same error code showning afterwards;

`2024-07-06 19:51:46.749 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1298, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/climate.py", line 3010, in update
    device_data[ATTR_ROOM_TEMPERATURE]["value"] != None else self._cur_temp_before
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'roomTemperature'`

**Comment by claudegel** [comment]
Ok that is the attribute ATTR_ROOM_TEMPERATURE is the problem. 
It's strange because this attribute give the room temperature from the thermostat.  Maybe they use another attribute for room temperature. Let me check

**Comment by claudegel** [comment]
Ok as temporary fix, in climate.py comment line 3008, 3009, 3010 like this
#                    self._cur_temp_before = self._cur_temp
#                    self._cur_temp = float(device_data[ATTR_ROOM_TEMPERATURE]["value"]) if \
#                        device_data[ATTR_ROOM_TEMPERATURE]["value"] != None else self._cur_temp_before
and restart HA
We need to find out why Neviweb do not send room temperature value for your thermostat as it is sending the temperature value for all other thermostats.

**Comment by claudegel** [comment]
What browser are you using for access to neviweb.com ? firefox or chrome

**Comment by PapaZodi** [comment]
I seem to have run into another issue with HA,  I seem to have lost all my work up to date.  I don't even have HACS or the dashboard I was working on...  and can't seem to recover.

I'm using Microsoft Edge has my web browser, I could use Chrome.


![image](https://github.com/claudegel/sinope-130/assets/173308201/73b3e7ac-7a11-4dac-a0d7-9d4a33ceac6e)

**Comment by PapaZodi** [comment]
Back in, back in business, I've added the "#" has requested

![image](https://github.com/claudegel/sinope-130/assets/173308201/fa890585-3cb9-459a-aab8-3af57fbbf662)

**Comment by claudegel** [comment]
You can use any browser for HA. I'm using Firefox amd chrome. 
It look like Neviweb is not sending the room temperature parameter value as it do for all other thermostats.
So now ypour thermostat should show up in HA woth those lines commented out.
Check in your log to see if there is another KeyError: that appear
I'm gonna put a temporary fix for room temperature but after if you can use firefox to access neviweb.com I'll show you how to monitor what neviweb is sending to your browser when you open your thermostat TH1134ZB-HC parameters. This way we will see why the room temperature is not there and if Sinopé use another parameter name for this value.

**Comment by PapaZodi** [comment]
Just give me 30 min to do dishes, then I'll install Firefox

**Comment by claudegel** [comment]
No problem. Once you have it installed use it to go to neviweb.com. Then open your TH1134ZB-HC configuration and hit F12. The debug console will open at the bottom and you'll be able to see all the communication between neviweb server and your firefox page. This will help to find out what attribut is used to send the room temperature.
![firefox console](https://github.com/claudegel/sinope-130/assets/4268938/fd767e1e-24a0-422e-8620-d6be6d354e04)

**Comment by PapaZodi** [comment]
Downloading it now

**Comment by PapaZodi** [comment]
This is funny, it also giving an error in Firefox

![image](https://github.com/claudegel/sinope-130/assets/173308201/8387a9eb-13f8-4bb8-a625-cdebd6c1c4fe)

**Comment by PapaZodi** [comment]
how do you get the "Reponse" next screen shot

**Comment by PapaZodi** [comment]
Je recoit cette erreur aussi sur le TH1124ZB-HC

**Comment by PapaZodi** [comment]
Je joux pas souvant avec Firfox.  When I look your first section for Console, I'm not seeing it the same way,  But I'm trying to get to view your second section below, I cannot find the correct translation to Reponce from my options.

![image](https://github.com/claudegel/sinope-130/assets/173308201/9f5a2df6-0ba4-4d4c-91d2-fe6b48473ded)

**Comment by PapaZodi** [comment]
Was this what you where stating earlier once I add the "#" for line descriptions, on rows 3008, 3009, 3010 & 3028.

Here is the most recent log entry for neviweb;

`2024-07-07`` 20:13:52.292 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1048, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1070, in __async_calculate_state
    if state_attributes := self.state_attributes:
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 318, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 551, in state_attributes
    data[ATTR_PRESET_MODE] = self.preset_mode
                             ^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 318, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/climate.py", line 1111, in preset_mode
    if self._occupancy == PRESET_HOME:
       ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 318, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Neviweb130HcThermostat' object has no attribute '_occupancy''

But these TH1134ZB-HC are now showing in my entites :)

![image](https://github.com/claudegel/sinope-130/assets/173308201/73c31400-4199-49b7-b034-b299efafe78e)

**Comment by PapaZodi** [comment]
Here is another image from FireFox

![image](https://github.com/claudegel/sinope-130/assets/173308201/1e847929-aed7-416d-a1d6-945b33d5ab25)

**Comment by claudegel** [comment]
In climate.py add a line containing
self._occupancy = None
after line 2944
self._operation_mode = None

**Comment by claudegel** [comment]
In the firefox console, when you open the console there is a line named filter. On the right side of the line there are many button. One of them is XHR, Clic on it and you should see all the get lines form Neviweb

**Comment by claudegel** [comment]
I've put all fix in a new branch
https://github.com/claudegel/sinope-130/tree/HC-thermostat/custom_components/neviweb130
just take climate.py from that branch and replace the one you have in HA and restart

**Comment by PapaZodi** [comment]
Bonjour Claude,

I beleive this is the info you want... I hope
![image](https://github.com/claudegel/sinope-130/assets/173308201/1422b561-50bc-4273-ba52-c49633760a48)

**Comment by PapaZodi** [comment]
The thermostat was reading 20 degree C

**Comment by PapaZodi** [comment]
I've added the new code to Climate.py, did a restart.

Here is the current error code from my logs, all other TH.. got added.  The past 2 days I had to hard start HA, would this because of these changes?

2024-07-08 16:33:18.989 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 727, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1298, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/climate.py", line 3056, in update
    self._display_cap = device_data[ATTR_DISPLAY_CAP]
                        ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'displayCapability'

**Comment by claudegel** [comment]
I've fix the issue about ATTR_DISPLAY_CAP in the HC-thermostat branch. Pick the climate.py
About the attributes you've sent above it is exactly what I need. Do it again but open each configuration and advance setting for your thermostat it will display other attributes. This way I'll be able to complete the picture for that thermostat.

**Comment by PapaZodi** [comment]
I think I did have the Advance tab open, for the TH1135ZB-HC, there is only 1 option in the Advanced section which is the "cycle" and this is it.  Here is another clip.

![image](https://github.com/claudegel/sinope-130/assets/173308201/0c687a7a-61a3-4346-a990-94805e988f6f)

**Comment by PapaZodi** [comment]
Un gros merci,!!!  tous mes thermostate sont la :)

Je m'excuse mon francais a un gros manque de pratique.
