### ISSUE TITLE
Restart problem

### ISSUE THREAD

**Issue by mrochette01** [claudegel/sinope-130#255]
How can I correct this situation? For your information, I have just updated HA's operating system.

**Here's a copy of the log:**

Logger: homeassistant.setup
Source: setup.py:416
First occurred: 4:47:58 PM (1 occurrences)
Last logged: 4:47:58 PM

Error during setup of component neviweb130
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 135, in setup
    data = Neviweb130Data(hass_config[DOMAIN])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 168, in __init__
    self.neviweb130_client = Neviweb130Client(username, password, network, network2)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/neviweb130/__init__.py", line 198, in __init__
    self.__post_login_page()
  File "/config/custom_components/neviweb130/__init__.py", line 221, in __post_login_page
    raise PyNeviweb130Error("Cannot log in")
custom_components.neviweb130.PyNeviweb130Error: Cannot log in

**Comment by wiredmax** [comment]
I'm having the exact same issue right now, on login the API endpoint of naviweb is returning a HTTP 415 error: Unsupported Media Type

I think they now expect a different format or different headers for the login.

**Comment by mrochette01** [comment]
I hope they'll quickly fix the API format or its integration with HA.

**Comment by marcolivierarsenault** [comment]
Same here

**Comment by bpennypacker** [comment]
Also getting the same and also confirmed I'm receiving a 415 error on the login call.

**Comment by fransixles** [comment]
Same here

**Comment by lamungu** [comment]
The Login API is run without headers. Looking into it, the full response from a CURL Request shows this:

```
{"statusCode":415,"code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","error":"Unsupported Media Type","message":"Unsupported Media Type: application/x-www-form-urlencoded"}
```

Could it be the login API call requires to be sent as a JSON request? Maybe adding a header as `application/json` to it could fix the issue.

**Comment by lamungu** [comment]
I've submitted a potential fix on #256, and was able to test it on my own HA instance running on 2024.8.2.

My guess is the  Neviweb team has standardized their request flow internally, and enforced the JSON encoding on all their request, leading to the breakage on the plugin. 

Feel free to test the branch on your own instances if anything arises. Cheers!

**Comment by bpennypacker** [comment]
@lamungu Thanks for tracking this down so quickly! I just made the same change on my HA system and it appears to be working fine now.

**Comment by marcolivierarsenault** [comment]
Fixed it. Thanks

**Comment by jbenard2000** [comment]
Same problem here
