### ISSUE TITLE
Statistics for Energy issue

### ISSUE THREAD

**Issue by tessierp** [claudegel/sinope-130#263]
Seems like something must have changed recently, I am no longer able to keep track of energy statistics.

Lets take one of the rooms where I initially had this :

`    - name: "Tech Room hourly count energy usage"
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      state: >-
        {{ state_attr("climate.neviweb130_climate_th1123wf","hourly_kwh_count") }}`

Home Assistant would complain that it doesn't have a unique_id, hence it couldn't do anything with it. So I tried to add the following : 

`    - name: "Tech Room hourly count energy usage"
      unique_id: tech_room_hourly_count_energy_usage
      unit_of_measurement: "kWh"
      device_class: energy
      state_class: total_increasing
      state: >-
        {{ state_attr("climate.neviweb130_climate_th1123wf","hourly_kwh_count") }}`

Which solved the issue. I guess all you need is to update the documentation. Not sure if you are seeing the same issue on your side.

![image](https://github.com/user-attachments/assets/34a77593-f93c-4845-98f4-9a7c8faa86a9)

**Comment by claudegel** [comment]
Yes it is the same. There was a change in HA about sensors and template sensors. I've updated the documentation for template sensors.
Thanks for reporting this
