### ISSUE TITLE
Filling up logs with usage stats for basic valve

### ISSUE THREAD

**Issue by u8915055** [claudegel/sinope-130#266]
Hello, 

I have a wifi valve that i am using this component to manage in home assistant.  I am able to open and close my valve thru HA with no problems.

However for some reason i am getting all these logs messages relating to empty periodic stats:

```
2024-10-31 13:27:56.516 WARNING (SyncWorker_2) [custom_components.neviweb130.valve] Got None for device_hourly_stats
2024-10-31 13:27:56.928 WARNING (SyncWorker_2) [custom_components.neviweb130.valve] Got None for device_daily_stats
```

Is there a way to shut these off? I realize i could change the logging level for this component but to me i dont understand why this component is trying to constantly retrieve status like this for a basic valve with no flow meter or anything.

Thanks for your help.

The valve i have is VA4220WF

**Comment by claudegel** [comment]
Hi can you tel me what you have for attribute «flow_meter_model»
If it is «No flow meter» then i think I can avoid statistic
I'll create a new branch called flow so you can test when it is ready.
Just tell me your value for flow meter model

**Comment by claudegel** [comment]
In your log could you post the line containing
`[custom_components.neviweb130.valve] Updating neviweb130 valve .....`

**Comment by u8915055** [comment]
Hello there, thanks for the quick response.

Ok here are all the attributes associated with the valve entity in my home assistant installation:

```
valve_status: opened
temperature_alert: ok
battery_level: 96
battery_voltage: 5.9
battery_status: ok
power_supply: null
valve_closure_source: null
battery_alert: true
motor_target_position: 100
water_leak_status: flowMeter
valve_cause: remote
valve_info_id: 0000000000000002
alert_motor_jam: false
alert_motor_position: false
alert_motor_limit: false
away_action: 
action: none
actionPayload: null

flow_meter_alarm_delay_1: 60 min
flow_meter_alarm_duration_1: 1 min
flow_meter_alarm_flowMin_1: 120000
flowmeter_options_1: Close and send
flow_meter_alarm_delay_2: 60 min
flow_meter_alarm_duration_2: 1 min
flow_meter_alarm_flowMin_2: 120000
flowmeter_options_2: Close and send
temp_action_low: none
batt_action_low: none
battery_percent_normalized: 80
battery_status_normalized: ok
flow_meter_multiplier: 0
flow_meter_offset: 0
flow_meter_divisor: 1
occupancy_sensor_delay: 48 h
hourly_flow_count: null
daily_flow_count: null
monthly_flow_count: null
hourly_flow: null
daily_flow: null
monthly_flow: null
rssi: -45
sku: VA4220WF
device_model: 3150
device_model_cfg: 2
firmware: 2.7.3
activation: true
device_type: valve
id: 369677
device_class: water
icon: mdi:pipe-valve
friendly_name: neviweb130 valve VA4220WF
supported_features: 3
```

As you can see i dont see that flow meter model attribute.

I hope this helps.
Thanks again for your willingness to look into this..

**Comment by u8915055** [comment]
Oh and that line you asked about is not in my logs since my last reboot. I get one warning message about the Nevi component being a custom component and then it just goes into the constant warnings about the hourly daily and monthly stats being 'none'

**Comment by claudegel** [comment]
you need to activate the log in configuration.yaml
```
logger:
  default: warning
  logs:
    homeassistant.custom_components: debug
    custom_components.neviweb130: debug
```

**Comment by claudegel** [comment]
Also do you have the model of your valve. In Neviweb, check in the info section of your valve and tell me the model number. It should be 3150

**Comment by claudegel** [comment]
Ok thanks will be able with this 
'flowMeterMeasurementConfig': {'multiplier': 0, 'offset': 0, 'divisor': 1}
I'll put the changes in the flow branch today

**Comment by u8915055** [comment]
Excellent.. i will look for that change and give it a go.
Love the valve otherwise.. have paired it with a some zigbee water sensors and its great peace of mind.

thanks again

**Comment by claudegel** [comment]
Ok go to branch :
https://github.com/claudegel/sinope-130/tree/flow/custom_components/neviweb130
Just the file valv.py have changes. So copy valve.py over your custom_components/neviweb130/valve.py and restart HA

**Comment by u8915055** [comment]
It works!  Sorry for the delay.. just got some time to try it out.. no messages in the log anymore :). So, should i stay on this branch or will this be added somehow into the main branch?  Thanks again for your work on this.

**Comment by claudegel** [comment]
Keep it until next update tonight. The fix will be in the main branch later today.
