### ISSUE TITLE
ne pas utiliser le Network2 même si il y a des appareil dans Neviweb

### ISSUE THREAD

**Issue by bsauve** [claudegel/sinope-130#270]
Bonjour,
j'ai deux maisons avec des appareils Sinopé et un seul compte Neviweb.

On dirait que je dois absolument inscrire le nom des deux networks.

neviweb130:
  username: '«your Neviweb username»'
  password: '«your Neviweb password»'
  network: '«your gt130 location name in Neviweb»' (gt130 emplacement dans Neviweb)
  network2: '«your second location name in Neviweb»' (2e emplacement)

J'aimerais pouvoir mettre le nom du network 1 seulement dans une instance de HA et mettre le nom du network deux seulement dans ma deuxième instance de HA.

Quand je met rien pour le "network2" j'ai une erreur.

Est-ce possible ?

Merci

**Comment by claudegel** [comment]
Je suis a l'exterieur pour quelquss jours.Simplement omettre le parametre network2 dans chaque configuration.yamlEnvoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : bsauve ***@***.***> Date : 2024-11-06  11 h 25 a.m.  (GMT-05:00) À : claudegel/sinope-130 ***@***.***> Cc : Subscribed ***@***.***> Objet : [claudegel/sinope-130] ne pas utiliser le Network2 même si il y a des appareil dans Neviweb (Issue #270) 
Bonjour,
j'ai deux maisons avec des appareils Sinopé et un seul compte Neviweb.
On dirait que je dois absolument inscrire le nom des deux networks.
neviweb130:
username: '«your Neviweb username»'
password: '«your Neviweb password»'
network: '«your gt130 location name in Neviweb»' (gt130 emplacement dans Neviweb)
network2: '«your second location name in Neviweb»' (2e emplacement)
J'aimerais pouvoir mettre le nom du network 1 seulement dans une instance de HA et mettre le nom du network deux seulement dans ma deuxième instance de HA.
Quand je met rien pour le "network2" j'ai une erreur.
Est-ce possible ?
Merci

**Comment by bsauve** [comment]
Ça semble bien fonctionner d'enlever completement la ligne "network2".
Merci

**Comment by claudegel** [comment]
Tu peux aussi garder tous tes appareils dans le même HA en ayant 2 reseaux, network et network2
Les appareils dans Neviweb associés au premier network s'appelleront climate.neviweb130_climate_nom_de_appareil
et pour le network2
climate.neviweb130_climate_2_nom_de_appareil
de cette façon c'est facile de les gérer séparéments pour les automations et sur le tableau de bord.

**Comment by bsauve** [comment]
Oui merci c'est comme ça que je fonctionnais avant mais j'ai décidé d'avoir 2 instances de HA afin de séparer les deux maison et pouvoir gérer plus facilement le géofencing. Deux home bien distincte, çe me semble plus facile.

Merci

**Comment by claudegel** [comment]
Bon les deux méthodes fonctionnent heureusement. Faut juste se rappeler que le paramêtre network2 on a pas besoin de le mettre dans configuration.yaml si on a pas deux réseaux de Neviweb à mettre dans le même HA. 
Laissez-moi savoir si il y a autre chose.
