### ISSUE TITLE
Reading target temperature

### ISSUE THREAD

**Issue by SylvainGa** [claudegel/sinope-130#3]
Hi,

I would like to create an automation that is triggered by a webhook. The would automation sets the temperature to 21C when activated but only if it's at a target temperature of 15C (ie, nobody home). Reason for that is if after 30 minutes the person that triggered it isn't home, it will reset back to 15C but I don't want to reset if it wasn't at 15C to start with. I tried different methods to read the target temperature and to no avail. Is there an implemented method for that? I would think so since the Thermostat entity do display the target temperature.

Thanks,

**Comment by claudegel** [comment]
To get the target temperature of a thermostat in Home Assistant you need to use a numeric state trigger
trigger:
    platform: numeric_state
    entity_id: climate.neviweb130_climate_THERMOSTAT_NAME
    value_template: "{{ state.attributes.temperature }}"

or you could use something like:
{{states.climate.neviweb130_climate_THERMOSTAT_NAME.attributes.temperature}}

**Comment by claudegel** [comment]
the attribute temperature is your thermostat setpoint temperature

**Comment by SylvainGa** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Merci!                                                                                                                                              Envoyé via Boîte de réception BlackBerry Hub+ pour Android                                                                                                                                                                           De : notifications@github.comEnvoyé : 6 janvier 2020 22 h 05À : sinope-130@noreply.github.comRépondre à : reply@reply.github.comCc : gagnon.sylvain@gmail.com; author@noreply.github.comObjet : Re: [claudegel/sinope-130] Reading target temperature (#3)  To get the target temperature of a thermostat in Home Assistant you need to use a numeric state trigger
trigger:
platform: numeric_state
entity_id: climate.neviweb130_climate_THERMOSTAT_NAME
value_template: "{{ state.attributes.temperature }}"
or you could use something like:
{{states.climate.neviweb130_climate_THERMOSTAT_NAME.attributes.temperature}}
