### ISSUE TITLE
Session expired

### ISSUE THREAD

**Issue by charlesdagenais** [claudegel/sinope-130#33]
Second time this week, I’m getting a session expired message in log. Thermostats stop updating.

Restarting HA restore the normal behaviour, but I’ll watch for how long before the session expire again (got this happening 2 times this week)

```
Traceback` (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/neviweb130/climate.py", line 425, in update
    device_data = self._client.get_device_attributes(self._id,
  File "/config/custom_components/neviweb130/__init__.py", line 235, in get_device_attributes
    raise PyNeviweb130Error("Session expired")
custom_components.neviweb130.PyNeviweb130Error: Session expired
```

scan interval is `300`

running HA 2021.08

**Comment by claudegel** [comment]
What is your scan_interval parameter. Mine is 360

**Comment by charlesdagenais** [comment]
> What is your scan_interval parameter. Mine is 360

300

**Comment by claudegel** [comment]
Please check in your log for this line:
`[custom_components.neviweb130] Setting scan interval to: `
is it 0:05:00 ?

**Comment by claudegel** [comment]
If you don't see this line in your log, add debugging in configuration.yaml like this
```
logger:
  default: warning
  logs:
    custom_components.neviweb130: debug
```
Then restart HA

**Comment by charlesdagenais** [comment]
> Please check in your log for this line:
> `[custom_components.neviweb130] Setting scan interval to: `
> is it 0:05:00 ?

yes I see that. 0:05:00  .  Will monitor the logs in next couple of days if it happen again,
