### ISSUE TITLE
'ATTR_WIFI_FLOOR_OUTPUT1' is not defined

### ISSUE THREAD

**Issue by horspiste** [claudegel/sinope-130#40]
Bonjour, avec la version 0.7, j'ai maintenant 2 fois cette erreur dans mon log quand je redémarre HA. Je crois que ce sont certains de mes thermostats OTH3600-GA-ZB qui font cela.

2021-11-22 09:34:14 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/climate.py", line 472, in update
WIFI_FLOOR_ATTRIBUTE = [ATTR_WIFI_FLOOR_OUTPUT1, ATTR_FLOOR_MAX, ATTR_FLOOR_MIM]
NameError: name 'ATTR_WIFI_FLOOR_OUTPUT1' is not defined

**Comment by horspiste** [comment]
Il s'agit plutôt que mes deux thermostats TH1300WF qui font cela. Les autres sont ok.

**Comment by ijustlikeit** [comment]
Same error after upgrading to latest version:
2021-11-22 15:39:25 ERROR (MainThread) [homeassistant.components.climate] neviweb130: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 651, in async_device_update
await task
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/neviweb130/climate.py", line 472, in update
WIFI_FLOOR_ATTRIBUTE = [ATTR_WIFI_FLOOR_OUTPUT1, ATTR_FLOOR_MAX, ATTR_FLOOR_MIM]
NameError: name 'ATTR_WIFI_FLOOR_OUTPUT1' is not defined

**Comment by MarioBouchard** [comment]
Même problème ici. J'ai des TH1300WF qui ne fonctionnent pas mais les autres sont ok

**Comment by claudegel** [comment]
Sorry guys I've forgotten that one. I've created a branch wifi-floor. You just need to download climate.py and copy over yours in HA then restart HA. You can also edit your climate.py and change line 472
from
`WIFI_FLOOR_ATTRIBUTE = [ATTR_WIFI_FLOOR_OUTPUT1, ATTR_FLOOR_MAX, ATTR_FLOOR_MIM]`
to`
WIFI_FLOOR_ATTRIBUTE = [ATTR_FLOOR_MAX, ATTR_FLOOR_MIM]`

If any of you have time to send me all the TH1300WF attributes in Neviweb it will help me to improve veniweb130 for that thermostat

**Comment by claudegel** [comment]
Désolé je me pensais sur le blog. J'ai créé une branche wifi-floor. Il y a juste le fichier climate.py qui est changé. Simplement récupérer ce fichier et écraser celui de custom_components/neviweb130/climate.py puis redémarrer HA.
Sinon vous pouvez éditer votre fichier climate.py et changer la ligne 472
de:
`WIFI_FLOOR_ATTRIBUTE = [ATTR_WIFI_FLOOR_OUTPUT1, ATTR_FLOOR_MAX, ATTR_FLOOR_MIM]`
à
`WIFI_FLOOR_ATTRIBUTE = [ATTR_FLOOR_MAX, ATTR_FLOOR_MIM]`
Si quelqu'un a un peu de temps pourriez-vous m'envoyer les attributs de ce thermostats dans Neviweb ? Ceci me permettrait de l'optimiser dans HA.
Pour avoir les attributs il faut ouvrir la console de débug de firefox ou chrome selon le navigateur que vous utilisez. Je peux vous guider au besoin.

**Comment by ijustlikeit** [comment]
Thanks Claude.   Small  typepo correction to your suggested code...should be:
WIFI_FLOOR_ATTRIBUTE = [ATTR_FLOOR_MAX, ATTR_FLOOR_**MIN**]
not
WIFI_FLOOR_ATTRIBUTE = [ATTR_FLOOR_MAX, ATTR_FLOOR_MIM]

Tested and working btw.

**Comment by ijustlikeit** [comment]
Are these the attributes you were asking for TH1300WF?

attachment
![att](https://user-images.githubusercontent.com/58893668/142971446-618ff23c-69e4-4894-9cae-50c12130866b.PNG)
:

**Comment by MarioBouchard** [comment]
![Screenshot 2021-11-23 071700](https://user-images.githubusercontent.com/90644968/143022591-6151f7e2-1e3e-4506-abb8-a788ff0cc71e.jpg)

**Comment by horspiste** [comment]
Voici les miens pour TH1300WF:
hvac_modes: off, auto, heat
min_temp: 16.5
max_temp: 24
preset_modes: none, away, temporary
current_temperature: 19.1
temperature: 17
hvac_action: idle
preset_mode: none
wattage: 1248
gfci_status: ok
sensor_mode: roomByFloor
slave_heat: off
slave_status: null
slave_load: 0
floor_setpoint_max: 30
floor_setpoint_low: 22
floor_air_limit: 19
floor_sensor_type: 10k
load_watt: 1248
floor_limit_high: 30
floor_limit_high_status: on
floor_limit_low: 22
floor_limit_low_status: on
max_air_limit: 19
max_air_limit_status: on
second_display: exteriorTemperature
occupancy: none
backlight: null
heat_level: 0
keypad: unlock
time_format: 24h
temperature_format: celsius
setpoint_max: 24
setpoint_min: 16.5
rssi: -24
id: 153539
unit_of_measurement: celsius
friendly_name: neviweb130 climate Charlena SDB
supported_features: 17
device_class: temperature

**Comment by claudegel** [comment]
Merci ce que je cherchais est fourni par MarioBouchard. Ce sont les parametre que Neviweb envoi et reçoi donc ce que je dois demander pour avoir toutes les infos et les transférer dans HA.
J'ai fais une mise a jour 0.7.2 pour fixer le petit bug et la je vais travailler un peu pour avoir toutes les données du Th1300WF disponibles dans HA 

Merci des nouvelles sous peu

**Comment by claudegel** [comment]
I've completed support for TH1300WF. If you want to test before I release. Check branch th1300wf and download climate.py and const.py. Let me know

**Comment by horspiste** [comment]
I've installed the new const.py and climate.py and so far all seems well. I
got a warning of "setup of climate platform neviweb130 is taking over 10
second" but I also had that before.

Thanks.

Sylvain

**Comment by claudegel** [comment]
OK thank you. I'll push a new release
