### ISSUE TITLE
HVAC Mode - Zigbee

### ISSUE THREAD

**Issue by sicarriere** [claudegel/sinope-130#44]
Maybe this is not a issue, but it seems that we can't set the HVAC Mode with the Zigbee (TH1123ZB by example) device with GT130 gateway. 

I only have these attributes in Neviweb (developper console) :
`{"roomSetpoint":16,"roomTemperature":{"value":18.1},"outputPercentDisplay":0}`

If I check my WiFi's devices, I have more attributes :
`{"setpointMode":"manual","roomSetpoint":21.5,"roomTemperatureDisplay":{"value":21.5,"status":"on"},"outputPercentDisplay":{"percent":20,"sourceType":"heating"},"occupancyMode":"none"}`

Or I missing something ;-)

**Comment by claudegel** [comment]
Can you post the line you have in HA log for this thermostat. Something like this
`...Updating neviweb130 climate Plancher cuisine (1.469 sec): {'roomSetpoint': 22, 'outputPercentDisplay': 0, 'roomTemperature': {'value': 22.64}, 'roomSetpointMin': 10, 'roomSetpointMax': 26, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'gfciStatus': 'ok', 'airFloorMode': 'floor', 'auxHeatConfig': 'off', 'loadWattOutput2': {'status': 'on', 'value': 0}, 'floorMaxAirTemperature': {'status': 'on', 'value': 25}, 'floorSensorType': '10k', 'loadConnected': 1800, 'lockKeypad': 'unlocked', 'backlightAdaptive': 'always'}`
It look like I have the same problem. There is three hvac modes: Off, Heat and Auto but the preset mode is None and I can't switch between them. I'll need to investigate on Neviweb if they had changes some attributes.
Could you check on your side in the developper console what show up when you switch between those mode in Neviweb for your thermostat. I have only zigbee floor thermostats on Neviweb. My other thermostats are MIWI :(

**Comment by sicarriere** [comment]
Here the log :

Garage is a Zigbee :
`2021-12-08 11:49:42 DEBUG (SyncWorker_14) [custom_components.neviweb130] Data = {'setpointMode': 'off'}
2021-12-08 11:49:42 DEBUG (SyncWorker_14) [custom_components.neviweb130] Request response = 200
2021-12-08 11:49:42 DEBUG (SyncWorker_14) [custom_components.neviweb130] Json Data received= {}
2021-12-08 11:49:42 DEBUG (SyncWorker_14) [custom_components.neviweb130] Content = b'{}'
2021-12-08 11:49:42 DEBUG (SyncWorker_14) [custom_components.neviweb130] Text = {}
2021-12-08 11:49:43 DEBUG (SyncWorker_11) [custom_components.neviweb130.climate] Updating neviweb130 climate Garage (0.693 sec): {'roomSetpoint': 13, 'outputPercentDisplay': 60, 'roomTemperature': {'value': 13.24}, 'roomSetpointMin': 5, 'roomSetpointMax': 30, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'loadConnected': 1980, 'lockKeypad': 'unlocked', 'backlightAdaptive': 'always'}
`

And my office ;-) is a WiFi :
`2021-12-08 11:50:47 DEBUG (SyncWorker_16) [custom_components.neviweb130] Data = {'setpointMode': 'off'}
2021-12-08 11:50:47 DEBUG (SyncWorker_16) [custom_components.neviweb130] Request response = 200
2021-12-08 11:50:47 DEBUG (SyncWorker_16) [custom_components.neviweb130] Json Data received= {'setpointMode': 'off'}
2021-12-08 11:50:47 DEBUG (SyncWorker_16) [custom_components.neviweb130] Content = b'{"setpointMode":"off"}'
2021-12-08 11:50:47 DEBUG (SyncWorker_16) [custom_components.neviweb130] Text = {"setpointMode":"off"}
2021-12-08 11:50:47 DEBUG (SyncWorker_15) [custom_components.neviweb130.climate] Updating neviweb130 climate Bureau Eric (0.791 sec): {'roomSetpoint': 16, 'outputPercentDisplay': {'percent': 0, 'sourceType': 'heating'}, 'roomTemperature': {'value': 18.92, 'error': None}, 'roomSetpointMin': 5, 'roomSetpointMax': 30, 'timeFormat': '24h', 'temperatureFormat': 'celsius', 'loadWatt': 1197, 'wifiRssi': -71, 'keyboardLock': 'unlock', 'config2ndDisplay': 'default', 'setpointMode': 'off', 'occupancyMode': 'none', 'backlightAutoDim': 'alwaysOn'}`

In neviweb, I don't have the option to set the HVAC Mode for Zigbee, here the two screenshot (Zigbee and WiFi) :
![image](https://user-images.githubusercontent.com/47251868/145250015-1f120409-167c-4fa0-bff9-090a14c36d78.png)
![image](https://user-images.githubusercontent.com/47251868/145250135-9307aa2d-3383-498f-8b57-63802823a76c.png)

**Comment by claudegel** [comment]
Yes I just saw that. Sinopé didn't  put on, off, auto  mode because they added automation that we can program for our thermostats. It's not clear where those automation are stored, in the GT130 or  in Neviweb.
As I don't have any wifi thermostats I can't check for those one. But I think we should remove HVAC_MODE_AUTO and PRESET_BYPASS, they are not supported by Neviweb for the zigbee thermostats.
Can you tell me if there is auto mode for the wifi thermostats ?

**Comment by claudegel** [comment]
Same zigbee thermostat connected to HA via ZHA have off/heat mode and none/away preset. For your wifi thermostat the occupancyMode is the equivalent to away preset.

**Comment by claudegel** [comment]
I've created a new branch thermostat-mode to clean up mode and preset for thermostat. There are changes in const.py and climate.py. Please test on your side

**Comment by sicarriere** [comment]
Hi Claude,

Yes, The Wifi' one have the "auto" mode :
![image](https://user-images.githubusercontent.com/47251868/145399083-66d84859-a129-4a4c-a6fe-eb0f1e02949b.png)

Si, If I want the "off" havac mode, I must go with a Cronbee II for my Zigbee one?....  Amazon je m'en viens ;-)

**Comment by claudegel** [comment]
Does it work with the actual version of neviweb130? Can you set it to auto ?
Can you send me the exact parameter used when you set it to auto or manual or stop in Neviweb with the developper console. I need the three parameters to add them correctly in neviweb130. It will be deactivated for the zigbee devices but available for the wifi one

**Comment by sicarriere** [comment]
With the WiFi's one, everything is ok, but here the parameters from the Neviweb site :

Auto :
`{"setpointMode":"auto","roomSetpoint":21,"roomTemperatureDisplay":{"value":21.5,"status":"on"},"outputPercentDisplay":{"percent":0,"sourceType":"heating"},"occupancyMode":"none","drStatus":{"drActive":"off","optOut":"off","setpoint":"off","powerAbsolute":"off","powerRelative":"off"},"drSetpoint":{"status":"off","value":null}}`

Manual :
`{"setpointMode":"manual","roomSetpoint":16,"roomTemperatureDisplay":{"value":21.5,"status":"on"},"outputPercentDisplay":{"percent":0,"sourceType":"heating"},"occupancyMode":"none"}`

Off:
`{"setpointMode":"off","roomSetpoint":21,"roomTemperatureDisplay":{"value":21,"status":"on"},"outputPercentDisplay":{"percent":0,"sourceType":"heating"},"occupancyMode":"none","drStatus":{"drActive":"off","optOut":"off","setpoint":"off","powerAbsolute":"off","powerRelative":"off"},"drSetpoint":{"status":"off","value":null}}`

**Comment by claudegel** [comment]
Thank you, with that info I can configure climate.py so it work for wifi thermostats and it is not available for the zigbee
I'll update the branch thermostat-mode

**Comment by claudegel** [comment]
If you put your wifi thermostat in auto mode and after you manually change setpoint on thermostat. Does your thermostat show a temporary mode in Neviweb. I think it is the autoBypass attribute for setpointMode

**Comment by sicarriere** [comment]
Exactly : 
Switch my WiFi to auto :
`{"setpointMode":"auto","roomSetpoint":21,"roomTemperatureDisplay":{"value":19.5,"status":"on"},"outputPercentDisplay":{"percent":100,"sourceType":"heating"},"occupancyMode":"none","drStatus":{"drActive":"off","optOut":"off","setpoint":"off","powerAbsolute":"off","powerRelative":"off"},"drSetpoint":{"status":"off","value":null}}
`
And change the setpoint to 25 :
`{"setpointMode":"autoBypass","roomSetpoint":25,"roomTemperatureDisplay":{"value":19.5,"status":"on"},"outputPercentDisplay":{"percent":100,"sourceType":"heating"},"occupancyMode":"none"}`

So yes, we have the "autoBypass" for the WiFi

**Comment by claudegel** [comment]
Ok thank you. now ready to make the changes to neviweb130. Will tell you when it's available to test

**Comment by claudegel** [comment]
Ok I've created a branch  modes-patch. Just climate.py have changed.
please test and I'll make a new release if it is ok
Thank you for your help

**Comment by sicarriere** [comment]
Hi Claude,

every Wifi mode are working correctly. The only thing, it said "temporary" instead of "Temporaire" when we bypass the auto mode. So, it's look like that HA don't have that translation.

And for the Zigbee, we still have the "off" in "HVAC_MODES".  But since I know that it's not an option in neviweb (so not working), and I'm waiting my cronbee II this week, I will switch them on the cronbee ;-) with ZHA

**Comment by claudegel** [comment]
The translation for Temporary is in climate.py
change line 143
`PRESET_BYPASS = 'temporary'`
to `PRESET_BYPASS = 'Temporaire'`
This is not in HA translation
As for the 'off' in HVAC_MODE I'll check with Sinopé to see if they can add it because the same thermostat can be turned off in zha. So it should be possible to have the same in Neviweb

**Comment by claudegel** [comment]
I just push a new release for preset and modes of wifi/zigbee

**Comment by claudegel** [comment]
Hi Eric,

Sinopé just told me that they are working on off mode for the zigbee
thermostat and they have a target date for beginning of 2022.

Claude Gelinas

Le Thu, 09 Dec 2021 04:48:54 -0800
Eric Carriere ***@***.***> a écrit:

> Hi Claude,
> 
> Yes, The Wifi' one have the "auto" mode :
> ![image](https://user-images.githubusercontent.com/47251868/145399083-66d84859-a129-4a4c-a6fe-eb0f1e02949b.png)
> 
> Si, If I want the "off" havac mode, I must go with a Cronbee II for
> my Zigbee one?....  Amazon je m'en viens ;-)
> 
>

**Comment by sicarriere** [comment]
Thanks Claude. Great news.... In the meantime, I will play with my cronbee II when it will be at home in the next 3 hours ;-)
