### ISSUE TITLE
Problem with HomeAssistant 12.x  "implements device_state_attributes"

### ISSUE THREAD

**Issue by horspiste** [claudegel/sinope-130#46]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 09:32:02 (7 occurrences)
Last logged: 09:32:13

Entity climate.neviweb130_climate_charlena_sdb (<class 'custom_components.neviweb130.climate.Neviweb130Thermostat'>) implements device_state_attributes. Please report it to the custom component author.
Entity climate.neviweb130_climate_salle_de_lavage (<class 'custom_components.neviweb130.climate.Neviweb130Thermostat'>) implements device_state_attributes. Please report it to the custom component author.
Entity climate.neviweb130_climate_sdb (<class 'custom_components.neviweb130.climate.Neviweb130Thermostat'>) implements device_state_attributes. Please report it to the custom component author.
Entity climate.neviweb130_climate_sdb_centre (<class 'custom_components.neviweb130.climate.Neviweb130Thermostat'>) implements device_state_attributes. Please report it to the custom component author.
Entity climate.neviweb130_climate_walk_in (<class 'custom_components.neviweb130.climate.Neviweb130Thermostat'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by claudegel** [comment]
Yes I'm working on this. With the last update of HA lots of things are becoming deprecated and I need to change many line of code. Neviweb130 and all other custom component for Sinopé devices are still working perfectly. I should have a release in the coming days or weeks.
Thank you for reporting this issue.

**Comment by claudegel** [comment]
It's done. update to 0.8.2

Thank you
