### ISSUE TITLE
Add energy to climate

### ISSUE THREAD

**Issue by djiesr** [claudegel/sinope-130#58]
It's possible to add the energy to device? 
I see we can get it by hour or by day with:
https://neviweb.com/api/device/123456/energy/hourly
https://neviweb.com/api/device/123456/energy/daily
Thanks!

**Comment by claudegel** [comment]
Yes It's possible. I'm doing an update today to add new Sinopé devices then I'll add your stat. I'll open a branch for this and let you know today.
It is possible to get hourly, daily and monthly but it will load the communication if we ask for this every 5 minutes. I'll check if it is possible to have a different schedule to get the data.

**Comment by claudegel** [comment]
Could be something like 
hourly, once per hour
daily, once a day
monthly, once a month
Let me check

**Comment by djiesr** [comment]
I think the better way it's every 30 minutes for hourly, every 4 hours for day and every day for month. Just in case...

**Comment by claudegel** [comment]
I've created a new branch «stats» with basic today energy polling for thermostats, light and switch. Check this and I'll add frequency of polling later today.

**Comment by charlesdagenais** [comment]
Wouldn’t hourly only be enough to build daily and monthly stat in HA energy module ?

**Comment by djiesr** [comment]
Thanks! I will stay tune.

**Comment by claudegel** [comment]
In init.py I've setup for hourly, daily and monthly polling. I'll start to set hourly polling every hour because Neviweb is sending each time the last 48 hours. Then we will see if this is enough for the energy module.

**Comment by claudegel** [comment]
OK now I can catch all stats from Neviweb. I've added debug so you can see what we get and in what format so we can start to extract what we want. Look on it and tell me what you need. I've activated only daily stats to start
In your log look for 
Climate Stats received:...
Light Stats received:...
Switch Stats received:...

**Comment by djiesr** [comment]
C'est bon si on continue en français?
Vous savez ce que periodQuality et counter veulent dire?

**Comment by djiesr** [comment]
Ok periodeQuality ce sont les minutes, mais "counter"?

**Comment by claudegel** [comment]
periodQuality c'est les minutes de la période, ex 1440 c'est 24hr
counter c'est la somme des watt utilisé a chaque période. Donc pour avoir les kwh utilisés pendant une période il faut prendre la période courante et soustraire la période precedante puis /1000
Je ne sais pas ce que le module energy a besoin. Je pense qu'il veux les kwh de la journée

**Comment by claudegel** [comment]
Je vois que le daily stat retourne les 30 derniers jours donc il faut extraire le data de aujourd'hui et de la veille pour obtenir la consommateion du jour.
On devrait executer ca à 00:01 et prendre le data de la veille

**Comment by djiesr** [comment]
ok, period c'est la consommation de la journée et counter c'est le total. Juste avoir le counter, ça permet de faire ce qu'on veut avec avec utility_meter comme:

> utility_meter:
>   energy_thermostat_salon_jour:
>     source: sensor.0x500b914000s0sd0d5_energy
>     name: Thermostat salon par jour
>     cycle: daily

**Comment by charlesdagenais** [comment]
> ok, period c'est la consommation de la journée et counter c'est le total. Juste avoir le counter, ça permet de faire ce qu'on veut avec avec utility_meter comme:
> 
> > utility_meter:
> > energy_thermostat_salon_jour:
> > source: sensor.0x500b914000s0sd0d5_energy
> > name: Thermostat salon par jour
> > cycle: daily

J'ai jamais reussi à créer un sensor qui fonctionnait dans le dashboard energy avec utility_meter . J'ai peut-etre mal compris...


De la [page de support dev HA](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
)

Je comprends que le sensor d'un device devrait avoir les propriétés suivantes pour pouvoir le faire apparaitre dans le dashboard Energy . 

device_class: energy
unit_of_measurement: kWh
state_class: total_increasing

et comme valeur, le résultat de   `data["history"][0]["counter"] / 1000`   tiré de  `https://neviweb.com/api/device/123456/energy/hourly`  pour obtenir le dernier total à jour

**Comment by claudegel** [comment]
Ok pour les thermostats le device_class c'est temperature, unit_of_measurement self._temperature_format et state_class est pas défini dans climate.py.
Donc je suppose qu'il faut créer un sensor qui a ces propriétés à partir d'un attribut du thermostat qui va donner le today_energy_kwh ou bien le hourly_energy_kwh
Je vais commencer par extraire la valeur pour les kwh pour chaque heure et lire un peu la doc du module energy

**Comment by djiesr** [comment]
Avant j'utilisais zigbee2mqtt pour les Sinope et je n'avais que la valeur total des kWh exemple 1542kWh et avec utility_meter: je pouvais diviser en heure, jour, mois, année comme ça:

> utility_meter:
> energy_thermostat_salon_jour:
> source: sensor.0x500b914000s0sd0d5_energy
> name: Thermostat salon par jour
> cycle: daily

et après dans les "appareil individuels dans Énergie, j'ajoutais " sensor.energy_thermostat_salon_jour".
C'est bien d'avoir un sensor qui dit la consommation par jour, mais le sensor total (counter) est tout aussi efficace pour avoir heure, jour, mois. Suffit de le mettre à jour aux 30 minutes.

**Comment by djiesr** [comment]
Avez le "daily", il va prendre la différence avec la journée précédente automatiquement. Exemple de ma consommation du mois de janvier.
![image](https://user-images.githubusercontent.com/31359825/151718845-cfc3ad16-03a6-436f-b789-cfee24981f6e.png)

**Comment by claudegel** [comment]
Bingo j'ai mis a jour la branche et on a toutes les valeurs pour les thermostats, lumières et switch
'hourly_kwh_sum': la consommation total à l'heure
'daily_kwh_sum': la consommation total au jour
'monthly_kwh_sum': la consommation total au mois

Je pourrais aussi avoir juste la consommation pour la dernière heure, le dernier jour et le dernier mois en faisant la soustraction
'hour_kwh'
'day_kwh'
'month_kwh'

**Comment by claudegel** [comment]
Pour l'instant les conteur se mettent a jour selon le scan_interval mais je pourrais regarder pour aller chercher les valeurs aux demi-heures

**Comment by djiesr** [comment]
Mes résultats sont un peu étranges, j'ai moins consommé depuis un moi que depuis une heure:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/31359825/151721122-cac3db73-80c1-4e22-9d54-8e6b0e3aca00.png">
Et est-ce qu'on peut ajouter total_kwh avec le "counter" ?

**Comment by charlesdagenais** [comment]
> Mes résultats sont un peu étranges, j'ai moins consommé depuis un moi que depuis une heure: <img alt="image" width="160" src="https://user-images.githubusercontent.com/31359825/151721122-cac3db73-80c1-4e22-9d54-8e6b0e3aca00.png"> Et est-ce qu'on peut ajouter total_kwh avec le "counter" ?

C'est parce que le last update du point de données hourly est plus récent que le daily:
hourly (remarquer la valeur qu'on retrouve plus bas dans le daily)
<img width="699" alt="image" src="https://user-images.githubusercontent.com/2420301/151721336-bf8ed082-cb04-41d3-b565-c0bccb0cd3c1.png">
daily
<img width="730" alt="image" src="https://user-images.githubusercontent.com/2420301/151721295-6c062eb2-7e88-4525-8a2a-274a87ff3c1b.png">

**Comment by claudegel** [comment]
J'ai validé sur Neviweb et les valeurs semblent correctes. Sauf que je pense qu'il y a eu un reset de certaines valeurs. 
hourly_kwh: 2619.16
daily_kwh: 2613.119
monthly_kwh: 2443.055
Pour les mois il y a juste 16 mois d'historique au lieu de 24
Je vais ajouter la valeur pour la période courante: periode
Je pense aussi que la valeur pour heure et jour c'est le même compteur total sauf qu'il est affiché aux heures pour le hourly et au jours pour le daily. Donc hourly monte alors que daily affiche le total de minuit la veille.

**Comment by djiesr** [comment]
Ok, je comprends, Merci! Vous êtes super efficace!

**Comment by claudegel** [comment]
Bon il faudrait trouver un nom d'attribut pour la période et la somme. Je propose:
hourly_kwh pour la période 
hourly_kwh_count pour le compteur

**Comment by claudegel** [comment]
Voilà, j'ai ajouter les attributs
hourly_kwh_count: 496.632
daily_kwh_count: 493.22
monthly_kwh_count: 383.628
hourly_kwh: 0
daily_kwh: 3.412
monthly_kwh: 113.004
Si de votre coté c'est beau je vais pouvoir publier une nouvelle version

**Comment by djiesr** [comment]
Moi, ça me va! :) J'ai tout ce qu'il faut.

**Comment by claudegel** [comment]
Ok je publie une nouvelle version pour tout le monde. Merci

**Comment by claudegel** [comment]
J'ai trouvé comment aller chercher les valeurs aux demi-heures au lieu du scan_interval. Je vais le mettre dans le prochain release.
