### ISSUE TITLE
Hass actions to neviweb causes thermostat state to go into autoBypass which isn't appreciated by Hass-HomeKit

### ISSUE THREAD

**Issue by kris2k2** [claudegel/sinope-130#63]
Thought I'd let you know; I noticed the state itself on neviweb is recognized by their API, and displayed in the UI when used, but normally not available.  I think the hass device needs to report back 'auto' (even when its in 'autoBypass') to not break the rest of the hass ecosystem (in this case, Homekit Bridge). 

Bon travail!

2022-02-01 08:38:49 ERROR (MainThread) [homeassistant.helpers.event] Error while processing state change for climate.neviweb130_climate_living_room
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 269, in _async_state_change_dispatcher
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 433, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 397, in async_update_event_state_callback
    self.async_update_state_callback(event.data.get("new_state"))
  File "/usr/src/homeassistant/homeassistant/components/homekit/accessories.py", line 419, in async_update_state_callback
    self.async_update_state(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 444, in async_update_state
    self._async_update_state(new_state)
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 466, in _async_update_state
    homekit_hvac_action = HC_HASS_TO_HOMEKIT_ACTION[hvac_action]
KeyError: 'autoBypass'

**Comment by kris2k2** [comment]
Here's my device state which points to hvac_action as the culprit.

hvac_modes:
  - 'off'
  - auto
  - manual
  - autoBypass
min_temp: 5
max_temp: 30
preset_modes:
  - away
  - home
  - none
current_temperature: 22.6
temperature: 22.5
hvac_action: autoBypass
preset_mode: none
wattage: 1884
occupancy: home
temp_display_status: 'on'
temp_display_value: 22.5
source_type: heating
early_start: 'off'
setpoint_away: 15
load_watt_1: 1884
second_display: exteriorTemperature
heat_level: 20
keypad: unlock
backlight: alwaysOn
time_format: 24h
temperature_format: celsius
setpoint_max: 30
setpoint_min: 5
eco_status: 'off'
eco_optOut: 'off'
eco_setpoint: 'off'
eco_power_relative: 'off'
eco_power_absolute: 'off'
eco_setpoint_status: 'off'
eco_setpoint_value: null
hourly_kwh_count: 147.742
daily_kwh_count: 147.166
monthly_kwh_count: 147.166
hourly_kwh: 0
daily_kwh: 0.576
monthly_kwh: 0.576
rssi: -57
id: 223488
unit_of_measurement: celsius
device_class: temperature
friendly_name: Living Room Thermostat
supported_features: 17

**Comment by sicarriere** [comment]
Just see the same problem yesterday with homekit after update sinope-130 from 0.9.3 to 1.1,1 and if I check my climate, we don't have the good HVAC_MODES :

![image](https://user-images.githubusercontent.com/47251868/151973415-b046b1cf-159e-42b8-a7c5-cec857b952a4.png)

This is for a WiFi device. If I check "climate.py" (line 145), here the probleme :
`SUPPORTED_HVAC_WIFI_MODES = [
    HVAC_MODE_OFF,
    HVAC_MODE_AUTO,
    MODE_MANUAL,
    MODE_AUTO_BYPASS,
]`

but if I change this for :

`SUPPORTED_HVAC_WIFI_MODES = [
    HVAC_MODE_OFF,
    HVAC_MODE_AUTO,
    HVAC_MODE_HEAT,
]`

![image](https://user-images.githubusercontent.com/47251868/151973894-9814f176-bb3e-4137-a321-4d12fee26a94.png)

everything is OK. HA Climate doesn't support MODE_MANUAL or MODE_AUTO_BYPASS for HVAC_MODES

**Comment by kris2k2** [comment]
I just found the spec for hvac_mode:
https://developers.home-assistant.io/docs/core/entity/climate/

And from what I see from your climate.py is that you're allowing HVAC_WIFI_MODES to permeate into this limited value domain space.  

At the same time, I looked at /usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py to see what HomeKit likes/dislikes, and found their mapping table which translates to this:

HC_HASS_TO_HOMEKIT = {                                                
    HVAC_MODE_OFF: HC_HEAT_COOL_OFF,                                  
    HVAC_MODE_HEAT: HC_HEAT_COOL_HEAT,                                
    HVAC_MODE_COOL: HC_HEAT_COOL_COOL,                                
    HVAC_MODE_AUTO: HC_HEAT_COOL_AUTO,                                
    HVAC_MODE_HEAT_COOL: HC_HEAT_COOL_AUTO,                           
    HVAC_MODE_DRY: HC_HEAT_COOL_COOL,                                 
    HVAC_MODE_FAN_ONLY: HC_HEAT_COOL_COOL,                            
}        

Following the same logic, its just a matter of putting a translation table in place, the thermostate mode to a custom field, and mapping both inbound + outbound messages to neviweb accordingly.

**Comment by claudegel** [comment]
In Neviweb when a device is in auto mode and somebody manually change the setpoint, then neviweb report it as autoBypass. The device will return in auto mode at the next change in the auto program. 
If it is not supported yet in HA I'll change the code so when it is reported as autoBypass we will pass the HVAC_MODE_AUTO.
I'll open a new branch for these changes so you can test before we merge it into the next release.

**Comment by claudegel** [comment]
Ok check hvac_mode branch. It should work for you and let me know so I can merge it

**Comment by sicarriere** [comment]
All good for me with the hvac_mode branch.

**Comment by claudegel** [comment]
I've done a new release for hvac_mode. Thank you for reporting this

**Comment by kris2k2** [comment]
Thanks! its been stable for 24h here too.
