### ISSUE TITLE
Invalid config?

### ISSUE THREAD

**Issue by donparlor** [claudegel/sinope-130#70]
I get this notification but I am not sure what is the problem:

Logger: homeassistant.config
Source: config.py:454
First occurred: 00:15:48 (1 occurrences)
Last logged: 00:15:48

Invalid config for [automation]: Device 51dde038f7ad6909c09df0d2cc7f371d not found. Got OrderedDict([('default_config', {}), ('dhcp', {}), ('http', OrderedDict([('ssl_certificate', '/ssl/fullchain.pem'), ('ssl_key', '/ssl/privkey.pem')])), ('lovelace', OrderedDict([('resources', [OrderedDict([('url', '/hacsfiles/mini-graph-card/mini-graph-card-bundle.js'), ('type', 'module')]), OrderedDict([('url', '/hacsfiles/scheduler-card/scheduler-card.js'), ('type', 'module')])])])), ('neviweb130', OrderedDict([('username', '------------'), ('password', '----------!'), ('network',.... (See /config/configuration.yaml, line 37).

**Comment by claudegel** [comment]
Can you post your configuration.yaml for the section neviweb130 ?
What is the Sinopé device model that cause this error ? Thermostat, light ?

**Comment by donparlor** [comment]
Here is my neviweb130 section of configuration.yaml

neviweb130:
  username: -removed-@gmail.com
  password: -removed-
  network: "2610"
  scan_interval: 360

And Line 37 in configuration.yaml is empty. So I'm not sure why the error message is pointing toward this line.

**Comment by claudegel** [comment]
Sorry it should be the name that show up in neviweb on top of first page

**Comment by donparlor** [comment]
Yes, 2610 is the name of my "House" in the Neviweb app. It is showing where you pointed out in your circle.
I forgot to mention it is a FLP55 wifi thermostat

**Comment by claudegel** [comment]
Does it show up in HA

**Comment by claudegel** [comment]
Do you have statistic for kwh in Neviweb for that thermostat ? if yes we can add those in neviweb130 if you can help

**Comment by donparlor** [comment]
I created a mini-graph-card with the sensor.temperature
![Capture d’écran, le 2022-02-17 à 14 18 04](https://user-images.githubusercontent.com/97048708/154554697-6e6bcc59-6f60-4778-bd11-1bfcc7c50076.png)

And I also created a thermostat with the entity climate.neviweb130_climate_flextherm_flp55
![Capture d’écran, le 2022-02-17 à 14 18 23](https://user-images.githubusercontent.com/97048708/154554785-e3d667a4-1a0c-4ab9-9b2d-03922830067e.png)

With the  FLP55 wifi thermostat, I have the following information inside Neviweb App


![272901636_1641291699545725_1913609569346118976_n](https://user-images.githubusercontent.com/97048708/154555219-f5e4160f-c19b-4170-8f73-a74b6dd45ef5.jpg)

![273693845_470005698170189_315624194101534056_n](https://user-images.githubusercontent.com/97048708/154555237-80e298b4-f968-44f7-86e8-7ddb244b7c27.jpg)

If I can provide additional information, let me know!

**Comment by donparlor** [comment]
It seems Neviweb does not calculate cost of energy in the graph, even though I specified the cost of kW/h
![273085205_995190741102313_1033420161145444244_n](https://user-images.githubusercontent.com/97048708/154557182-a9d37ffe-0fd2-424f-b3fa-ee2d8650f6f4.jpg)

**Comment by claudegel** [comment]
So you have kwh data. We can pull it from Neviweb. But as I don't have a FLP55 could you look in Neviweb for your thermostat. Open the dev tool console. In firefox it is ctrl maj E.
then open the thermostat configuration and history in kwh mode for hourly, daily and monthly. Check in the console 
![stats](https://user-images.githubusercontent.com/4268938/154583352-7258b7cd-2827-4c2e-847b-2c8cf9a4b2a8.png)
I need the attributes for period and counter. I'don't know if it is call the same for the FLP55
if you are with Chrome go to more-tools/dev-tools to get the same tool

**Comment by donparlor** [comment]
I am not sure the kWh is really adding up. 
Here is what I see:
![Capture d’écran, le 2022-02-17 à 18 06 52](https://user-images.githubusercontent.com/97048708/154586619-4b106795-291a-4d73-b8e2-c048edc4ee47.png)

**Comment by donparlor** [comment]
In the parameters, you can see I have a value in the Load Connected (watts) field.
![Capture d’écran, le 2022-02-17 à 18 08 36](https://user-images.githubusercontent.com/97048708/154586735-09827081-9b8a-47e0-9d51-d14e3d225145.png)

**Comment by claudegel** [comment]
Ha yes I see in your graph that there is only the temperature data. So for this thermostat there is no consumption data.
So your configuration.yaml is ok, the thermostats is available and nothing look broken. The problem should be with your automation. what is the Device 51dde038f7ad6909c09df0d2cc7f371d ?

**Comment by claudegel** [comment]
Check in file /config/.storage/core.entity_registry. 51dde038f7ad6909c09df0d2cc7f371d should be there with more data about the device

**Comment by donparlor** [comment]
I used Samba Share to navigate my RPI4 but I just can't find the path you are pointing to.

**Comment by claudegel** [comment]
This is in the config/ dir where configuration.yaml is located. The .storage dir is not visible by default because there is a dot in front of the dir name. In your samba share windows you can enable show masked dir and you will see it

**Comment by donparlor** [comment]
Hello Claude! I managed to show hidden (dot) folders, and I could open core.entity_registry.  but the Device 
51dde038f7ad6909c09df0d2cc7f371d is nowhere to be found. 

The message mentions the device "not found". Maybe this is why I can't find it in core.entity_registry ??

Any other clue where I can find more information on this errror?

**Comment by claudegel** [comment]
You can check also in /config/.storage/core.device_registry and /config/.storage/core.config_entries

**Comment by donparlor** [comment]
I have a match inside core.device_registry:

{
                "config_entries": [
                    "8fdbbca7e4a83192bf84f6cc889df73b"
                ],
                "connections": [],
                "identifiers": [
                    [
                        "zwave_js",
                        "3371148266-3"
                    ],
                    [
                        "zwave_js",
                        "3371148266-3-634:769:18"
                    ]
                ],
                "id": "51dde038f7ad6909c09df0d2cc7f371d",
                "orphaned_timestamp": null
            },

**Comment by donparlor** [comment]
And while looking inside zwave_js.legacy_zwave_migration, I found this

{
    "version": 1,
    "minor_version": 1,
    "key": "zwave_js.legacy_zwave_migration",
    "data": {
        "8fdbbca7e4a83192bf84f6cc889df73b": {
            "binary_sensor.motion_and_vibration_sensor_home_security_motion_detection": {
                "node_id": 9,
                "endpoint_index": 0,
                "command_class": 113,
                "value_property_name": "Home Security",
                "value_property_key_name": "Motion sensor status",
                "value_id": "9-113-0-Home Security-Motion sensor status",
                "device_id": "82dac233d25b12fdf3caffe698fe63eb",
                "domain": "binary_sensor",
                "entity_id": "binary_sensor.motion_and_vibration_sensor_home_security_motion_detection",
                "unique_id": "3371148266.9-113-0-Home Security-Motion sensor status.8",
                "unit_of_measurement": null
            },
            "binary_sensor.motion_and_vibration_sensor_home_security_motion_detection_2": {
                "node_id": 3,
                "endpoint_index": 0,
                "command_class": 113,
                "value_property_name": "Home Security",
                "value_property_key_name": "Motion sensor status",
                "value_id": "3-113-0-Home Security-Motion sensor status",
                "device_id": "51dde038f7ad6909c09df0d2cc7f371d",
                "domain": "binary_sensor",
                "entity_id": "binary_sensor.motion_and_vibration_sensor_home_security_motion_detection_2",
                "unique_id": "3371148266.3-113-0-Home Security-Motion sensor status.8",
                "unit_of_measurement": null
            },
            "sensor.motion_and_vibration_sensor_battery_level": {
                "node_id": 9,
                "endpoint_index": 0,
                "command_class": 128,
                "value_property_name": "level",
                "value_property_key_name": null,
                "value_id": "9-128-0-level",
                "device_id": "82dac233d25b12fdf3caffe698fe63eb",
                "domain": "sensor",
                "entity_id": "sensor.motion_and_vibration_sensor_battery_level",
                "unique_id": "3371148266.9-128-0-level",
                "unit_of_measurement": "%"
            },
            "binary_sensor.motion_and_vibration_sensor_low_battery_level": {
                "node_id": 9,
                "endpoint_index": 0,
                "command_class": 128,
                "value_property_name": "isLow",
                "value_property_key_name": null,
                "value_id": "9-128-0-isLow",
                "device_id": "82dac233d25b12fdf3caffe698fe63eb",
                "domain": "binary_sensor",
                "entity_id": "binary_sensor.motion_and_vibration_sensor_low_battery_level",
                "unique_id": "3371148266.9-128-0-isLow",
                "unit_of_measurement": null
            }
        }
    }
}

**Comment by donparlor** [comment]
Basically, it seems to be my binary_sensor.motion_and_vibration_sensor_home_security_motion_detection_2

I recently installed a Zooz ZSE18 motion sensor, and I had a lot of trouble pairing it correctly. I guess the multiple pairing attempts ended up creating fake entities and now my HA is looking for a phantom device among the bad pairings. This would be my wisest guess... If you know how I can further investigate on this, let me know.

**Comment by claudegel** [comment]
Feel free o reopen if you need assitance
