### ISSUE TITLE
Heating history neviweb portal always on

### ISSUE THREAD

**Issue by fpitre75** [claudegel/sinope-130#76]
Hi Claude, since Neviweb130 V1.20 , with Neviweb portal  all zigbee sinope thermostat show heating history ON all the time also if current temperature is far over set point.

![Screenshot_20220301-083547_kindlephoto-2843837](https://user-images.githubusercontent.com/76669828/156179202-ddb2b8ff-df2e-40ed-a1a8-a9a89fecd14a.png)

**Comment by claudegel** [comment]
Ok found the bug. hvac_action was not set so history graph was using hvac_mode instead. But hvac_mode is alway set to heat.
Now hvac_action is properly set and the graph should be ok. Note that before you install this patch and restart HA there is no data for hvac_action so it won't fix the hold data in the graph. 
Please test branch history-bug. It is just climate.py that need to be changed.
Let me know so I can push new release for others

**Comment by claudegel** [comment]
It work on my side so I've pushed a new release 1.2.2
Thank you for reporting this issue
