### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by evan** [claudegel/sinope-130#84]
Looks like this change https://github.com/home-assistant/core/pull/68821 in HA 2022.4.0 broke this plugin.

```
Logger: homeassistant.setup
Source: setup.py:298
First occurred: 2:54:42 PM (1 occurrences)
Last logged: 2:54:42 PM

Unable to prepare setup for platform neviweb130.switch: Platform not found (cannot import name 'ATTR_TODAY_ENERGY_KWH' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py)).
```

Thanks!

**Comment by donparlor** [comment]
I wanted to report this bug also. Same here:

Logger: homeassistant.setup
Source: setup.py:298
First occurred: 17:20:04 (1 occurrences)
Last logged: 17:20:04

Unable to prepare setup for platform neviweb130.switch: Platform not found (cannot import name 'ATTR_TODAY_ENERGY_KWH' from 'homeassistant.components.switch' (/usr/src/homeassistant/homeassistant/components/switch/__init__.py)).

**Comment by claudegel** [comment]
I'm on it. They've removed current_power_w and today_energy_kwh from the switch component.

**Comment by donparlor** [comment]
Updated! I confirm, no more error message. Thanks Claude!

**Comment by evan** [comment]
Look good for me too. Thanks for the quick fix and for creating the plugin in the first place.
