### ISSUE TITLE
Problem with power management

### ISSUE THREAD

**Issue by djiesr** [claudegel/sinope-130#85]
Il y a dû y avoir un changement il y a quelques semaines, parce que j'ai remarqué cela il y a plusieurs jours:
eco_setpoint_value: null
hourly_kwh_count: null
daily_kwh_count: null
monthly_kwh_count: null
hourly_kwh: null
daily_kwh: null
monthly_kwh: null
rssi: null

**Comment by djiesr** [comment]
oh, sans raison, tout est redevenu correct on dirait:

eco_setpoint_status: 'off'
eco_setpoint_value: null
hourly_kwh_count: 118.928
daily_kwh_count: 118.928
monthly_kwh_count: 118.928
hourly_kwh: 0
daily_kwh: 0
monthly_kwh: 0
rssi: null

**Comment by claudegel** [comment]
Laisse moi savoir si ça se reproduit. Je vais fouiller un peu pour voir ce qui pourrait bloquer cette mise a jour des attributs. Possiblement une mise a jour de neviweb qui a bloqué ces valeurs.

**Comment by djiesr** [comment]
D'accord, j'avais ce problème depuis quelques jours, mais peut-être que la mise-à-jour de HA d'ajourd'huia réinitialisé quelque chose.

**Comment by Khayrisill** [comment]
Je remonte ce sujet car je fait fasse au même problème.
Je tente d'extraire les données de consommations et tout mes thermostats me renvoi :null

> hourly_kwh_count: null
> daily_kwh_count: null
> monthly_kwh_count: null
> hourly_kwh: null
> daily_kwh: null
> monthly_kwh: null

**Comment by claudegel** [comment]
Bonjour,

je sais que Sinopé a passer une entente avec Hilo pour devenir participant au credit hivernale et avoir une subvention d'hydro Québec pour ceux qui achèteront des appareils Sinopé pour participer à Hilo. Il est possible que Sinopé soit à modifier ses programmes en préparation de l'hiver qu approche. J'ai redémarrer plusieurs fois mon serveur HA aujourd'hui car je prépare un release en fin de semaine. Chaque fois qu'on redémarre HA les valeurs tombent à null. Je vais surveiller de mon coté pour voir si j'ai des valeurs en fin de semaine

**Comment by Khayrisill** [comment]
J'ai réussis a obtenir ces valeurs au bout d'un certain temps, mais je confirme j'ai effectué plusieur redémarage et on tombe a null dans ce cas.

**Comment by claudegel** [comment]
dans vos log est-ce que vous avez ceci
[custom_components.neviweb.climate] Got None for device_hourly_stats

**Comment by claudegel** [comment]
J'ai des valeurs 
hourly_kwh_count: 1010.958
daily_kwh_count: 1010.958
monthly_kwh_count: 1010.958
hourly_kwh: 0
daily_kwh: 0
monthly_kwh: 0

Naturellement je ne chauffe pas présentement mais je vais quand même valider davantage si les valeurs sont bonnes et aussi valider si Neviweb nous coupe si on demande trop souvent du data ou bien si il envoi un message d'erreur

**Comment by Khayrisill** [comment]
Au bout de 30 minutes à 1 heure l'acquisition des données se fait.
Je ne suis pas sur ou regarder pour vérifier les logs.

**Comment by djiesr** [comment]
Des fois j'ai des null aussi, mais aujourd'hui j'ai tout bon. 
hourly_kwh_count: 1873.445
daily_kwh_count: 1873.445
monthly_kwh_count: 1873.445
hourly_kwh: 0
daily_kwh: 0
monthly_kwh: 0
Je ne peux pas l'expliquer.

**Comment by claudegel** [comment]
Le délais est de 30 minutes entre les demandes à Neviweb.
J'ai ajouté du débug sur ce que Neviweb retourne pour hourly, daily et monthly. Ca va me permettre de voir si Neviweb envoi des messages d'erreur.
Le débug se retourve dans home-assistant.log simplement.

**Comment by Khayrisill** [comment]
Non, je ne vois rien dans les logs, J'ai des valeurs présentement, elles semblent correct si je les compares a neviweb. je vais arreter les redémarages intempestif et vérifier si elles se mettent a jours. Que me conseil tu entre le hourly ou daily pour monitorer la consomation journalière ?

hourly_kwh_count: 918.001
daily_kwh_count: 917.65
monthly_kwh_count: 917.65
hourly_kwh: 0.188
daily_kwh: 0.539
monthly_kwh: 0.539

**Comment by claudegel** [comment]
Je pense que hourly est plus flexible si tu veux voir à quel période de la journée tu consommes plus.

**Comment by claudegel** [comment]
Je vais publier une nouvelle version aujourd'hui qui ajoute du débug pour le message de retour de Neviweb pour les requêtes de stat. On verra bien si il y a des problèmes avec les réponses de Neviweb.
