### ISSUE TITLE
State attributes : null

### ISSUE THREAD

**Issue by Khayrisill** [claudegel/sinope-130#98]
Je remonte ce sujet car je fait face au même problème.
Je tente d'extraire les données de consommations et tout mes thermostats me renvoi :null

> hourly_kwh_count: null
> daily_kwh_count: null
> monthly_kwh_count: null
> hourly_kwh: null
> daily_kwh: null
> monthly_kwh: null

_Originally posted by @Khayrisill in https://github.com/claudegel/sinope-130/issues/85#issuecomment-1272185839_

**Comment by claudegel** [comment]
j'ai réouvert l'ancien #85, on va rester sur celui-ci
